package com.viesis.viescraft.init;

import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.registry.EntityRegistry;

import com.viesis.viescraft.ViesCraft;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.obsidian.EntityAirshipV1ObsidianYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstonePink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstonePurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Admin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Black;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Blue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Brown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Cyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Gray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Green;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0LightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0LightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Lime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Magenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Normal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Orange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Pink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Purple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Red;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0White;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Yellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.obsidian.EntityItemAirshipV1ObsidianYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstonePink;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstonePurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Admin;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Black;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Blue;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Brown;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Cyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Gray;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Green;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0LightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0LightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Lime;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Magenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Normal;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Orange;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Pink;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Purple;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Red;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0White;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Yellow;

public class InitEntityV3VC {
	
	private static int entityID = 3001;
	
	public static void preInit()
	{
		
		register("item_airship_v1_wood0_normal", EntityItemAirshipV1Wood0Normal.class, "item.airship.v1.wood0.normal", 64, 20, true);
		register("item_airship_v1_wood0_black", EntityItemAirshipV1Wood0Black.class, "item.airship.v1.wood0.black", 64, 20, true);
		register("item_airship_v1_wood0_blue", EntityItemAirshipV1Wood0Blue.class, "item.airship.v1.wood0.blue", 64, 20, true);
		register("item_airship_v1_wood0_brown", EntityItemAirshipV1Wood0Brown.class, "item.airship.v1.wood0.brown", 64, 20, true);
		register("item_airship_v1_wood0_cyan", EntityItemAirshipV1Wood0Cyan.class, "item.airship.v1.wood0.cyan", 64, 20, true);
		register("item_airship_v1_wood0_gray", EntityItemAirshipV1Wood0Gray.class, "item.airship.v1.wood0.gray", 64, 20, true);
		register("item_airship_v1_wood0_green", EntityItemAirshipV1Wood0Green.class, "item.airship.v1.wood0.green", 64, 20, true);
		register("item_airship_v1_wood0_lightblue", EntityItemAirshipV1Wood0LightBlue.class, "item.airship.v1.wood0.lightblue", 64, 20, true);
		register("item_airship_v1_wood0_lightgray", EntityItemAirshipV1Wood0LightGray.class, "item.airship.v1.wood0.lightgray", 64, 20, true);
		register("item_airship_v1_wood0_lime", EntityItemAirshipV1Wood0Lime.class, "item.airship.v1.wood0.lime", 64, 20, true);
		register("item_airship_v1_wood0_magenta", EntityItemAirshipV1Wood0Magenta.class, "item.airship.v1.wood0.magenta", 64, 20, true);
		register("item_airship_v1_wood0_orange", EntityItemAirshipV1Wood0Orange.class, "item.airship.v1.wood0.orange", 64, 20, true);
		register("item_airship_v1_wood0_pink", EntityItemAirshipV1Wood0Pink.class, "item.airship.v1.wood0.pink", 64, 20, true);
		register("item_airship_v1_wood0_purple", EntityItemAirshipV1Wood0Purple.class, "item.airship.v1.wood0.purple", 64, 20, true);
		register("item_airship_v1_wood0_red", EntityItemAirshipV1Wood0Red.class, "item.airship.v1.wood0.red", 64, 20, true);
		register("item_airship_v1_wood0_white", EntityItemAirshipV1Wood0White.class, "item.airship.v1.wood0.white", 64, 20, true);
		register("item_airship_v1_wood0_yellow", EntityItemAirshipV1Wood0Yellow.class, "item.airship.v1.wood0.yellow", 64, 20, true);
		register("item_airship_v1_wood0_admin", EntityItemAirshipV1Wood0Admin.class, "item.airship.v1.wood0.admin", 64, 20, true);
		
		register("item_airship_v1_iron_normal", EntityItemAirshipV1IronNormal.class, "item.airship.v1.iron.normal", 64, 20, true);
		register("item_airship_v1_iron_black", EntityItemAirshipV1IronBlack.class, "item.airship.v1.iron.black", 64, 20, true);
		register("item_airship_v1_iron_blue", EntityItemAirshipV1IronBlue.class, "item.airship.v1.iron.blue", 64, 20, true);
		register("item_airship_v1_iron_brown", EntityItemAirshipV1IronBrown.class, "item.airship.v1.iron.brown", 64, 20, true);
		register("item_airship_v1_iron_cyan", EntityItemAirshipV1IronCyan.class, "item.airship.v1.iron.cyan", 64, 20, true);
		register("item_airship_v1_iron_gray", EntityItemAirshipV1IronGray.class, "item.airship.v1.iron.gray", 64, 20, true);
		register("item_airship_v1_iron_green", EntityItemAirshipV1IronGreen.class, "item.airship.v1.iron.green", 64, 20, true);
		register("item_airship_v1_iron_lightblue", EntityItemAirshipV1IronLightBlue.class, "item.airship.v1.iron.lightblue", 64, 20, true);
		register("item_airship_v1_iron_lightgray", EntityItemAirshipV1IronLightGray.class, "item.airship.v1.iron.lightgray", 64, 20, true);
		register("item_airship_v1_iron_lime", EntityItemAirshipV1IronLime.class, "item.airship.v1.iron.lime", 64, 20, true);
		register("item_airship_v1_iron_magenta", EntityItemAirshipV1IronMagenta.class, "item.airship.v1.iron.magenta", 64, 20, true);
		register("item_airship_v1_iron_orange", EntityItemAirshipV1IronOrange.class, "item.airship.v1.iron.orange", 64, 20, true);
		register("item_airship_v1_iron_pink", EntityItemAirshipV1IronPink.class, "item.airship.v1.iron.pink", 64, 20, true);
		register("item_airship_v1_iron_purple", EntityItemAirshipV1IronPurple.class, "item.airship.v1.iron.purple", 64, 20, true);
		register("item_airship_v1_iron_red", EntityItemAirshipV1IronRed.class, "item.airship.v1.iron.red", 64, 20, true);
		register("item_airship_v1_iron_white", EntityItemAirshipV1IronWhite.class, "item.airship.v1.iron.white", 64, 20, true);
		register("item_airship_v1_iron_yellow", EntityItemAirshipV1IronYellow.class, "item.airship.v1.iron.yellow", 64, 20, true);
		register("item_airship_v1_iron_admin", EntityItemAirshipV1IronAdmin.class, "item.airship.v1.iron.admin", 64, 20, true);
		
		register("item_airship_v1_redstone_normal", EntityItemAirshipV1RedstoneNormal.class, "item.airship.v1.redstone.normal", 64, 20, true);
		register("item_airship_v1_redstone_black", EntityItemAirshipV1RedstoneBlack.class, "item.airship.v1.redstone.black", 64, 20, true);
		register("item_airship_v1_redstone_blue", EntityItemAirshipV1RedstoneBlue.class, "item.airship.v1.redstone.blue", 64, 20, true);
		register("item_airship_v1_redstone_brown", EntityItemAirshipV1RedstoneBrown.class, "item.airship.v1.redstone.brown", 64, 20, true);
		register("item_airship_v1_redstone_cyan", EntityItemAirshipV1RedstoneCyan.class, "item.airship.v1.redstone.cyan", 64, 20, true);
		register("item_airship_v1_redstone_gray", EntityItemAirshipV1RedstoneGray.class, "item.airship.v1.redstone.gray", 64, 20, true);
		register("item_airship_v1_redstone_green", EntityItemAirshipV1RedstoneGreen.class, "item.airship.v1.redstone.green", 64, 20, true);
		register("item_airship_v1_redstone_lightblue", EntityItemAirshipV1RedstoneLightBlue.class, "item.airship.v1.redstone.lightblue", 64, 20, true);
		register("item_airship_v1_redstone_lightgray", EntityItemAirshipV1RedstoneLightGray.class, "item.airship.v1.redstone.lightgray", 64, 20, true);
		register("item_airship_v1_redstone_lime", EntityItemAirshipV1RedstoneLime.class, "item.airship.v1.redstone.lime", 64, 20, true);
		register("item_airship_v1_redstone_magenta", EntityItemAirshipV1RedstoneMagenta.class, "item.airship.v1.redstone.magenta", 64, 20, true);
		register("item_airship_v1_redstone_orange", EntityItemAirshipV1RedstoneOrange.class, "item.airship.v1.redstone.orange", 64, 20, true);
		register("item_airship_v1_redstone_pink", EntityItemAirshipV1RedstonePink.class, "item.airship.v1.redstone.pink", 64, 20, true);
		register("item_airship_v1_redstone_purple", EntityItemAirshipV1RedstonePurple.class, "item.airship.v1.redstone.purple", 64, 20, true);
		register("item_airship_v1_redstone_red", EntityItemAirshipV1RedstoneRed.class, "item.airship.v1.redstone.red", 64, 20, true);
		register("item_airship_v1_redstone_white", EntityItemAirshipV1RedstoneWhite.class, "item.airship.v1.redstone.white", 64, 20, true);
		register("item_airship_v1_redstone_yellow", EntityItemAirshipV1RedstoneYellow.class, "item.airship.v1.redstone.yellow", 64, 20, true);
		register("item_airship_v1_redstone_admin", EntityItemAirshipV1RedstoneAdmin.class, "item.airship.v1.redstone.admin", 64, 20, true);
		
		register("item_airship_v1_gold_normal", EntityItemAirshipV1GoldNormal.class, "item.airship.v1.gold.normal", 64, 20, true);
		register("item_airship_v1_gold_black", EntityItemAirshipV1GoldBlack.class, "item.airship.v1.gold.black", 64, 20, true);
		register("item_airship_v1_gold_blue", EntityItemAirshipV1GoldBlue.class, "item.airship.v1.gold.blue", 64, 20, true);
		register("item_airship_v1_gold_brown", EntityItemAirshipV1GoldBrown.class, "item.airship.v1.gold.brown", 64, 20, true);
		register("item_airship_v1_gold_cyan", EntityItemAirshipV1GoldCyan.class, "item.airship.v1.gold.cyan", 64, 20, true);
		register("item_airship_v1_gold_gray", EntityItemAirshipV1GoldGray.class, "item.airship.v1.gold.gray", 64, 20, true);
		register("item_airship_v1_gold_green", EntityItemAirshipV1GoldGreen.class, "item.airship.v1.gold.green", 64, 20, true);
		register("item_airship_v1_gold_lightblue", EntityItemAirshipV1GoldLightBlue.class, "item.airship.v1.gold.lightblue", 64, 20, true);
		register("item_airship_v1_gold_lightgray", EntityItemAirshipV1GoldLightGray.class, "item.airship.v1.gold.lightgray", 64, 20, true);
		register("item_airship_v1_gold_lime", EntityItemAirshipV1GoldLime.class, "item.airship.v1.gold.lime", 64, 20, true);
		register("item_airship_v1_gold_magenta", EntityItemAirshipV1GoldMagenta.class, "item.airship.v1.gold.magenta", 64, 20, true);
		register("item_airship_v1_gold_orange", EntityItemAirshipV1GoldOrange.class, "item.airship.v1.gold.orange", 64, 20, true);
		register("item_airship_v1_gold_pink", EntityItemAirshipV1GoldPink.class, "item.airship.v1.gold.pink", 64, 20, true);
		register("item_airship_v1_gold_purple", EntityItemAirshipV1GoldPurple.class, "item.airship.v1.gold.purple", 64, 20, true);
		register("item_airship_v1_gold_red", EntityItemAirshipV1GoldRed.class, "item.airship.v1.gold.red", 64, 20, true);
		register("item_airship_v1_gold_white", EntityItemAirshipV1GoldWhite.class, "item.airship.v1.gold.white", 64, 20, true);
		register("item_airship_v1_gold_yellow", EntityItemAirshipV1GoldYellow.class, "item.airship.v1.gold.yellow", 64, 20, true);
		register("item_airship_v1_gold_admin", EntityItemAirshipV1GoldAdmin.class, "item.airship.v1.gold.admin", 64, 20, true);
		
		register("item_airship_v1_lapislazuli_normal", EntityItemAirshipV1LapisLazuliNormal.class, "item.airship.v1.lapislazuli.normal", 64, 20, true);
		register("item_airship_v1_lapislazuli_black", EntityItemAirshipV1LapisLazuliBlack.class, "item.airship.v1.lapislazuli.black", 64, 20, true);
		register("item_airship_v1_lapislazuli_blue", EntityItemAirshipV1LapisLazuliBlue.class, "item.airship.v1.lapislazuli.blue", 64, 20, true);
		register("item_airship_v1_lapislazuli_brown", EntityItemAirshipV1LapisLazuliBrown.class, "item.airship.v1.lapislazuli.brown", 64, 20, true);
		register("item_airship_v1_lapislazuli_cyan", EntityItemAirshipV1LapisLazuliCyan.class, "item.airship.v1.lapislazuli.cyan", 64, 20, true);
		register("item_airship_v1_lapislazuli_gray", EntityItemAirshipV1LapisLazuliGray.class, "item.airship.v1.lapislazuli.gray", 64, 20, true);
		register("item_airship_v1_lapislazuli_green", EntityItemAirshipV1LapisLazuliGreen.class, "item.airship.v1.lapislazuli.green", 64, 20, true);
		register("item_airship_v1_lapislazuli_lightblue", EntityItemAirshipV1LapisLazuliLightBlue.class, "item.airship.v1.lapislazuli.lightblue", 64, 20, true);
		register("item_airship_v1_lapislazuli_lightgray", EntityItemAirshipV1LapisLazuliLightGray.class, "item.airship.v1.lapislazuli.lightgray", 64, 20, true);
		register("item_airship_v1_lapislazuli_lime", EntityItemAirshipV1LapisLazuliLime.class, "item.airship.v1.lapislazuli.lime", 64, 20, true);
		register("item_airship_v1_lapislazuli_magenta", EntityItemAirshipV1LapisLazuliMagenta.class, "item.airship.v1.lapislazuli.magenta", 64, 20, true);
		register("item_airship_v1_lapislazuli_orange", EntityItemAirshipV1LapisLazuliOrange.class, "item.airship.v1.lapislazuli.orange", 64, 20, true);
		register("item_airship_v1_lapislazuli_pink", EntityItemAirshipV1LapisLazuliPink.class, "item.airship.v1.lapislazuli.pink", 64, 20, true);
		register("item_airship_v1_lapislazuli_purple", EntityItemAirshipV1LapisLazuliPurple.class, "item.airship.v1.lapislazuli.purple", 64, 20, true);
		register("item_airship_v1_lapislazuli_red", EntityItemAirshipV1LapisLazuliRed.class, "item.airship.v1.lapislazuli.red", 64, 20, true);
		register("item_airship_v1_lapislazuli_white", EntityItemAirshipV1LapisLazuliWhite.class, "item.airship.v1.lapislazuli.white", 64, 20, true);
		register("item_airship_v1_lapislazuli_yellow", EntityItemAirshipV1LapisLazuliYellow.class, "item.airship.v1.lapislazuli.yellow", 64, 20, true);
		register("item_airship_v1_lapislazuli_admin", EntityItemAirshipV1LapisLazuliAdmin.class, "item.airship.v1.lapislazuli.admin", 64, 20, true);
		
		register("item_airship_v1_obsidian_normal", EntityItemAirshipV1ObsidianNormal.class, "item.airship.v1.obsidian.normal", 64, 20, true);
		register("item_airship_v1_obsidian_black", EntityItemAirshipV1ObsidianBlack.class, "item.airship.v1.obsidian.black", 64, 20, true);
		register("item_airship_v1_obsidian_blue", EntityItemAirshipV1ObsidianBlue.class, "item.airship.v1.obsidian.blue", 64, 20, true);
		register("item_airship_v1_obsidian_brown", EntityItemAirshipV1ObsidianBrown.class, "item.airship.v1.obsidian.brown", 64, 20, true);
		register("item_airship_v1_obsidian_cyan", EntityItemAirshipV1ObsidianCyan.class, "item.airship.v1.obsidian.cyan", 64, 20, true);
		register("item_airship_v1_obsidian_gray", EntityItemAirshipV1ObsidianGray.class, "item.airship.v1.obsidian.gray", 64, 20, true);
		register("item_airship_v1_obsidian_green", EntityItemAirshipV1ObsidianGreen.class, "item.airship.v1.obsidian.green", 64, 20, true);
		register("item_airship_v1_obsidian_lightblue", EntityItemAirshipV1ObsidianLightBlue.class, "item.airship.v1.obsidian.lightblue", 64, 20, true);
		register("item_airship_v1_obsidian_lightgray", EntityItemAirshipV1ObsidianLightGray.class, "item.airship.v1.obsidian.lightgray", 64, 20, true);
		register("item_airship_v1_obsidian_lime", EntityItemAirshipV1ObsidianLime.class, "item.airship.v1.obsidian.lime", 64, 20, true);
		register("item_airship_v1_obsidian_magenta", EntityItemAirshipV1ObsidianMagenta.class, "item.airship.v1.obsidian.magenta", 64, 20, true);
		register("item_airship_v1_obsidian_orange", EntityItemAirshipV1ObsidianOrange.class, "item.airship.v1.obsidian.orange", 64, 20, true);
		register("item_airship_v1_obsidian_pink", EntityItemAirshipV1ObsidianPink.class, "item.airship.v1.obsidian.pink", 64, 20, true);
		register("item_airship_v1_obsidian_purple", EntityItemAirshipV1ObsidianPurple.class, "item.airship.v1.obsidian.purple", 64, 20, true);
		register("item_airship_v1_obsidian_red", EntityItemAirshipV1ObsidianRed.class, "item.airship.v1.obsidian.red", 64, 20, true);
		register("item_airship_v1_obsidian_white", EntityItemAirshipV1ObsidianWhite.class, "item.airship.v1.obsidian.white", 64, 20, true);
		register("item_airship_v1_obsidian_yellow", EntityItemAirshipV1ObsidianYellow.class, "item.airship.v1.obsidian.yellow", 64, 20, true);
		register("item_airship_v1_obsidian_admin", EntityItemAirshipV1ObsidianAdmin.class, "item.airship.v1.obsidian.admin", 64, 20, true);
		
		register("item_airship_v1_diamond_normal", EntityItemAirshipV1DiamondNormal.class, "item.airship.v1.diamond.normal", 64, 20, true);
		register("item_airship_v1_diamond_black", EntityItemAirshipV1DiamondBlack.class, "item.airship.v1.diamond.black", 64, 20, true);
		register("item_airship_v1_diamond_blue", EntityItemAirshipV1DiamondBlue.class, "item.airship.v1.diamond.blue", 64, 20, true);
		register("item_airship_v1_diamond_brown", EntityItemAirshipV1DiamondBrown.class, "item.airship.v1.diamond.brown", 64, 20, true);
		register("item_airship_v1_diamond_cyan", EntityItemAirshipV1DiamondCyan.class, "item.airship.v1.diamond.cyan", 64, 20, true);
		register("item_airship_v1_diamond_gray", EntityItemAirshipV1DiamondGray.class, "item.airship.v1.diamond.gray", 64, 20, true);
		register("item_airship_v1_diamond_green", EntityItemAirshipV1DiamondGreen.class, "item.airship.v1.diamond.green", 64, 20, true);
		register("item_airship_v1_diamond_lightblue", EntityItemAirshipV1DiamondLightBlue.class, "item.airship.v1.diamond.lightblue", 64, 20, true);
		register("item_airship_v1_diamond_lightgray", EntityItemAirshipV1DiamondLightGray.class, "item.airship.v1.diamond.lightgray", 64, 20, true);
		register("item_airship_v1_diamond_lime", EntityItemAirshipV1DiamondLime.class, "item.airship.v1.diamond.lime", 64, 20, true);
		register("item_airship_v1_diamond_magenta", EntityItemAirshipV1DiamondMagenta.class, "item.airship.v1.diamond.magenta", 64, 20, true);
		register("item_airship_v1_diamond_orange", EntityItemAirshipV1DiamondOrange.class, "item.airship.v1.diamond.orange", 64, 20, true);
		register("item_airship_v1_diamond_pink", EntityItemAirshipV1DiamondPink.class, "item.airship.v1.diamond.pink", 64, 20, true);
		register("item_airship_v1_diamond_purple", EntityItemAirshipV1DiamondPurple.class, "item.airship.v1.diamond.purple", 64, 20, true);
		register("item_airship_v1_diamond_red", EntityItemAirshipV1DiamondRed.class, "item.airship.v1.diamond.red", 64, 20, true);
		register("item_airship_v1_diamond_white", EntityItemAirshipV1DiamondWhite.class, "item.airship.v1.diamond.white", 64, 20, true);
		register("item_airship_v1_diamond_yellow", EntityItemAirshipV1DiamondYellow.class, "item.airship.v1.diamond.yellow", 64, 20, true);
		register("item_airship_v1_diamond_admin", EntityItemAirshipV1DiamondAdmin.class, "item.airship.v1.diamond.admin", 64, 20, true);
		
		register("item_airship_v1_emerald_normal", EntityItemAirshipV1EmeraldNormal.class, "item.airship.v1.emerald.normal", 64, 20, true);
		register("item_airship_v1_emerald_black", EntityItemAirshipV1EmeraldBlack.class, "item.airship.v1.emerald.black", 64, 20, true);
		register("item_airship_v1_emerald_blue", EntityItemAirshipV1EmeraldBlue.class, "item.airship.v1.emerald.blue", 64, 20, true);
		register("item_airship_v1_emerald_brown", EntityItemAirshipV1EmeraldBrown.class, "item.airship.v1.emerald.brown", 64, 20, true);
		register("item_airship_v1_emerald_cyan", EntityItemAirshipV1EmeraldCyan.class, "item.airship.v1.emerald.cyan", 64, 20, true);
		register("item_airship_v1_emerald_gray", EntityItemAirshipV1EmeraldGray.class, "item.airship.v1.emerald.gray", 64, 20, true);
		register("item_airship_v1_emerald_green", EntityItemAirshipV1EmeraldGreen.class, "item.airship.v1.emerald.green", 64, 20, true);
		register("item_airship_v1_emerald_lightblue", EntityItemAirshipV1EmeraldLightBlue.class, "item.airship.v1.emerald.lightblue", 64, 20, true);
		register("item_airship_v1_emerald_lightgray", EntityItemAirshipV1EmeraldLightGray.class, "item.airship.v1.emerald.lightgray", 64, 20, true);
		register("item_airship_v1_emerald_lime", EntityItemAirshipV1EmeraldLime.class, "item.airship.v1.emerald.lime", 64, 20, true);
		register("item_airship_v1_emerald_magenta", EntityItemAirshipV1EmeraldMagenta.class, "item.airship.v1.emerald.magenta", 64, 20, true);
		register("item_airship_v1_emerald_orange", EntityItemAirshipV1EmeraldOrange.class, "item.airship.v1.emerald.orange", 64, 20, true);
		register("item_airship_v1_emerald_pink", EntityItemAirshipV1EmeraldPink.class, "item.airship.v1.emerald.pink", 64, 20, true);
		register("item_airship_v1_emerald_purple", EntityItemAirshipV1EmeraldPurple.class, "item.airship.v1.emerald.purple", 64, 20, true);
		register("item_airship_v1_emerald_red", EntityItemAirshipV1EmeraldRed.class, "item.airship.v1.emerald.red", 64, 20, true);
		register("item_airship_v1_emerald_white", EntityItemAirshipV1EmeraldWhite.class, "item.airship.v1.emerald.white", 64, 20, true);
		register("item_airship_v1_emerald_yellow", EntityItemAirshipV1EmeraldYellow.class, "item.airship.v1.emerald.yellow", 64, 20, true);
		register("item_airship_v1_emerald_admin", EntityItemAirshipV1EmeraldAdmin.class, "item.airship.v1.emerald.admin", 64, 20, true);
		
		//===========================================
		
		register("airship_v1_wood0_normal", EntityAirshipV1Wood0Normal.class, "airship.v1.wood0.normal", 64, 1, true);
		register("airship_v1_wood0_black", EntityAirshipV1Wood0Black.class, "airship.v1.wood0.black", 64, 1, true);
		register("airship_v1_wood0_blue", EntityAirshipV1Wood0Blue.class, "airship.v1.wood0.blue", 64, 1, true);
		register("airship_v1_wood0_brown", EntityAirshipV1Wood0Brown.class, "airship.v1.wood0.brown", 64, 1, true);
		register("airship_v1_wood0_cyan", EntityAirshipV1Wood0Cyan.class, "airship.v1.wood0.cyan", 64, 1, true);
		register("airship_v1_wood0_gray", EntityAirshipV1Wood0Gray.class, "airship.v1.wood0.gray", 64, 1, true);
		register("airship_v1_wood0_green", EntityAirshipV1Wood0Green.class, "airship.v1.wood0.green", 64, 1, true);
		register("airship_v1_wood0_lightblue", EntityAirshipV1Wood0LightBlue.class, "airship.v1.wood0.lightblue", 64, 1, true);
		register("airship_v1_wood0_lightgray", EntityAirshipV1Wood0LightGray.class, "airship.v1.wood0.lightgray", 64, 1, true);
		register("airship_v1_wood0_lime", EntityAirshipV1Wood0Lime.class, "airship.v1.wood0.lime", 64, 1, true);
		register("airship_v1_wood0_magenta", EntityAirshipV1Wood0Magenta.class, "airship.v1.wood0.magenta", 64, 1, true);
		register("airship_v1_wood0_orange", EntityAirshipV1Wood0Orange.class, "airship.v1.wood0.orange", 64, 1, true);
		register("airship_v1_wood0_pink", EntityAirshipV1Wood0Pink.class, "airship.v1.wood0.pink", 64, 1, true);
		register("airship_v1_wood0_purple", EntityAirshipV1Wood0Purple.class, "airship.v1.wood0.purple", 64, 1, true);
		register("airship_v1_wood0_red", EntityAirshipV1Wood0Red.class, "airship.v1.wood0.red", 64, 1, true);
		register("airship_v1_wood0_white", EntityAirshipV1Wood0White.class, "airship.v1.wood0.white", 64, 1, true);
		register("airship_v1_wood0_yellow", EntityAirshipV1Wood0Yellow.class, "airship.v1.wood0.yellow", 64, 1, true);
		register("airship_v1_wood0_admin", EntityAirshipV1Wood0Admin.class, "airship.v1.wood0.admin", 64, 1, true);
		
		register("airship_v1_iron_normal", EntityAirshipV1IronNormal.class, "airship.v1.iron.normal", 64, 1, true);
		register("airship_v1_iron_black", EntityAirshipV1IronBlack.class, "airship.v1.iron.black", 64, 1, true);
		register("airship_v1_iron_blue", EntityAirshipV1IronBlue.class, "airship.v1.iron.blue", 64, 1, true);
		register("airship_v1_iron_brown", EntityAirshipV1IronBrown.class, "airship.v1.iron.brown", 64, 1, true);
		register("airship_v1_iron_cyan", EntityAirshipV1IronCyan.class, "airship.v1.iron.cyan", 64, 1, true);
		register("airship_v1_iron_gray", EntityAirshipV1IronGray.class, "airship.v1.iron.gray", 64, 1, true);
		register("airship_v1_iron_green", EntityAirshipV1IronGreen.class, "airship.v1.iron.green", 64, 1, true);
		register("airship_v1_iron_lightblue", EntityAirshipV1IronLightBlue.class, "airship.v1.iron.lightblue", 64, 1, true);
		register("airship_v1_iron_lightgray", EntityAirshipV1IronLightGray.class, "airship.v1.iron.lightgray", 64, 1, true);
		register("airship_v1_iron_lime", EntityAirshipV1IronLime.class, "airship.v1.iron.lime", 64, 1, true);
		register("airship_v1_iron_magenta", EntityAirshipV1IronMagenta.class, "airship.v1.iron.magenta", 64, 1, true);
		register("airship_v1_iron_orange", EntityAirshipV1IronOrange.class, "airship.v1.iron.orange", 64, 1, true);
		register("airship_v1_iron_pink", EntityAirshipV1IronPink.class, "airship.v1.iron.pink", 64, 1, true);
		register("airship_v1_iron_purple", EntityAirshipV1IronPurple.class, "airship.v1.iron.purple", 64, 1, true);
		register("airship_v1_iron_red", EntityAirshipV1IronRed.class, "airship.v1.iron.red", 64, 1, true);
		register("airship_v1_iron_white", EntityAirshipV1IronWhite.class, "airship.v1.iron.white", 64, 1, true);
		register("airship_v1_iron_yellow", EntityAirshipV1IronYellow.class, "airship.v1.iron.yellow", 64, 1, true);
		register("airship_v1_iron_admin", EntityAirshipV1IronAdmin.class, "airship.v1.iron.admin", 64, 1, true);
		
		register("airship_v1_redstone_normal", EntityAirshipV1RedstoneNormal.class, "airship.v1.redstone.normal", 64, 1, true);
		register("airship_v1_redstone_black", EntityAirshipV1RedstoneBlack.class, "airship.v1.redstone.black", 64, 1, true);
		register("airship_v1_redstone_blue", EntityAirshipV1RedstoneBlue.class, "airship.v1.redstone.blue", 64, 1, true);
		register("airship_v1_redstone_brown", EntityAirshipV1RedstoneBrown.class, "airship.v1.redstone.brown", 64, 1, true);
		register("airship_v1_redstone_cyan", EntityAirshipV1RedstoneCyan.class, "airship.v1.redstone.cyan", 64, 1, true);
		register("airship_v1_redstone_gray", EntityAirshipV1RedstoneGray.class, "airship.v1.redstone.gray", 64, 1, true);
		register("airship_v1_redstone_green", EntityAirshipV1RedstoneGreen.class, "airship.v1.redstone.green", 64, 1, true);
		register("airship_v1_redstone_lightblue", EntityAirshipV1RedstoneLightBlue.class, "airship.v1.redstone.lightblue", 64, 1, true);
		register("airship_v1_redstone_lightgray", EntityAirshipV1RedstoneLightGray.class, "airship.v1.redstone.lightgray", 64, 1, true);
		register("airship_v1_redstone_lime", EntityAirshipV1RedstoneLime.class, "airship.v1.redstone.lime", 64, 1, true);
		register("airship_v1_redstone_magenta", EntityAirshipV1RedstoneMagenta.class, "airship.v1.redstone.magenta", 64, 1, true);
		register("airship_v1_redstone_orange", EntityAirshipV1RedstoneOrange.class, "airship.v1.redstone.orange", 64, 1, true);
		register("airship_v1_redstone_pink", EntityAirshipV1RedstonePink.class, "airship.v1.redstone.pink", 64, 1, true);
		register("airship_v1_redstone_purple", EntityAirshipV1RedstonePurple.class, "airship.v1.redstone.purple", 64, 1, true);
		register("airship_v1_redstone_red", EntityAirshipV1RedstoneRed.class, "airship.v1.redstone.red", 64, 1, true);
		register("airship_v1_redstone_white", EntityAirshipV1RedstoneWhite.class, "airship.v1.redstone.white", 64, 1, true);
		register("airship_v1_redstone_yellow", EntityAirshipV1RedstoneYellow.class, "airship.v1.redstone.yellow", 64, 1, true);
		register("airship_v1_redstone_admin", EntityAirshipV1RedstoneAdmin.class, "airship.v1.redstone.admin", 64, 1, true);
		
		register("airship_v1_gold_normal", EntityAirshipV1GoldNormal.class, "airship.v1.gold.normal", 64, 1, true);
		register("airship_v1_gold_black", EntityAirshipV1GoldBlack.class, "airship.v1.gold.black", 64, 1, true);
		register("airship_v1_gold_blue", EntityAirshipV1GoldBlue.class, "airship.v1.gold.blue", 64, 1, true);
		register("airship_v1_gold_brown", EntityAirshipV1GoldBrown.class, "airship.v1.gold.brown", 64, 1, true);
		register("airship_v1_gold_cyan", EntityAirshipV1GoldCyan.class, "airship.v1.gold.cyan", 64, 1, true);
		register("airship_v1_gold_gray", EntityAirshipV1GoldGray.class, "airship.v1.gold.gray", 64, 1, true);
		register("airship_v1_gold_green", EntityAirshipV1GoldGreen.class, "airship.v1.gold.green", 64, 1, true);
		register("airship_v1_gold_lightblue", EntityAirshipV1GoldLightBlue.class, "airship.v1.gold.lightblue", 64, 1, true);
		register("airship_v1_gold_lightgray", EntityAirshipV1GoldLightGray.class, "airship.v1.gold.lightgray", 64, 1, true);
		register("airship_v1_gold_lime", EntityAirshipV1GoldLime.class, "airship.v1.gold.lime", 64, 1, true);
		register("airship_v1_gold_magenta", EntityAirshipV1GoldMagenta.class, "airship.v1.gold.magenta", 64, 1, true);
		register("airship_v1_gold_orange", EntityAirshipV1GoldOrange.class, "airship.v1.gold.orange", 64, 1, true);
		register("airship_v1_gold_pink", EntityAirshipV1GoldPink.class, "airship.v1.gold.pink", 64, 1, true);
		register("airship_v1_gold_purple", EntityAirshipV1GoldPurple.class, "airship.v1.gold.purple", 64, 1, true);
		register("airship_v1_gold_red", EntityAirshipV1GoldRed.class, "airship.v1.gold.red", 64, 1, true);
		register("airship_v1_gold_white", EntityAirshipV1GoldWhite.class, "airship.v1.gold.white", 64, 1, true);
		register("airship_v1_gold_yellow", EntityAirshipV1GoldYellow.class, "airship.v1.gold.yellow", 64, 1, true);
		register("airship_v1_gold_admin", EntityAirshipV1GoldAdmin.class, "airship.v1.gold.admin", 64, 1, true);
		
		register("airship_v1_lapislazuli_normal", EntityAirshipV1LapisLazuliNormal.class, "airship.v1.lapislazuli.normal", 64, 1, true);
		register("airship_v1_lapislazuli_black", EntityAirshipV1LapisLazuliBlack.class, "airship.v1.lapislazuli.black", 64, 1, true);
		register("airship_v1_lapislazuli_blue", EntityAirshipV1LapisLazuliBlue.class, "airship.v1.lapislazuli.blue", 64, 1, true);
		register("airship_v1_lapislazuli_brown", EntityAirshipV1LapisLazuliBrown.class, "airship.v1.lapislazuli.brown", 64, 1, true);
		register("airship_v1_lapislazuli_cyan", EntityAirshipV1LapisLazuliCyan.class, "airship.v1.lapislazuli.cyan", 64, 1, true);
		register("airship_v1_lapislazuli_gray", EntityAirshipV1LapisLazuliGray.class, "airship.v1.lapislazuli.gray", 64, 1, true);
		register("airship_v1_lapislazuli_green", EntityAirshipV1LapisLazuliGreen.class, "airship.v1.lapislazuli.green", 64, 1, true);
		register("airship_v1_lapislazuli_lightblue", EntityAirshipV1LapisLazuliLightBlue.class, "airship.v1.lapislazuli.lightblue", 64, 1, true);
		register("airship_v1_lapislazuli_lightgray", EntityAirshipV1LapisLazuliLightGray.class, "airship.v1.lapislazuli.lightgray", 64, 1, true);
		register("airship_v1_lapislazuli_lime", EntityAirshipV1LapisLazuliLime.class, "airship.v1.lapislazuli.lime", 64, 1, true);
		register("airship_v1_lapislazuli_magenta", EntityAirshipV1LapisLazuliMagenta.class, "airship.v1.lapislazuli.magenta", 64, 1, true);
		register("airship_v1_lapislazuli_orange", EntityAirshipV1LapisLazuliOrange.class, "airship.v1.lapislazuli.orange", 64, 1, true);
		register("airship_v1_lapislazuli_pink", EntityAirshipV1LapisLazuliPink.class, "airship.v1.lapislazuli.pink", 64, 1, true);
		register("airship_v1_lapislazuli_purple", EntityAirshipV1LapisLazuliPurple.class, "airship.v1.lapislazuli.purple", 64, 1, true);
		register("airship_v1_lapislazuli_red", EntityAirshipV1LapisLazuliRed.class, "airship.v1.lapislazuli.red", 64, 1, true);
		register("airship_v1_lapislazuli_white", EntityAirshipV1LapisLazuliWhite.class, "airship.v1.lapislazuli.white", 64, 1, true);
		register("airship_v1_lapislazuli_yellow", EntityAirshipV1LapisLazuliYellow.class, "airship.v1.lapislazuli.yellow", 64, 1, true);
		register("airship_v1_lapislazuli_admin", EntityAirshipV1LapisLazuliAdmin.class, "airship.v1.lapislazuli.admin", 64, 1, true);
		
		register("airship_v1_obsidian_normal", EntityAirshipV1ObsidianNormal.class, "airship.v1.obsidian.normal", 64, 1, true);
		register("airship_v1_obsidian_black", EntityAirshipV1ObsidianBlack.class, "airship.v1.obsidian.black", 64, 1, true);
		register("airship_v1_obsidian_blue", EntityAirshipV1ObsidianBlue.class, "airship.v1.obsidian.blue", 64, 1, true);
		register("airship_v1_obsidian_brown", EntityAirshipV1ObsidianBrown.class, "airship.v1.obsidian.brown", 64, 1, true);
		register("airship_v1_obsidian_cyan", EntityAirshipV1ObsidianCyan.class, "airship.v1.obsidian.cyan", 64, 1, true);
		register("airship_v1_obsidian_gray", EntityAirshipV1ObsidianGray.class, "airship.v1.obsidian.gray", 64, 1, true);
		register("airship_v1_obsidian_green", EntityAirshipV1ObsidianGreen.class, "airship.v1.obsidian.green", 64, 1, true);
		register("airship_v1_obsidian_lightblue", EntityAirshipV1ObsidianLightBlue.class, "airship.v1.obsidian.lightblue", 64, 1, true);
		register("airship_v1_obsidian_lightgray", EntityAirshipV1ObsidianLightGray.class, "airship.v1.obsidian.lightgray", 64, 1, true);
		register("airship_v1_obsidian_lime", EntityAirshipV1ObsidianLime.class, "airship.v1.obsidian.lime", 64, 1, true);
		register("airship_v1_obsidian_magenta", EntityAirshipV1ObsidianMagenta.class, "airship.v1.obsidian.magenta", 64, 1, true);
		register("airship_v1_obsidian_orange", EntityAirshipV1ObsidianOrange.class, "airship.v1.obsidian.orange", 64, 1, true);
		register("airship_v1_obsidian_pink", EntityAirshipV1ObsidianPink.class, "airship.v1.obsidian.pink", 64, 1, true);
		register("airship_v1_obsidian_purple", EntityAirshipV1ObsidianPurple.class, "airship.v1.obsidian.purple", 64, 1, true);
		register("airship_v1_obsidian_red", EntityAirshipV1ObsidianRed.class, "airship.v1.obsidian.red", 64, 1, true);
		register("airship_v1_obsidian_white", EntityAirshipV1ObsidianWhite.class, "airship.v1.obsidian.white", 64, 1, true);
		register("airship_v1_obsidian_yellow", EntityAirshipV1ObsidianYellow.class, "airship.v1.obsidian.yellow", 64, 1, true);
		register("airship_v1_obsidian_admin", EntityAirshipV1ObsidianAdmin.class, "airship.v1.obsidian.admin", 64, 1, true);
		
		register("airship_v1_diamond_normal", EntityAirshipV1DiamondNormal.class, "airship.v1.diamond.normal", 64, 1, true);
		register("airship_v1_diamond_black", EntityAirshipV1DiamondBlack.class, "airship.v1.diamond.black", 64, 1, true);
		register("airship_v1_diamond_blue", EntityAirshipV1DiamondBlue.class, "airship.v1.diamond.blue", 64, 1, true);
		register("airship_v1_diamond_brown", EntityAirshipV1DiamondBrown.class, "airship.v1.diamond.brown", 64, 1, true);
		register("airship_v1_diamond_cyan", EntityAirshipV1DiamondCyan.class, "airship.v1.diamond.cyan", 64, 1, true);
		register("airship_v1_diamond_gray", EntityAirshipV1DiamondGray.class, "airship.v1.diamond.gray", 64, 1, true);
		register("airship_v1_diamond_green", EntityAirshipV1DiamondGreen.class, "airship.v1.diamond.green", 64, 1, true);
		register("airship_v1_diamond_lightblue", EntityAirshipV1DiamondLightBlue.class, "airship.v1.diamond.lightblue", 64, 1, true);
		register("airship_v1_diamond_lightgray", EntityAirshipV1DiamondLightGray.class, "airship.v1.diamond.lightgray", 64, 1, true);
		register("airship_v1_diamond_lime", EntityAirshipV1DiamondLime.class, "airship.v1.diamond.lime", 64, 1, true);
		register("airship_v1_diamond_magenta", EntityAirshipV1DiamondMagenta.class, "airship.v1.diamond.magenta", 64, 1, true);
		register("airship_v1_diamond_orange", EntityAirshipV1DiamondOrange.class, "airship.v1.diamond.orange", 64, 1, true);
		register("airship_v1_diamond_pink", EntityAirshipV1DiamondPink.class, "airship.v1.diamond.pink", 64, 1, true);
		register("airship_v1_diamond_purple", EntityAirshipV1DiamondPurple.class, "airship.v1.diamond.purple", 64, 1, true);
		register("airship_v1_diamond_red", EntityAirshipV1DiamondRed.class, "airship.v1.diamond.red", 64, 1, true);
		register("airship_v1_diamond_white", EntityAirshipV1DiamondWhite.class, "airship.v1.diamond.white", 64, 1, true);
		register("airship_v1_diamond_yellow", EntityAirshipV1DiamondYellow.class, "airship.v1.diamond.yellow", 64, 1, true);
		register("airship_v1_diamond_admin", EntityAirshipV1DiamondAdmin.class, "airship.v1.diamond.admin", 64, 1, true);
		
		register("airship_v1_emerald_normal", EntityAirshipV1EmeraldNormal.class, "airship.v1.emerald.normal", 64, 1, true);
		register("airship_v1_emerald_black", EntityAirshipV1EmeraldBlack.class, "airship.v1.emerald.black", 64, 1, true);
		register("airship_v1_emerald_blue", EntityAirshipV1EmeraldBlue.class, "airship.v1.emerald.blue", 64, 1, true);
		register("airship_v1_emerald_brown", EntityAirshipV1EmeraldBrown.class, "airship.v1.emerald.brown", 64, 1, true);
		register("airship_v1_emerald_cyan", EntityAirshipV1EmeraldCyan.class, "airship.v1.emerald.cyan", 64, 1, true);
		register("airship_v1_emerald_gray", EntityAirshipV1EmeraldGray.class, "airship.v1.emerald.gray", 64, 1, true);
		register("airship_v1_emerald_green", EntityAirshipV1EmeraldGreen.class, "airship.v1.emerald.green", 64, 1, true);
		register("airship_v1_emerald_lightblue", EntityAirshipV1EmeraldLightBlue.class, "airship.v1.emerald.lightblue", 64, 1, true);
		register("airship_v1_emerald_lightgray", EntityAirshipV1EmeraldLightGray.class, "airship.v1.emerald.lightgray", 64, 1, true);
		register("airship_v1_emerald_lime", EntityAirshipV1EmeraldLime.class, "airship.v1.emerald.lime", 64, 1, true);
		register("airship_v1_emerald_magenta", EntityAirshipV1EmeraldMagenta.class, "airship.v1.emerald.magenta", 64, 1, true);
		register("airship_v1_emerald_orange", EntityAirshipV1EmeraldOrange.class, "airship.v1.emerald.orange", 64, 1, true);
		register("airship_v1_emerald_pink", EntityAirshipV1EmeraldPink.class, "airship.v1.emerald.pink", 64, 1, true);
		register("airship_v1_emerald_purple", EntityAirshipV1EmeraldPurple.class, "airship.v1.emerald.purple", 64, 1, true);
		register("airship_v1_emerald_red", EntityAirshipV1EmeraldRed.class, "airship.v1.emerald.red", 64, 1, true);
		register("airship_v1_emerald_white", EntityAirshipV1EmeraldWhite.class, "airship.v1.emerald.white", 64, 1, true);
		register("airship_v1_emerald_yellow", EntityAirshipV1EmeraldYellow.class, "airship.v1.emerald.yellow", 64, 1, true);
		register("airship_v1_emerald_admin", EntityAirshipV1EmeraldAdmin.class, "airship.v1.emerald.admin", 64, 1, true);
		
	}
	
	public static void register(String name, Class<? extends Entity> entityClass, String entityName, int trackingRange, int updateFrequency, boolean sendsVelocityUpdates)
	{
		EntityRegistry.registerModEntity(new ResourceLocation("vc:" + name), entityClass, entityName, entityID++, ViesCraft.instance, trackingRange, updateFrequency, sendsVelocityUpdates);
	}
}
