package com.viesis.viescraft.client;

import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.client.registry.RenderingRegistry;

import com.viesis.viescraft.api.ItemsVC;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.RenderAirshipYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Black;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Blue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Brown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Cyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Gray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Green;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2LightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2LightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Lime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Magenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Normal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Orange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Pink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Purple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Red;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2White;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.RenderAirshipV2Yellow;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipBlack;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipBrown;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipCyan;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipGreen;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipLime;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipNormal;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipOrange;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipPink;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipPurple;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipRed;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipWhite;
import com.viesis.viescraft.client.entity.render.projectile.v1.RenderItemAirshipYellow;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Black;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Blue;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Brown;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Cyan;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Gray;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Green;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2LightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2LightGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Lime;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Magenta;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Normal;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Orange;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Pink;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Purple;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Red;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2White;
import com.viesis.viescraft.client.entity.render.projectile.v2.RenderItemAirshipV2Yellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Black;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Blue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Brown;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Cyan;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Gray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Green;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2LightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2LightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Lime;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Magenta;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Normal;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Orange;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Pink;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Purple;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Red;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2White;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Yellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipYellow;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Black;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Blue;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Brown;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Cyan;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Gray;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Green;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2LightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2LightGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Lime;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Magenta;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Normal;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Orange;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Pink;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Purple;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Red;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2White;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Yellow;

public final class InitEntityVCRender extends ItemsVC {
	
	public static RenderManager EARender = Minecraft.getMinecraft().getRenderManager(); 
	
	public static void registerRenders()
	{
		registerRender(EntityItemAirshipNormal.class,  new RenderItemAirshipNormal(EARender));
		registerRender(EntityItemAirshipBlack.class,  new RenderItemAirshipBlack(EARender));
		registerRender(EntityItemAirshipBlue.class,  new RenderItemAirshipBlue(EARender));
		registerRender(EntityItemAirshipBrown.class,  new RenderItemAirshipBrown(EARender));
		registerRender(EntityItemAirshipCyan.class,  new RenderItemAirshipCyan(EARender));
		registerRender(EntityItemAirshipGray.class,  new RenderItemAirshipGray(EARender));
		registerRender(EntityItemAirshipGreen.class,  new RenderItemAirshipGreen(EARender));
		registerRender(EntityItemAirshipLightBlue.class,  new RenderItemAirshipLightBlue(EARender));
		registerRender(EntityItemAirshipLightGray.class,  new RenderItemAirshipLightGray(EARender));
		registerRender(EntityItemAirshipLime.class,  new RenderItemAirshipLime(EARender));
		registerRender(EntityItemAirshipMagenta.class,  new RenderItemAirshipMagenta(EARender));
		registerRender(EntityItemAirshipOrange.class,  new RenderItemAirshipOrange(EARender));
		registerRender(EntityItemAirshipPink.class,  new RenderItemAirshipPink(EARender));
		registerRender(EntityItemAirshipPurple.class,  new RenderItemAirshipPurple(EARender));
		registerRender(EntityItemAirshipRed.class,  new RenderItemAirshipRed(EARender));
		registerRender(EntityItemAirshipWhite.class,  new RenderItemAirshipWhite(EARender));
		registerRender(EntityItemAirshipYellow.class,  new RenderItemAirshipYellow(EARender));
		
		
		registerRender(EntityItemAirshipV2Normal.class,  new RenderItemAirshipV2Normal(EARender));
		registerRender(EntityItemAirshipV2Black.class,  new RenderItemAirshipV2Black(EARender));
		registerRender(EntityItemAirshipV2Blue.class,  new RenderItemAirshipV2Blue(EARender));
		registerRender(EntityItemAirshipV2Brown.class,  new RenderItemAirshipV2Brown(EARender));
		registerRender(EntityItemAirshipV2Cyan.class,  new RenderItemAirshipV2Cyan(EARender));
		registerRender(EntityItemAirshipV2Gray.class,  new RenderItemAirshipV2Gray(EARender));
		registerRender(EntityItemAirshipV2Green.class,  new RenderItemAirshipV2Green(EARender));
		registerRender(EntityItemAirshipV2LightBlue.class,  new RenderItemAirshipV2LightBlue(EARender));
		registerRender(EntityItemAirshipV2LightGray.class,  new RenderItemAirshipV2LightGray(EARender));
		registerRender(EntityItemAirshipV2Lime.class,  new RenderItemAirshipV2Lime(EARender));
		registerRender(EntityItemAirshipV2Magenta.class,  new RenderItemAirshipV2Magenta(EARender));
		registerRender(EntityItemAirshipV2Orange.class,  new RenderItemAirshipV2Orange(EARender));
		registerRender(EntityItemAirshipV2Pink.class,  new RenderItemAirshipV2Pink(EARender));
		registerRender(EntityItemAirshipV2Purple.class,  new RenderItemAirshipV2Purple(EARender));
		registerRender(EntityItemAirshipV2Red.class,  new RenderItemAirshipV2Red(EARender));
		registerRender(EntityItemAirshipV2White.class,  new RenderItemAirshipV2White(EARender));
		registerRender(EntityItemAirshipV2Yellow.class,  new RenderItemAirshipV2Yellow(EARender));
		
		//===========================================================================
		
		registerRender(EntityAirshipNormal.class,  new RenderAirshipNormal(EARender));
		registerRender(EntityAirshipBlack.class,  new RenderAirshipBlack(EARender));
		registerRender(EntityAirshipBlue.class,  new RenderAirshipBlue(EARender));
		registerRender(EntityAirshipBrown.class,  new RenderAirshipBrown(EARender));
		registerRender(EntityAirshipCyan.class,  new RenderAirshipCyan(EARender));
		registerRender(EntityAirshipGray.class,  new RenderAirshipGray(EARender));
		registerRender(EntityAirshipGreen.class,  new RenderAirshipGreen(EARender));
		registerRender(EntityAirshipLightBlue.class,  new RenderAirshipLightBlue(EARender));
		registerRender(EntityAirshipLightGray.class,  new RenderAirshipLightGray(EARender));
		registerRender(EntityAirshipLime.class,  new RenderAirshipLime(EARender));
		registerRender(EntityAirshipMagenta.class,  new RenderAirshipMagenta(EARender));
		registerRender(EntityAirshipOrange.class,  new RenderAirshipOrange(EARender));
		registerRender(EntityAirshipPink.class,  new RenderAirshipPink(EARender));
		registerRender(EntityAirshipPurple.class,  new RenderAirshipPurple(EARender));
		registerRender(EntityAirshipRed.class,  new RenderAirshipRed(EARender));
		registerRender(EntityAirshipWhite.class,  new RenderAirshipWhite(EARender));
		registerRender(EntityAirshipYellow.class,  new RenderAirshipYellow(EARender));
		
		
		registerRender(EntityAirshipV2Normal.class,  new RenderAirshipV2Normal(EARender));
		registerRender(EntityAirshipV2Black.class,  new RenderAirshipV2Black(EARender));
		registerRender(EntityAirshipV2Blue.class,  new RenderAirshipV2Blue(EARender));
		registerRender(EntityAirshipV2Brown.class,  new RenderAirshipV2Brown(EARender));
		registerRender(EntityAirshipV2Cyan.class,  new RenderAirshipV2Cyan(EARender));
		registerRender(EntityAirshipV2Gray.class,  new RenderAirshipV2Gray(EARender));
		registerRender(EntityAirshipV2Green.class,  new RenderAirshipV2Green(EARender));
		registerRender(EntityAirshipV2LightBlue.class,  new RenderAirshipV2LightBlue(EARender));
		registerRender(EntityAirshipV2LightGray.class,  new RenderAirshipV2LightGray(EARender));
		registerRender(EntityAirshipV2Lime.class,  new RenderAirshipV2Lime(EARender));
		registerRender(EntityAirshipV2Magenta.class,  new RenderAirshipV2Magenta(EARender));
		registerRender(EntityAirshipV2Orange.class,  new RenderAirshipV2Orange(EARender));
		registerRender(EntityAirshipV2Pink.class,  new RenderAirshipV2Pink(EARender));
		registerRender(EntityAirshipV2Purple.class,  new RenderAirshipV2Purple(EARender));
		registerRender(EntityAirshipV2Red.class,  new RenderAirshipV2Red(EARender));
		registerRender(EntityAirshipV2White.class,  new RenderAirshipV2White(EARender));
		registerRender(EntityAirshipV2Yellow.class,  new RenderAirshipV2Yellow(EARender));
		
	}
	
	public static void registerRender(Class<? extends Entity> classIn, Render<? extends Entity> renderItem)
	{
		RenderingRegistry.registerEntityRenderingHandler(classIn, renderItem);
	}
}
