package com.viesis.viescraft.client;

import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.client.registry.RenderingRegistry;

import com.viesis.viescraft.api.ItemsVC;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.diamond.RenderAirshipV1DiamondYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.emerald.RenderAirshipV1EmeraldYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.gold.RenderAirshipV1GoldYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.iron.RenderAirshipV1IronYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.lapislazuli.RenderAirshipV1LapisLazuliYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstonePink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstonePurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.redstone.RenderAirshipV1RedstoneYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Admin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Black;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Blue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Brown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Cyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Gray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Green;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0LightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0LightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Lime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Magenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Normal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Orange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Pink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Purple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Red;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0White;
import com.viesis.viescraft.client.entity.render.airshipcolors.v1.wood0.RenderAirshipV1Wood0Yellow;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondBlack;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondBrown;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondCyan;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondGreen;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondLime;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondNormal;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondOrange;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondPink;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondPurple;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondRed;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondWhite;
import com.viesis.viescraft.client.entity.render.projectile.v1.diamond.RenderItemAirshipV1DiamondYellow;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldBlack;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldBrown;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldCyan;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldGreen;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldLime;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldNormal;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldOrange;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldPink;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldPurple;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldRed;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldWhite;
import com.viesis.viescraft.client.entity.render.projectile.v1.emerald.RenderItemAirshipV1EmeraldYellow;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldBlack;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldBrown;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldCyan;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldGreen;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldLime;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldNormal;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldOrange;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldPink;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldPurple;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldRed;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldWhite;
import com.viesis.viescraft.client.entity.render.projectile.v1.gold.RenderItemAirshipV1GoldYellow;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronBlack;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronBrown;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronCyan;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronGreen;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronLime;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronNormal;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronOrange;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronPink;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronPurple;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronRed;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronWhite;
import com.viesis.viescraft.client.entity.render.projectile.v1.iron.RenderItemAirshipV1IronYellow;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliBlack;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliBrown;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliCyan;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliGreen;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliLime;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliNormal;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliOrange;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliPink;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliPurple;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliRed;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliWhite;
import com.viesis.viescraft.client.entity.render.projectile.v1.lapislazuli.RenderItemAirshipV1LapisLazuliYellow;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneBlack;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneBrown;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneCyan;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneGreen;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneLime;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneNormal;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneOrange;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstonePink;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstonePurple;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneRed;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneWhite;
import com.viesis.viescraft.client.entity.render.projectile.v1.redstone.RenderItemAirshipV1RedstoneYellow;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Admin;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Black;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Blue;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Brown;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Cyan;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Gray;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Green;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0LightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0LightGray;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Lime;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Magenta;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Normal;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Orange;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Pink;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Purple;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Red;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0White;
import com.viesis.viescraft.client.entity.render.projectile.v1.wood0.RenderItemAirshipV1Wood0Yellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.diamond.EntityAirshipV1DiamondYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.emerald.EntityAirshipV1EmeraldYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.gold.EntityAirshipV1GoldYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.iron.EntityAirshipV1IronYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliPink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.lapislazuli.EntityAirshipV1LapisLazuliYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneLime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstonePink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstonePurple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneRed;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v1.redstone.EntityAirshipV1RedstoneYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Admin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Black;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Blue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Brown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Cyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Gray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Green;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0LightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0LightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Lime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Magenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Normal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Orange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Pink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Purple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Red;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0White;
import com.viesis.viescraft.common.entity.airshipcolors.v1.wood0.EntityAirshipV1Wood0Yellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.diamond.EntityItemAirshipV1DiamondYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.emerald.EntityItemAirshipV1EmeraldYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.gold.EntityItemAirshipV1GoldYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.iron.EntityItemAirshipV1IronYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliPink;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliPurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.lapislazuli.EntityItemAirshipV1LapisLazuliYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneBlack;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneBrown;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneCyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneGreen;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneLime;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneNormal;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneOrange;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstonePink;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstonePurple;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneRed;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneWhite;
import com.viesis.viescraft.common.entity.airshipitems.v1.redstone.EntityItemAirshipV1RedstoneYellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Admin;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Black;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Blue;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Brown;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Cyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Gray;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Green;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0LightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0LightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Lime;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Magenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Normal;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Orange;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Pink;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Purple;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Red;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0White;
import com.viesis.viescraft.common.entity.airshipitems.v1.wood0.EntityItemAirshipV1Wood0Yellow;

public final class InitEntityV1VCRender extends ItemsVC {
	
	public static RenderManager VCRender = Minecraft.getMinecraft().getRenderManager(); 
	
	public static void registerRenders()
	{
		
		registerRender(EntityItemAirshipV1Wood0Normal.class, new RenderItemAirshipV1Wood0Normal(VCRender));
		registerRender(EntityItemAirshipV1Wood0Black.class, new RenderItemAirshipV1Wood0Black(VCRender));
		registerRender(EntityItemAirshipV1Wood0Blue.class, new RenderItemAirshipV1Wood0Blue(VCRender));
		registerRender(EntityItemAirshipV1Wood0Brown.class, new RenderItemAirshipV1Wood0Brown(VCRender));
		registerRender(EntityItemAirshipV1Wood0Cyan.class, new RenderItemAirshipV1Wood0Cyan(VCRender));
		registerRender(EntityItemAirshipV1Wood0Gray.class, new RenderItemAirshipV1Wood0Gray(VCRender));
		registerRender(EntityItemAirshipV1Wood0Green.class, new RenderItemAirshipV1Wood0Green(VCRender));
		registerRender(EntityItemAirshipV1Wood0LightBlue.class, new RenderItemAirshipV1Wood0LightBlue(VCRender));
		registerRender(EntityItemAirshipV1Wood0LightGray.class, new RenderItemAirshipV1Wood0LightGray(VCRender));
		registerRender(EntityItemAirshipV1Wood0Lime.class, new RenderItemAirshipV1Wood0Lime(VCRender));
		registerRender(EntityItemAirshipV1Wood0Magenta.class, new RenderItemAirshipV1Wood0Magenta(VCRender));
		registerRender(EntityItemAirshipV1Wood0Orange.class, new RenderItemAirshipV1Wood0Orange(VCRender));
		registerRender(EntityItemAirshipV1Wood0Pink.class, new RenderItemAirshipV1Wood0Pink(VCRender));
		registerRender(EntityItemAirshipV1Wood0Purple.class, new RenderItemAirshipV1Wood0Purple(VCRender));
		registerRender(EntityItemAirshipV1Wood0Red.class, new RenderItemAirshipV1Wood0Red(VCRender));
		registerRender(EntityItemAirshipV1Wood0White.class, new RenderItemAirshipV1Wood0White(VCRender));
		registerRender(EntityItemAirshipV1Wood0Yellow.class, new RenderItemAirshipV1Wood0Yellow(VCRender));
		registerRender(EntityItemAirshipV1Wood0Admin.class, new RenderItemAirshipV1Wood0Admin(VCRender));
		
		registerRender(EntityItemAirshipV1IronNormal.class, new RenderItemAirshipV1IronNormal(VCRender));
		registerRender(EntityItemAirshipV1IronBlack.class, new RenderItemAirshipV1IronBlack(VCRender));
		registerRender(EntityItemAirshipV1IronBlue.class, new RenderItemAirshipV1IronBlue(VCRender));
		registerRender(EntityItemAirshipV1IronBrown.class, new RenderItemAirshipV1IronBrown(VCRender));
		registerRender(EntityItemAirshipV1IronCyan.class, new RenderItemAirshipV1IronCyan(VCRender));
		registerRender(EntityItemAirshipV1IronGray.class, new RenderItemAirshipV1IronGray(VCRender));
		registerRender(EntityItemAirshipV1IronGreen.class, new RenderItemAirshipV1IronGreen(VCRender));
		registerRender(EntityItemAirshipV1IronLightBlue.class, new RenderItemAirshipV1IronLightBlue(VCRender));
		registerRender(EntityItemAirshipV1IronLightGray.class, new RenderItemAirshipV1IronLightGray(VCRender));
		registerRender(EntityItemAirshipV1IronLime.class, new RenderItemAirshipV1IronLime(VCRender));
		registerRender(EntityItemAirshipV1IronMagenta.class, new RenderItemAirshipV1IronMagenta(VCRender));
		registerRender(EntityItemAirshipV1IronOrange.class, new RenderItemAirshipV1IronOrange(VCRender));
		registerRender(EntityItemAirshipV1IronPink.class, new RenderItemAirshipV1IronPink(VCRender));
		registerRender(EntityItemAirshipV1IronPurple.class, new RenderItemAirshipV1IronPurple(VCRender));
		registerRender(EntityItemAirshipV1IronRed.class, new RenderItemAirshipV1IronRed(VCRender));
		registerRender(EntityItemAirshipV1IronWhite.class, new RenderItemAirshipV1IronWhite(VCRender));
		registerRender(EntityItemAirshipV1IronYellow.class, new RenderItemAirshipV1IronYellow(VCRender));
		registerRender(EntityItemAirshipV1IronAdmin.class, new RenderItemAirshipV1IronAdmin(VCRender));
		
		registerRender(EntityItemAirshipV1RedstoneNormal.class, new RenderItemAirshipV1RedstoneNormal(VCRender));
		registerRender(EntityItemAirshipV1RedstoneBlack.class, new RenderItemAirshipV1RedstoneBlack(VCRender));
		registerRender(EntityItemAirshipV1RedstoneBlue.class, new RenderItemAirshipV1RedstoneBlue(VCRender));
		registerRender(EntityItemAirshipV1RedstoneBrown.class, new RenderItemAirshipV1RedstoneBrown(VCRender));
		registerRender(EntityItemAirshipV1RedstoneCyan.class, new RenderItemAirshipV1RedstoneCyan(VCRender));
		registerRender(EntityItemAirshipV1RedstoneGray.class, new RenderItemAirshipV1RedstoneGray(VCRender));
		registerRender(EntityItemAirshipV1RedstoneGreen.class, new RenderItemAirshipV1RedstoneGreen(VCRender));
		registerRender(EntityItemAirshipV1RedstoneLightBlue.class, new RenderItemAirshipV1RedstoneLightBlue(VCRender));
		registerRender(EntityItemAirshipV1RedstoneLightGray.class, new RenderItemAirshipV1RedstoneLightGray(VCRender));
		registerRender(EntityItemAirshipV1RedstoneLime.class, new RenderItemAirshipV1RedstoneLime(VCRender));
		registerRender(EntityItemAirshipV1RedstoneMagenta.class, new RenderItemAirshipV1RedstoneMagenta(VCRender));
		registerRender(EntityItemAirshipV1RedstoneOrange.class, new RenderItemAirshipV1RedstoneOrange(VCRender));
		registerRender(EntityItemAirshipV1RedstonePink.class, new RenderItemAirshipV1RedstonePink(VCRender));
		registerRender(EntityItemAirshipV1RedstonePurple.class, new RenderItemAirshipV1RedstonePurple(VCRender));
		registerRender(EntityItemAirshipV1RedstoneRed.class, new RenderItemAirshipV1RedstoneRed(VCRender));
		registerRender(EntityItemAirshipV1RedstoneWhite.class, new RenderItemAirshipV1RedstoneWhite(VCRender));
		registerRender(EntityItemAirshipV1RedstoneYellow.class, new RenderItemAirshipV1RedstoneYellow(VCRender));
		registerRender(EntityItemAirshipV1RedstoneAdmin.class, new RenderItemAirshipV1RedstoneAdmin(VCRender));
		
		registerRender(EntityItemAirshipV1GoldNormal.class, new RenderItemAirshipV1GoldNormal(VCRender));
		registerRender(EntityItemAirshipV1GoldBlack.class, new RenderItemAirshipV1GoldBlack(VCRender));
		registerRender(EntityItemAirshipV1GoldBlue.class, new RenderItemAirshipV1GoldBlue(VCRender));
		registerRender(EntityItemAirshipV1GoldBrown.class, new RenderItemAirshipV1GoldBrown(VCRender));
		registerRender(EntityItemAirshipV1GoldCyan.class, new RenderItemAirshipV1GoldCyan(VCRender));
		registerRender(EntityItemAirshipV1GoldGray.class, new RenderItemAirshipV1GoldGray(VCRender));
		registerRender(EntityItemAirshipV1GoldGreen.class, new RenderItemAirshipV1GoldGreen(VCRender));
		registerRender(EntityItemAirshipV1GoldLightBlue.class, new RenderItemAirshipV1GoldLightBlue(VCRender));
		registerRender(EntityItemAirshipV1GoldLightGray.class, new RenderItemAirshipV1GoldLightGray(VCRender));
		registerRender(EntityItemAirshipV1GoldLime.class, new RenderItemAirshipV1GoldLime(VCRender));
		registerRender(EntityItemAirshipV1GoldMagenta.class, new RenderItemAirshipV1GoldMagenta(VCRender));
		registerRender(EntityItemAirshipV1GoldOrange.class, new RenderItemAirshipV1GoldOrange(VCRender));
		registerRender(EntityItemAirshipV1GoldPink.class, new RenderItemAirshipV1GoldPink(VCRender));
		registerRender(EntityItemAirshipV1GoldPurple.class, new RenderItemAirshipV1GoldPurple(VCRender));
		registerRender(EntityItemAirshipV1GoldRed.class, new RenderItemAirshipV1GoldRed(VCRender));
		registerRender(EntityItemAirshipV1GoldWhite.class, new RenderItemAirshipV1GoldWhite(VCRender));
		registerRender(EntityItemAirshipV1GoldYellow.class, new RenderItemAirshipV1GoldYellow(VCRender));
		registerRender(EntityItemAirshipV1GoldAdmin.class, new RenderItemAirshipV1GoldAdmin(VCRender));
		
		registerRender(EntityItemAirshipV1LapisLazuliNormal.class, new RenderItemAirshipV1LapisLazuliNormal(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliBlack.class, new RenderItemAirshipV1LapisLazuliBlack(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliBlue.class, new RenderItemAirshipV1LapisLazuliBlue(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliBrown.class, new RenderItemAirshipV1LapisLazuliBrown(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliCyan.class, new RenderItemAirshipV1LapisLazuliCyan(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliGray.class, new RenderItemAirshipV1LapisLazuliGray(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliGreen.class, new RenderItemAirshipV1LapisLazuliGreen(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliLightBlue.class, new RenderItemAirshipV1LapisLazuliLightBlue(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliLightGray.class, new RenderItemAirshipV1LapisLazuliLightGray(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliLime.class, new RenderItemAirshipV1LapisLazuliLime(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliMagenta.class, new RenderItemAirshipV1LapisLazuliMagenta(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliOrange.class, new RenderItemAirshipV1LapisLazuliOrange(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliPink.class, new RenderItemAirshipV1LapisLazuliPink(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliPurple.class, new RenderItemAirshipV1LapisLazuliPurple(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliRed.class, new RenderItemAirshipV1LapisLazuliRed(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliWhite.class, new RenderItemAirshipV1LapisLazuliWhite(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliYellow.class, new RenderItemAirshipV1LapisLazuliYellow(VCRender));
		registerRender(EntityItemAirshipV1LapisLazuliAdmin.class, new RenderItemAirshipV1LapisLazuliAdmin(VCRender));
		
		registerRender(EntityItemAirshipV1DiamondNormal.class, new RenderItemAirshipV1DiamondNormal(VCRender));
		registerRender(EntityItemAirshipV1DiamondBlack.class, new RenderItemAirshipV1DiamondBlack(VCRender));
		registerRender(EntityItemAirshipV1DiamondBlue.class, new RenderItemAirshipV1DiamondBlue(VCRender));
		registerRender(EntityItemAirshipV1DiamondBrown.class, new RenderItemAirshipV1DiamondBrown(VCRender));
		registerRender(EntityItemAirshipV1DiamondCyan.class, new RenderItemAirshipV1DiamondCyan(VCRender));
		registerRender(EntityItemAirshipV1DiamondGray.class, new RenderItemAirshipV1DiamondGray(VCRender));
		registerRender(EntityItemAirshipV1DiamondGreen.class, new RenderItemAirshipV1DiamondGreen(VCRender));
		registerRender(EntityItemAirshipV1DiamondLightBlue.class, new RenderItemAirshipV1DiamondLightBlue(VCRender));
		registerRender(EntityItemAirshipV1DiamondLightGray.class, new RenderItemAirshipV1DiamondLightGray(VCRender));
		registerRender(EntityItemAirshipV1DiamondLime.class, new RenderItemAirshipV1DiamondLime(VCRender));
		registerRender(EntityItemAirshipV1DiamondMagenta.class, new RenderItemAirshipV1DiamondMagenta(VCRender));
		registerRender(EntityItemAirshipV1DiamondOrange.class, new RenderItemAirshipV1DiamondOrange(VCRender));
		registerRender(EntityItemAirshipV1DiamondPink.class, new RenderItemAirshipV1DiamondPink(VCRender));
		registerRender(EntityItemAirshipV1DiamondPurple.class, new RenderItemAirshipV1DiamondPurple(VCRender));
		registerRender(EntityItemAirshipV1DiamondRed.class, new RenderItemAirshipV1DiamondRed(VCRender));
		registerRender(EntityItemAirshipV1DiamondWhite.class, new RenderItemAirshipV1DiamondWhite(VCRender));
		registerRender(EntityItemAirshipV1DiamondYellow.class, new RenderItemAirshipV1DiamondYellow(VCRender));
		registerRender(EntityItemAirshipV1DiamondAdmin.class, new RenderItemAirshipV1DiamondAdmin(VCRender));
		
		registerRender(EntityItemAirshipV1EmeraldNormal.class, new RenderItemAirshipV1EmeraldNormal(VCRender));
		registerRender(EntityItemAirshipV1EmeraldBlack.class, new RenderItemAirshipV1EmeraldBlack(VCRender));
		registerRender(EntityItemAirshipV1EmeraldBlue.class, new RenderItemAirshipV1EmeraldBlue(VCRender));
		registerRender(EntityItemAirshipV1EmeraldBrown.class, new RenderItemAirshipV1EmeraldBrown(VCRender));
		registerRender(EntityItemAirshipV1EmeraldCyan.class, new RenderItemAirshipV1EmeraldCyan(VCRender));
		registerRender(EntityItemAirshipV1EmeraldGray.class, new RenderItemAirshipV1EmeraldGray(VCRender));
		registerRender(EntityItemAirshipV1EmeraldGreen.class, new RenderItemAirshipV1EmeraldGreen(VCRender));
		registerRender(EntityItemAirshipV1EmeraldLightBlue.class, new RenderItemAirshipV1EmeraldLightBlue(VCRender));
		registerRender(EntityItemAirshipV1EmeraldLightGray.class, new RenderItemAirshipV1EmeraldLightGray(VCRender));
		registerRender(EntityItemAirshipV1EmeraldLime.class, new RenderItemAirshipV1EmeraldLime(VCRender));
		registerRender(EntityItemAirshipV1EmeraldMagenta.class, new RenderItemAirshipV1EmeraldMagenta(VCRender));
		registerRender(EntityItemAirshipV1EmeraldOrange.class, new RenderItemAirshipV1EmeraldOrange(VCRender));
		registerRender(EntityItemAirshipV1EmeraldPink.class, new RenderItemAirshipV1EmeraldPink(VCRender));
		registerRender(EntityItemAirshipV1EmeraldPurple.class, new RenderItemAirshipV1EmeraldPurple(VCRender));
		registerRender(EntityItemAirshipV1EmeraldRed.class, new RenderItemAirshipV1EmeraldRed(VCRender));
		registerRender(EntityItemAirshipV1EmeraldWhite.class, new RenderItemAirshipV1EmeraldWhite(VCRender));
		registerRender(EntityItemAirshipV1EmeraldYellow.class, new RenderItemAirshipV1EmeraldYellow(VCRender));
		registerRender(EntityItemAirshipV1EmeraldAdmin.class, new RenderItemAirshipV1EmeraldAdmin(VCRender));
		
		//===========================================================================
		
		registerRender(EntityAirshipV1Wood0Normal.class, new RenderAirshipV1Wood0Normal(VCRender));
		registerRender(EntityAirshipV1Wood0Black.class, new RenderAirshipV1Wood0Black(VCRender));
		registerRender(EntityAirshipV1Wood0Blue.class, new RenderAirshipV1Wood0Blue(VCRender));
		registerRender(EntityAirshipV1Wood0Brown.class, new RenderAirshipV1Wood0Brown(VCRender));
		registerRender(EntityAirshipV1Wood0Cyan.class, new RenderAirshipV1Wood0Cyan(VCRender));
		registerRender(EntityAirshipV1Wood0Gray.class, new RenderAirshipV1Wood0Gray(VCRender));
		registerRender(EntityAirshipV1Wood0Green.class, new RenderAirshipV1Wood0Green(VCRender));
		registerRender(EntityAirshipV1Wood0LightBlue.class, new RenderAirshipV1Wood0LightBlue(VCRender));
		registerRender(EntityAirshipV1Wood0LightGray.class, new RenderAirshipV1Wood0LightGray(VCRender));
		registerRender(EntityAirshipV1Wood0Lime.class, new RenderAirshipV1Wood0Lime(VCRender));
		registerRender(EntityAirshipV1Wood0Magenta.class, new RenderAirshipV1Wood0Magenta(VCRender));
		registerRender(EntityAirshipV1Wood0Orange.class, new RenderAirshipV1Wood0Orange(VCRender));
		registerRender(EntityAirshipV1Wood0Pink.class, new RenderAirshipV1Wood0Pink(VCRender));
		registerRender(EntityAirshipV1Wood0Purple.class, new RenderAirshipV1Wood0Purple(VCRender));
		registerRender(EntityAirshipV1Wood0Red.class, new RenderAirshipV1Wood0Red(VCRender));
		registerRender(EntityAirshipV1Wood0White.class, new RenderAirshipV1Wood0White(VCRender));
		registerRender(EntityAirshipV1Wood0Yellow.class, new RenderAirshipV1Wood0Yellow(VCRender));
		registerRender(EntityAirshipV1Wood0Admin.class, new RenderAirshipV1Wood0Admin(VCRender));
		
		registerRender(EntityAirshipV1IronNormal.class, new RenderAirshipV1IronNormal(VCRender));
		registerRender(EntityAirshipV1IronBlack.class, new RenderAirshipV1IronBlack(VCRender));
		registerRender(EntityAirshipV1IronBlue.class, new RenderAirshipV1IronBlue(VCRender));
		registerRender(EntityAirshipV1IronBrown.class, new RenderAirshipV1IronBrown(VCRender));
		registerRender(EntityAirshipV1IronCyan.class, new RenderAirshipV1IronCyan(VCRender));
		registerRender(EntityAirshipV1IronGray.class, new RenderAirshipV1IronGray(VCRender));
		registerRender(EntityAirshipV1IronGreen.class, new RenderAirshipV1IronGreen(VCRender));
		registerRender(EntityAirshipV1IronLightBlue.class, new RenderAirshipV1IronLightBlue(VCRender));
		registerRender(EntityAirshipV1IronLightGray.class, new RenderAirshipV1IronLightGray(VCRender));
		registerRender(EntityAirshipV1IronLime.class, new RenderAirshipV1IronLime(VCRender));
		registerRender(EntityAirshipV1IronMagenta.class, new RenderAirshipV1IronMagenta(VCRender));
		registerRender(EntityAirshipV1IronOrange.class, new RenderAirshipV1IronOrange(VCRender));
		registerRender(EntityAirshipV1IronPink.class, new RenderAirshipV1IronPink(VCRender));
		registerRender(EntityAirshipV1IronPurple.class, new RenderAirshipV1IronPurple(VCRender));
		registerRender(EntityAirshipV1IronRed.class, new RenderAirshipV1IronRed(VCRender));
		registerRender(EntityAirshipV1IronWhite.class, new RenderAirshipV1IronWhite(VCRender));
		registerRender(EntityAirshipV1IronYellow.class, new RenderAirshipV1IronYellow(VCRender));
		registerRender(EntityAirshipV1IronAdmin.class, new RenderAirshipV1IronAdmin(VCRender));
		
		registerRender(EntityAirshipV1RedstoneNormal.class, new RenderAirshipV1RedstoneNormal(VCRender));
		registerRender(EntityAirshipV1RedstoneBlack.class, new RenderAirshipV1RedstoneBlack(VCRender));
		registerRender(EntityAirshipV1RedstoneBlue.class, new RenderAirshipV1RedstoneBlue(VCRender));
		registerRender(EntityAirshipV1RedstoneBrown.class, new RenderAirshipV1RedstoneBrown(VCRender));
		registerRender(EntityAirshipV1RedstoneCyan.class, new RenderAirshipV1RedstoneCyan(VCRender));
		registerRender(EntityAirshipV1RedstoneGray.class, new RenderAirshipV1RedstoneGray(VCRender));
		registerRender(EntityAirshipV1RedstoneGreen.class, new RenderAirshipV1RedstoneGreen(VCRender));
		registerRender(EntityAirshipV1RedstoneLightBlue.class, new RenderAirshipV1RedstoneLightBlue(VCRender));
		registerRender(EntityAirshipV1RedstoneLightGray.class, new RenderAirshipV1RedstoneLightGray(VCRender));
		registerRender(EntityAirshipV1RedstoneLime.class, new RenderAirshipV1RedstoneLime(VCRender));
		registerRender(EntityAirshipV1RedstoneMagenta.class, new RenderAirshipV1RedstoneMagenta(VCRender));
		registerRender(EntityAirshipV1RedstoneOrange.class, new RenderAirshipV1RedstoneOrange(VCRender));
		registerRender(EntityAirshipV1RedstonePink.class, new RenderAirshipV1RedstonePink(VCRender));
		registerRender(EntityAirshipV1RedstonePurple.class, new RenderAirshipV1RedstonePurple(VCRender));
		registerRender(EntityAirshipV1RedstoneRed.class, new RenderAirshipV1RedstoneRed(VCRender));
		registerRender(EntityAirshipV1RedstoneWhite.class, new RenderAirshipV1RedstoneWhite(VCRender));
		registerRender(EntityAirshipV1RedstoneYellow.class, new RenderAirshipV1RedstoneYellow(VCRender));
		registerRender(EntityAirshipV1RedstoneAdmin.class, new RenderAirshipV1RedstoneAdmin(VCRender));
		
		registerRender(EntityAirshipV1GoldNormal.class, new RenderAirshipV1GoldNormal(VCRender));
		registerRender(EntityAirshipV1GoldBlack.class, new RenderAirshipV1GoldBlack(VCRender));
		registerRender(EntityAirshipV1GoldBlue.class, new RenderAirshipV1GoldBlue(VCRender));
		registerRender(EntityAirshipV1GoldBrown.class, new RenderAirshipV1GoldBrown(VCRender));
		registerRender(EntityAirshipV1GoldCyan.class, new RenderAirshipV1GoldCyan(VCRender));
		registerRender(EntityAirshipV1GoldGray.class, new RenderAirshipV1GoldGray(VCRender));
		registerRender(EntityAirshipV1GoldGreen.class, new RenderAirshipV1GoldGreen(VCRender));
		registerRender(EntityAirshipV1GoldLightBlue.class, new RenderAirshipV1GoldLightBlue(VCRender));
		registerRender(EntityAirshipV1GoldLightGray.class, new RenderAirshipV1GoldLightGray(VCRender));
		registerRender(EntityAirshipV1GoldLime.class, new RenderAirshipV1GoldLime(VCRender));
		registerRender(EntityAirshipV1GoldMagenta.class, new RenderAirshipV1GoldMagenta(VCRender));
		registerRender(EntityAirshipV1GoldOrange.class, new RenderAirshipV1GoldOrange(VCRender));
		registerRender(EntityAirshipV1GoldPink.class, new RenderAirshipV1GoldPink(VCRender));
		registerRender(EntityAirshipV1GoldPurple.class, new RenderAirshipV1GoldPurple(VCRender));
		registerRender(EntityAirshipV1GoldRed.class, new RenderAirshipV1GoldRed(VCRender));
		registerRender(EntityAirshipV1GoldWhite.class, new RenderAirshipV1GoldWhite(VCRender));
		registerRender(EntityAirshipV1GoldYellow.class, new RenderAirshipV1GoldYellow(VCRender));
		registerRender(EntityAirshipV1GoldAdmin.class, new RenderAirshipV1GoldAdmin(VCRender));
		
		registerRender(EntityAirshipV1LapisLazuliNormal.class, new RenderAirshipV1LapisLazuliNormal(VCRender));
		registerRender(EntityAirshipV1LapisLazuliBlack.class, new RenderAirshipV1LapisLazuliBlack(VCRender));
		registerRender(EntityAirshipV1LapisLazuliBlue.class, new RenderAirshipV1LapisLazuliBlue(VCRender));
		registerRender(EntityAirshipV1LapisLazuliBrown.class, new RenderAirshipV1LapisLazuliBrown(VCRender));
		registerRender(EntityAirshipV1LapisLazuliCyan.class, new RenderAirshipV1LapisLazuliCyan(VCRender));
		registerRender(EntityAirshipV1LapisLazuliGray.class, new RenderAirshipV1LapisLazuliGray(VCRender));
		registerRender(EntityAirshipV1LapisLazuliGreen.class, new RenderAirshipV1LapisLazuliGreen(VCRender));
		registerRender(EntityAirshipV1LapisLazuliLightBlue.class, new RenderAirshipV1LapisLazuliLightBlue(VCRender));
		registerRender(EntityAirshipV1LapisLazuliLightGray.class, new RenderAirshipV1LapisLazuliLightGray(VCRender));
		registerRender(EntityAirshipV1LapisLazuliLime.class, new RenderAirshipV1LapisLazuliLime(VCRender));
		registerRender(EntityAirshipV1LapisLazuliMagenta.class, new RenderAirshipV1LapisLazuliMagenta(VCRender));
		registerRender(EntityAirshipV1LapisLazuliOrange.class, new RenderAirshipV1LapisLazuliOrange(VCRender));
		registerRender(EntityAirshipV1LapisLazuliPink.class, new RenderAirshipV1LapisLazuliPink(VCRender));
		registerRender(EntityAirshipV1LapisLazuliPurple.class, new RenderAirshipV1LapisLazuliPurple(VCRender));
		registerRender(EntityAirshipV1LapisLazuliRed.class, new RenderAirshipV1LapisLazuliRed(VCRender));
		registerRender(EntityAirshipV1LapisLazuliWhite.class, new RenderAirshipV1LapisLazuliWhite(VCRender));
		registerRender(EntityAirshipV1LapisLazuliYellow.class, new RenderAirshipV1LapisLazuliYellow(VCRender));
		registerRender(EntityAirshipV1LapisLazuliAdmin.class, new RenderAirshipV1LapisLazuliAdmin(VCRender));
		
		registerRender(EntityAirshipV1DiamondNormal.class, new RenderAirshipV1DiamondNormal(VCRender));
		registerRender(EntityAirshipV1DiamondBlack.class, new RenderAirshipV1DiamondBlack(VCRender));
		registerRender(EntityAirshipV1DiamondBlue.class, new RenderAirshipV1DiamondBlue(VCRender));
		registerRender(EntityAirshipV1DiamondBrown.class, new RenderAirshipV1DiamondBrown(VCRender));
		registerRender(EntityAirshipV1DiamondCyan.class, new RenderAirshipV1DiamondCyan(VCRender));
		registerRender(EntityAirshipV1DiamondGray.class, new RenderAirshipV1DiamondGray(VCRender));
		registerRender(EntityAirshipV1DiamondGreen.class, new RenderAirshipV1DiamondGreen(VCRender));
		registerRender(EntityAirshipV1DiamondLightBlue.class, new RenderAirshipV1DiamondLightBlue(VCRender));
		registerRender(EntityAirshipV1DiamondLightGray.class, new RenderAirshipV1DiamondLightGray(VCRender));
		registerRender(EntityAirshipV1DiamondLime.class, new RenderAirshipV1DiamondLime(VCRender));
		registerRender(EntityAirshipV1DiamondMagenta.class, new RenderAirshipV1DiamondMagenta(VCRender));
		registerRender(EntityAirshipV1DiamondOrange.class, new RenderAirshipV1DiamondOrange(VCRender));
		registerRender(EntityAirshipV1DiamondPink.class, new RenderAirshipV1DiamondPink(VCRender));
		registerRender(EntityAirshipV1DiamondPurple.class, new RenderAirshipV1DiamondPurple(VCRender));
		registerRender(EntityAirshipV1DiamondRed.class, new RenderAirshipV1DiamondRed(VCRender));
		registerRender(EntityAirshipV1DiamondWhite.class, new RenderAirshipV1DiamondWhite(VCRender));
		registerRender(EntityAirshipV1DiamondYellow.class, new RenderAirshipV1DiamondYellow(VCRender));
		registerRender(EntityAirshipV1DiamondAdmin.class, new RenderAirshipV1DiamondAdmin(VCRender));
		
		registerRender(EntityAirshipV1EmeraldNormal.class, new RenderAirshipV1EmeraldNormal(VCRender));
		registerRender(EntityAirshipV1EmeraldBlack.class, new RenderAirshipV1EmeraldBlack(VCRender));
		registerRender(EntityAirshipV1EmeraldBlue.class, new RenderAirshipV1EmeraldBlue(VCRender));
		registerRender(EntityAirshipV1EmeraldBrown.class, new RenderAirshipV1EmeraldBrown(VCRender));
		registerRender(EntityAirshipV1EmeraldCyan.class, new RenderAirshipV1EmeraldCyan(VCRender));
		registerRender(EntityAirshipV1EmeraldGray.class, new RenderAirshipV1EmeraldGray(VCRender));
		registerRender(EntityAirshipV1EmeraldGreen.class, new RenderAirshipV1EmeraldGreen(VCRender));
		registerRender(EntityAirshipV1EmeraldLightBlue.class, new RenderAirshipV1EmeraldLightBlue(VCRender));
		registerRender(EntityAirshipV1EmeraldLightGray.class, new RenderAirshipV1EmeraldLightGray(VCRender));
		registerRender(EntityAirshipV1EmeraldLime.class, new RenderAirshipV1EmeraldLime(VCRender));
		registerRender(EntityAirshipV1EmeraldMagenta.class, new RenderAirshipV1EmeraldMagenta(VCRender));
		registerRender(EntityAirshipV1EmeraldOrange.class, new RenderAirshipV1EmeraldOrange(VCRender));
		registerRender(EntityAirshipV1EmeraldPink.class, new RenderAirshipV1EmeraldPink(VCRender));
		registerRender(EntityAirshipV1EmeraldPurple.class, new RenderAirshipV1EmeraldPurple(VCRender));
		registerRender(EntityAirshipV1EmeraldRed.class, new RenderAirshipV1EmeraldRed(VCRender));
		registerRender(EntityAirshipV1EmeraldWhite.class, new RenderAirshipV1EmeraldWhite(VCRender));
		registerRender(EntityAirshipV1EmeraldYellow.class, new RenderAirshipV1EmeraldYellow(VCRender));
		registerRender(EntityAirshipV1EmeraldAdmin.class, new RenderAirshipV1EmeraldAdmin(VCRender));
	}
	
	public static void registerRender(Class<? extends Entity> classIn, Render<? extends Entity> renderItem)
	{
		RenderingRegistry.registerEntityRenderingHandler(classIn, renderItem);
	}
}
