package com.viesis.viescraft.init;

import java.util.HashSet;
import java.util.Set;

import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.GameRegistry;

import com.viesis.viescraft.api.ItemsVC;
import com.viesis.viescraft.common.entity.airshipcolors.EntityAirshipV1Core;
import com.viesis.viescraft.common.items.ItemAirshipDismounter;
import com.viesis.viescraft.common.items.ItemGuidebookControls;
import com.viesis.viescraft.common.items.ItemGuidebookMain;
import com.viesis.viescraft.common.items.ItemGuidebookPaint;
import com.viesis.viescraft.common.items.ItemGuidebookSocket;
import com.viesis.viescraft.common.items.achievements.ItemAchievementAirborn;
import com.viesis.viescraft.common.items.achievements.ItemAchievementCreate;
import com.viesis.viescraft.common.items.achievements.ItemAchievementCreateColor;
import com.viesis.viescraft.common.items.achievements.ItemAchievementCreateModule;
import com.viesis.viescraft.common.items.achievements.ItemAchievementEngine;
import com.viesis.viescraft.common.items.achievements.ItemAchievementIgnition;
import com.viesis.viescraft.common.items.achievements.ItemAchievementLava;
import com.viesis.viescraft.common.items.achievements.ItemAchievementWater;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Admin;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Black;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Blue;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Brown;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Cyan;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Gray;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Green;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1LightBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1LightGray;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Lime;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Magenta;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Normal;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Orange;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Pink;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Purple;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Red;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1White;
import com.viesis.viescraft.common.items.airshipitems.v1.ItemAirshipV1Yellow;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondAdmin;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondBlack;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondBrown;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondCyan;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondGray;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondGreen;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondLightBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondLightGray;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondLime;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondMagenta;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondNormal;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondOrange;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondPink;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondPurple;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondRed;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondWhite;
import com.viesis.viescraft.common.items.airshipitems.v1.diamond.ItemAirshipV1DiamondYellow;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldAdmin;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldBlack;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldBrown;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldCyan;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldGray;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldGreen;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldLightBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldLightGray;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldLime;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldMagenta;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldNormal;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldOrange;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldPink;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldPurple;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldRed;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldWhite;
import com.viesis.viescraft.common.items.airshipitems.v1.emerald.ItemAirshipV1EmeraldYellow;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldAdmin;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldBlack;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldBrown;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldCyan;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldGray;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldGreen;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldLightBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldLightGray;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldLime;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldMagenta;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldNormal;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldOrange;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldPink;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldPurple;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldRed;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldWhite;
import com.viesis.viescraft.common.items.airshipitems.v1.gold.ItemAirshipV1GoldYellow;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronAdmin;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronBlack;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronBrown;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronCyan;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronGray;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronGreen;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronLightBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronLightGray;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronLime;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronMagenta;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronNormal;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronOrange;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronPink;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronPurple;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronRed;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronWhite;
import com.viesis.viescraft.common.items.airshipitems.v1.iron.ItemAirshipV1IronYellow;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliAdmin;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliBlack;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliBrown;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliCyan;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliGray;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliGreen;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliLightBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliLightGray;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliLime;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliMagenta;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliNormal;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliOrange;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliPink;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliPurple;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliRed;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliWhite;
import com.viesis.viescraft.common.items.airshipitems.v1.lapislazuli.ItemAirshipV1LapisLazuliYellow;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneAdmin;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneBlack;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneBrown;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneCyan;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneGray;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneGreen;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneLightBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneLightGray;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneLime;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneMagenta;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneNormal;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneOrange;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstonePink;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstonePurple;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneRed;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneWhite;
import com.viesis.viescraft.common.items.airshipitems.v1.redstone.ItemAirshipV1RedstoneYellow;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Admin;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Black;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Blue;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Brown;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Cyan;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Gray;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Green;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0LightBlue;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0LightGray;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Lime;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Magenta;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Normal;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Orange;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Pink;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Purple;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Red;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0White;
import com.viesis.viescraft.common.items.airshipitems.v1.wood0.ItemAirshipV1Wood0Yellow;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Admin;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Black;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Blue;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Brown;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Cyan;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Gray;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Green;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2LightBlue;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2LightGray;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Lime;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Magenta;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Normal;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Orange;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Pink;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Purple;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Red;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2White;
import com.viesis.viescraft.common.items.airshipitems.v2.ItemAirshipV2Yellow;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Admin;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Black;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Blue;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Brown;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Cyan;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Gray;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Green;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3LightBlue;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3LightGray;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Lime;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Magenta;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Normal;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Orange;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Pink;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Purple;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Red;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3White;
import com.viesis.viescraft.common.items.airshipitems.v3.ItemAirshipV3Yellow;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Admin;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Black;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Blue;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Brown;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Cyan;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Gray;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Green;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4LightBlue;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4LightGray;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Lime;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Magenta;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Normal;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Orange;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Pink;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Purple;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Red;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4White;
import com.viesis.viescraft.common.items.airshipitems.v4.ItemAirshipV4Yellow;
import com.viesis.viescraft.common.items.modules.ItemFuelModuleInfinite;
import com.viesis.viescraft.common.items.modules.ItemInventoryModuleLarge;
import com.viesis.viescraft.common.items.modules.ItemInventoryModuleSmall;
import com.viesis.viescraft.common.items.modules.ItemModuleChip;
import com.viesis.viescraft.common.items.modules.ItemSpeedModuleMajor;
import com.viesis.viescraft.common.items.modules.ItemSpeedModuleMinor;
import com.viesis.viescraft.common.items.parts.ItemBalloon;
import com.viesis.viescraft.common.items.parts.ItemEngine;
import com.viesis.viescraft.common.items.parts.ItemFrameDiamond;
import com.viesis.viescraft.common.items.parts.ItemFrameEmerald;
import com.viesis.viescraft.common.items.parts.ItemFrameGold;
import com.viesis.viescraft.common.items.parts.ItemFrameIron;
import com.viesis.viescraft.common.items.parts.ItemFrameLapisLazuli;
import com.viesis.viescraft.common.items.parts.ItemFrameRedstone;
import com.viesis.viescraft.common.items.parts.ItemFrameWood0;
import com.viesis.viescraft.common.items.parts.ItemIgnition;
import com.viesis.viescraft.common.items.parts.ItemPaint;

public class InitItemsVC extends ItemsVC {
	
	public static final Set<Item> items = new HashSet<>();
	
	public static void preInit()
	{
		guidebook_main = registerItem(new ItemGuidebookMain());
		guidebook_controls = registerItem(new ItemGuidebookControls());
		guidebook_paint = registerItem(new ItemGuidebookPaint());
		guidebook_socket = registerItem(new ItemGuidebookSocket());
		
		airship_balloon = registerItem(new ItemBalloon());
		airship_engine = registerItem(new ItemEngine());
		airship_ignition = registerItem(new ItemIgnition());
		
		airship_frame_wood0 = registerItem(new ItemFrameWood0());
		airship_frame_iron = registerItem(new ItemFrameIron());
		airship_frame_redstone = registerItem(new ItemFrameRedstone());
		airship_frame_gold = registerItem(new ItemFrameGold());
		airship_frame_lapislazuli = registerItem(new ItemFrameLapisLazuli());
		airship_frame_diamond = registerItem(new ItemFrameDiamond());
		airship_frame_emerald = registerItem(new ItemFrameEmerald());
		
		airship_dismounter = registerItem(new ItemAirshipDismounter());
		
		module_chip = registerItem(new ItemModuleChip());
		module_inventory_small = registerItem(new ItemInventoryModuleSmall());
		module_inventory_large = registerItem(new ItemInventoryModuleLarge());
		module_speed_increase_minor = registerItem(new ItemSpeedModuleMinor());
		module_speed_increase_major = registerItem(new ItemSpeedModuleMajor());
		module_fuel_infinite = registerItem(new ItemFuelModuleInfinite());
		
		//module_stealth = registerItem(new ItemModuleStealth());
		//module_dash = registerItem(new ItemModuleDash());
		
		item_airship_v1_wood0_normal = registerItem(new ItemAirshipV1Wood0Normal());
		item_airship_v1_wood0_black = registerItem(new ItemAirshipV1Wood0Black());
		item_airship_v1_wood0_blue = registerItem(new ItemAirshipV1Wood0Blue());
		item_airship_v1_wood0_brown = registerItem(new ItemAirshipV1Wood0Brown());
		item_airship_v1_wood0_cyan = registerItem(new ItemAirshipV1Wood0Cyan());
		item_airship_v1_wood0_gray = registerItem(new ItemAirshipV1Wood0Gray());
		item_airship_v1_wood0_green = registerItem(new ItemAirshipV1Wood0Green());
		item_airship_v1_wood0_lightblue = registerItem(new ItemAirshipV1Wood0LightBlue());
		item_airship_v1_wood0_lightgray = registerItem(new ItemAirshipV1Wood0LightGray());
		item_airship_v1_wood0_lime = registerItem(new ItemAirshipV1Wood0Lime());
		item_airship_v1_wood0_magenta = registerItem(new ItemAirshipV1Wood0Magenta());
		item_airship_v1_wood0_orange = registerItem(new ItemAirshipV1Wood0Orange());
		item_airship_v1_wood0_pink = registerItem(new ItemAirshipV1Wood0Pink());
		item_airship_v1_wood0_purple = registerItem(new ItemAirshipV1Wood0Purple());
		item_airship_v1_wood0_red = registerItem(new ItemAirshipV1Wood0Red());
		item_airship_v1_wood0_white = registerItem(new ItemAirshipV1Wood0White());
		item_airship_v1_wood0_yellow = registerItem(new ItemAirshipV1Wood0Yellow());
		item_airship_v1_wood0_admin = registerItem(new ItemAirshipV1Wood0Admin());
		
		item_airship_v1_iron_normal = registerItem(new ItemAirshipV1IronNormal());
		item_airship_v1_iron_black = registerItem(new ItemAirshipV1IronBlack());
		item_airship_v1_iron_blue = registerItem(new ItemAirshipV1IronBlue());
		item_airship_v1_iron_brown = registerItem(new ItemAirshipV1IronBrown());
		item_airship_v1_iron_cyan = registerItem(new ItemAirshipV1IronCyan());
		item_airship_v1_iron_gray = registerItem(new ItemAirshipV1IronGray());
		item_airship_v1_iron_green = registerItem(new ItemAirshipV1IronGreen());
		item_airship_v1_iron_lightblue = registerItem(new ItemAirshipV1IronLightBlue());
		item_airship_v1_iron_lightgray = registerItem(new ItemAirshipV1IronLightGray());
		item_airship_v1_iron_lime = registerItem(new ItemAirshipV1IronLime());
		item_airship_v1_iron_magenta = registerItem(new ItemAirshipV1IronMagenta());
		item_airship_v1_iron_orange = registerItem(new ItemAirshipV1IronOrange());
		item_airship_v1_iron_pink = registerItem(new ItemAirshipV1IronPink());
		item_airship_v1_iron_purple = registerItem(new ItemAirshipV1IronPurple());
		item_airship_v1_iron_red = registerItem(new ItemAirshipV1IronRed());
		item_airship_v1_iron_white = registerItem(new ItemAirshipV1IronWhite());
		item_airship_v1_iron_yellow = registerItem(new ItemAirshipV1IronYellow());
		item_airship_v1_iron_admin = registerItem(new ItemAirshipV1IronAdmin());
		
		item_airship_v1_redstone_normal = registerItem(new ItemAirshipV1RedstoneNormal());
		item_airship_v1_redstone_black = registerItem(new ItemAirshipV1RedstoneBlack());
		item_airship_v1_redstone_blue = registerItem(new ItemAirshipV1RedstoneBlue());
		item_airship_v1_redstone_brown = registerItem(new ItemAirshipV1RedstoneBrown());
		item_airship_v1_redstone_cyan = registerItem(new ItemAirshipV1RedstoneCyan());
		item_airship_v1_redstone_gray = registerItem(new ItemAirshipV1RedstoneGray());
		item_airship_v1_redstone_green = registerItem(new ItemAirshipV1RedstoneGreen());
		item_airship_v1_redstone_lightblue = registerItem(new ItemAirshipV1RedstoneLightBlue());
		item_airship_v1_redstone_lightgray = registerItem(new ItemAirshipV1RedstoneLightGray());
		item_airship_v1_redstone_lime = registerItem(new ItemAirshipV1RedstoneLime());
		item_airship_v1_redstone_magenta = registerItem(new ItemAirshipV1RedstoneMagenta());
		item_airship_v1_redstone_orange = registerItem(new ItemAirshipV1RedstoneOrange());
		item_airship_v1_redstone_pink = registerItem(new ItemAirshipV1RedstonePink());
		item_airship_v1_redstone_purple = registerItem(new ItemAirshipV1RedstonePurple());
		item_airship_v1_redstone_red = registerItem(new ItemAirshipV1RedstoneRed());
		item_airship_v1_redstone_white = registerItem(new ItemAirshipV1RedstoneWhite());
		item_airship_v1_redstone_yellow = registerItem(new ItemAirshipV1RedstoneYellow());
		item_airship_v1_redstone_admin = registerItem(new ItemAirshipV1RedstoneAdmin());
		
		item_airship_v1_gold_normal = registerItem(new ItemAirshipV1GoldNormal());
		item_airship_v1_gold_black = registerItem(new ItemAirshipV1GoldBlack());
		item_airship_v1_gold_blue = registerItem(new ItemAirshipV1GoldBlue());
		item_airship_v1_gold_brown = registerItem(new ItemAirshipV1GoldBrown());
		item_airship_v1_gold_cyan = registerItem(new ItemAirshipV1GoldCyan());
		item_airship_v1_gold_gray = registerItem(new ItemAirshipV1GoldGray());
		item_airship_v1_gold_green = registerItem(new ItemAirshipV1GoldGreen());
		item_airship_v1_gold_lightblue = registerItem(new ItemAirshipV1GoldLightBlue());
		item_airship_v1_gold_lightgray = registerItem(new ItemAirshipV1GoldLightGray());
		item_airship_v1_gold_lime = registerItem(new ItemAirshipV1GoldLime());
		item_airship_v1_gold_magenta = registerItem(new ItemAirshipV1GoldMagenta());
		item_airship_v1_gold_orange = registerItem(new ItemAirshipV1GoldOrange());
		item_airship_v1_gold_pink = registerItem(new ItemAirshipV1GoldPink());
		item_airship_v1_gold_purple = registerItem(new ItemAirshipV1GoldPurple());
		item_airship_v1_gold_red = registerItem(new ItemAirshipV1GoldRed());
		item_airship_v1_gold_white = registerItem(new ItemAirshipV1GoldWhite());
		item_airship_v1_gold_yellow = registerItem(new ItemAirshipV1GoldYellow());
		item_airship_v1_gold_admin = registerItem(new ItemAirshipV1GoldAdmin());
		
		item_airship_v1_lapislazuli_normal = registerItem(new ItemAirshipV1LapisLazuliNormal());
		item_airship_v1_lapislazuli_black = registerItem(new ItemAirshipV1LapisLazuliBlack());
		item_airship_v1_lapislazuli_blue = registerItem(new ItemAirshipV1LapisLazuliBlue());
		item_airship_v1_lapislazuli_brown = registerItem(new ItemAirshipV1LapisLazuliBrown());
		item_airship_v1_lapislazuli_cyan = registerItem(new ItemAirshipV1LapisLazuliCyan());
		item_airship_v1_lapislazuli_gray = registerItem(new ItemAirshipV1LapisLazuliGray());
		item_airship_v1_lapislazuli_green = registerItem(new ItemAirshipV1LapisLazuliGreen());
		item_airship_v1_lapislazuli_lightblue = registerItem(new ItemAirshipV1LapisLazuliLightBlue());
		item_airship_v1_lapislazuli_lightgray = registerItem(new ItemAirshipV1LapisLazuliLightGray());
		item_airship_v1_lapislazuli_lime = registerItem(new ItemAirshipV1LapisLazuliLime());
		item_airship_v1_lapislazuli_magenta = registerItem(new ItemAirshipV1LapisLazuliMagenta());
		item_airship_v1_lapislazuli_orange = registerItem(new ItemAirshipV1LapisLazuliOrange());
		item_airship_v1_lapislazuli_pink = registerItem(new ItemAirshipV1LapisLazuliPink());
		item_airship_v1_lapislazuli_purple = registerItem(new ItemAirshipV1LapisLazuliPurple());
		item_airship_v1_lapislazuli_red = registerItem(new ItemAirshipV1LapisLazuliRed());
		item_airship_v1_lapislazuli_white = registerItem(new ItemAirshipV1LapisLazuliWhite());
		item_airship_v1_lapislazuli_yellow = registerItem(new ItemAirshipV1LapisLazuliYellow());
		item_airship_v1_lapislazuli_admin = registerItem(new ItemAirshipV1LapisLazuliAdmin());
		
		item_airship_v1_diamond_normal = registerItem(new ItemAirshipV1DiamondNormal());
		item_airship_v1_diamond_black = registerItem(new ItemAirshipV1DiamondBlack());
		item_airship_v1_diamond_blue = registerItem(new ItemAirshipV1DiamondBlue());
		item_airship_v1_diamond_brown = registerItem(new ItemAirshipV1DiamondBrown());
		item_airship_v1_diamond_cyan = registerItem(new ItemAirshipV1DiamondCyan());
		item_airship_v1_diamond_gray = registerItem(new ItemAirshipV1DiamondGray());
		item_airship_v1_diamond_green = registerItem(new ItemAirshipV1DiamondGreen());
		item_airship_v1_diamond_lightblue = registerItem(new ItemAirshipV1DiamondLightBlue());
		item_airship_v1_diamond_lightgray = registerItem(new ItemAirshipV1DiamondLightGray());
		item_airship_v1_diamond_lime = registerItem(new ItemAirshipV1DiamondLime());
		item_airship_v1_diamond_magenta = registerItem(new ItemAirshipV1DiamondMagenta());
		item_airship_v1_diamond_orange = registerItem(new ItemAirshipV1DiamondOrange());
		item_airship_v1_diamond_pink = registerItem(new ItemAirshipV1DiamondPink());
		item_airship_v1_diamond_purple = registerItem(new ItemAirshipV1DiamondPurple());
		item_airship_v1_diamond_red = registerItem(new ItemAirshipV1DiamondRed());
		item_airship_v1_diamond_white = registerItem(new ItemAirshipV1DiamondWhite());
		item_airship_v1_diamond_yellow = registerItem(new ItemAirshipV1DiamondYellow());
		item_airship_v1_diamond_admin = registerItem(new ItemAirshipV1DiamondAdmin());
		
		item_airship_v1_emerald_normal = registerItem(new ItemAirshipV1EmeraldNormal());
		item_airship_v1_emerald_black = registerItem(new ItemAirshipV1EmeraldBlack());
		item_airship_v1_emerald_blue = registerItem(new ItemAirshipV1EmeraldBlue());
		item_airship_v1_emerald_brown = registerItem(new ItemAirshipV1EmeraldBrown());
		item_airship_v1_emerald_cyan = registerItem(new ItemAirshipV1EmeraldCyan());
		item_airship_v1_emerald_gray = registerItem(new ItemAirshipV1EmeraldGray());
		item_airship_v1_emerald_green = registerItem(new ItemAirshipV1EmeraldGreen());
		item_airship_v1_emerald_lightblue = registerItem(new ItemAirshipV1EmeraldLightBlue());
		item_airship_v1_emerald_lightgray = registerItem(new ItemAirshipV1EmeraldLightGray());
		item_airship_v1_emerald_lime = registerItem(new ItemAirshipV1EmeraldLime());
		item_airship_v1_emerald_magenta = registerItem(new ItemAirshipV1EmeraldMagenta());
		item_airship_v1_emerald_orange = registerItem(new ItemAirshipV1EmeraldOrange());
		item_airship_v1_emerald_pink = registerItem(new ItemAirshipV1EmeraldPink());
		item_airship_v1_emerald_purple = registerItem(new ItemAirshipV1EmeraldPurple());
		item_airship_v1_emerald_red = registerItem(new ItemAirshipV1EmeraldRed());
		item_airship_v1_emerald_white = registerItem(new ItemAirshipV1EmeraldWhite());
		item_airship_v1_emerald_yellow = registerItem(new ItemAirshipV1EmeraldYellow());
		item_airship_v1_emerald_admin = registerItem(new ItemAirshipV1EmeraldAdmin());
		
		
		
		
		
		item_airship_v1_normal = registerItem(new ItemAirshipV1Normal());
		item_airship_v1_black = registerItem(new ItemAirshipV1Black());
		item_airship_v1_blue = registerItem(new ItemAirshipV1Blue());
		item_airship_v1_brown = registerItem(new ItemAirshipV1Brown());
		item_airship_v1_cyan = registerItem(new ItemAirshipV1Cyan());
		item_airship_v1_gray = registerItem(new ItemAirshipV1Gray());
		item_airship_v1_green = registerItem(new ItemAirshipV1Green());
		item_airship_v1_lightblue = registerItem(new ItemAirshipV1LightBlue());
		item_airship_v1_lightgray = registerItem(new ItemAirshipV1LightGray());
		item_airship_v1_lime = registerItem(new ItemAirshipV1Lime());
		item_airship_v1_magenta = registerItem(new ItemAirshipV1Magenta());
		item_airship_v1_orange = registerItem(new ItemAirshipV1Orange());
		item_airship_v1_pink = registerItem(new ItemAirshipV1Pink());
		item_airship_v1_purple = registerItem(new ItemAirshipV1Purple());
		item_airship_v1_red = registerItem(new ItemAirshipV1Red());
		item_airship_v1_white = registerItem(new ItemAirshipV1White());
		item_airship_v1_yellow = registerItem(new ItemAirshipV1Yellow());
		item_airship_v1_admin = registerItem(new ItemAirshipV1Admin());
		
		item_airship_v2_normal = registerItem(new ItemAirshipV2Normal());
		item_airship_v2_black = registerItem(new ItemAirshipV2Black());
		item_airship_v2_blue = registerItem(new ItemAirshipV2Blue());
		item_airship_v2_brown = registerItem(new ItemAirshipV2Brown());
		item_airship_v2_cyan = registerItem(new ItemAirshipV2Cyan());
		item_airship_v2_gray = registerItem(new ItemAirshipV2Gray());
		item_airship_v2_green = registerItem(new ItemAirshipV2Green());
		item_airship_v2_lightblue = registerItem(new ItemAirshipV2LightBlue());
		item_airship_v2_lightgray = registerItem(new ItemAirshipV2LightGray());
		item_airship_v2_lime = registerItem(new ItemAirshipV2Lime());
		item_airship_v2_magenta = registerItem(new ItemAirshipV2Magenta());
		item_airship_v2_orange = registerItem(new ItemAirshipV2Orange());
		item_airship_v2_pink = registerItem(new ItemAirshipV2Pink());
		item_airship_v2_purple = registerItem(new ItemAirshipV2Purple());
		item_airship_v2_red = registerItem(new ItemAirshipV2Red());
		item_airship_v2_white = registerItem(new ItemAirshipV2White());
		item_airship_v2_yellow = registerItem(new ItemAirshipV2Yellow());
		item_airship_v2_admin = registerItem(new ItemAirshipV2Admin());
		
		item_airship_v3_normal = registerItem(new ItemAirshipV3Normal());
		item_airship_v3_black = registerItem(new ItemAirshipV3Black());
		item_airship_v3_blue = registerItem(new ItemAirshipV3Blue());
		item_airship_v3_brown = registerItem(new ItemAirshipV3Brown());
		item_airship_v3_cyan = registerItem(new ItemAirshipV3Cyan());
		item_airship_v3_gray = registerItem(new ItemAirshipV3Gray());
		item_airship_v3_green = registerItem(new ItemAirshipV3Green());
		item_airship_v3_lightblue = registerItem(new ItemAirshipV3LightBlue());
		item_airship_v3_lightgray = registerItem(new ItemAirshipV3LightGray());
		item_airship_v3_lime = registerItem(new ItemAirshipV3Lime());
		item_airship_v3_magenta = registerItem(new ItemAirshipV3Magenta());
		item_airship_v3_orange = registerItem(new ItemAirshipV3Orange());
		item_airship_v3_pink = registerItem(new ItemAirshipV3Pink());
		item_airship_v3_purple = registerItem(new ItemAirshipV3Purple());
		item_airship_v3_red = registerItem(new ItemAirshipV3Red());
		item_airship_v3_white = registerItem(new ItemAirshipV3White());
		item_airship_v3_yellow = registerItem(new ItemAirshipV3Yellow());
		item_airship_v3_admin = registerItem(new ItemAirshipV3Admin());
		
		item_airship_v4_normal = registerItem(new ItemAirshipV4Normal());
		item_airship_v4_black = registerItem(new ItemAirshipV4Black());
		item_airship_v4_blue = registerItem(new ItemAirshipV4Blue());
		item_airship_v4_brown = registerItem(new ItemAirshipV4Brown());
		item_airship_v4_cyan = registerItem(new ItemAirshipV4Cyan());
		item_airship_v4_gray = registerItem(new ItemAirshipV4Gray());
		item_airship_v4_green = registerItem(new ItemAirshipV4Green());
		item_airship_v4_lightblue = registerItem(new ItemAirshipV4LightBlue());
		item_airship_v4_lightgray = registerItem(new ItemAirshipV4LightGray());
		item_airship_v4_lime = registerItem(new ItemAirshipV4Lime());
		item_airship_v4_magenta = registerItem(new ItemAirshipV4Magenta());
		item_airship_v4_orange = registerItem(new ItemAirshipV4Orange());
		item_airship_v4_pink = registerItem(new ItemAirshipV4Pink());
		item_airship_v4_purple = registerItem(new ItemAirshipV4Purple());
		item_airship_v4_red = registerItem(new ItemAirshipV4Red());
		item_airship_v4_white = registerItem(new ItemAirshipV4White());
		item_airship_v4_yellow = registerItem(new ItemAirshipV4Yellow());
		item_airship_v4_admin = registerItem(new ItemAirshipV4Admin());
		
		item_paint_black = registerItem(new ItemPaint(EntityAirshipV1Core.Type.BLACK));
		item_paint_blue = registerItem(new ItemPaint(EntityAirshipV1Core.Type.BLUE));
		item_paint_brown = registerItem(new ItemPaint(EntityAirshipV1Core.Type.BROWN));
		item_paint_cyan = registerItem(new ItemPaint(EntityAirshipV1Core.Type.CYAN));
		item_paint_gray = registerItem(new ItemPaint(EntityAirshipV1Core.Type.GRAY));
		item_paint_green = registerItem(new ItemPaint(EntityAirshipV1Core.Type.GREEN));
		item_paint_lightblue = registerItem(new ItemPaint(EntityAirshipV1Core.Type.LIGHTBLUE));
		item_paint_lightgray = registerItem(new ItemPaint(EntityAirshipV1Core.Type.LIGHTGRAY));
		item_paint_lime = registerItem(new ItemPaint(EntityAirshipV1Core.Type.LIME));
		item_paint_magenta = registerItem(new ItemPaint(EntityAirshipV1Core.Type.MAGENTA));
		item_paint_orange = registerItem(new ItemPaint(EntityAirshipV1Core.Type.ORANGE));
		item_paint_pink = registerItem(new ItemPaint(EntityAirshipV1Core.Type.PINK));
		item_paint_purple = registerItem(new ItemPaint(EntityAirshipV1Core.Type.PURPLE));
		item_paint_red = registerItem(new ItemPaint(EntityAirshipV1Core.Type.RED));
		item_paint_white = registerItem(new ItemPaint(EntityAirshipV1Core.Type.WHITE));
		item_paint_yellow = registerItem(new ItemPaint(EntityAirshipV1Core.Type.YELLOW));
		
		achievement_airship_create_engine = registerItem(new ItemAchievementEngine());
		achievement_airship_create_ignition = registerItem(new ItemAchievementIgnition());
		achievement_airship_create = registerItem(new ItemAchievementCreate());
		achievement_airship_create_color = registerItem(new ItemAchievementCreateColor());
		achievement_airship_create_module = registerItem(new ItemAchievementCreateModule());
		
		achievement_airship_airborn = registerItem(new ItemAchievementAirborn());
		achievement_airship_water = registerItem(new ItemAchievementWater());
		achievement_airship_lava = registerItem(new ItemAchievementLava());
	}
	
	private static <V extends Item> V registerItem(V item) 
	{
		GameRegistry.register(item);
		items.add(item);
		
		return item;
	}
}
