package com.viesis.viescraft.client;

import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.client.registry.RenderingRegistry;

import com.viesis.viescraft.api.ItemsVC;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.diamond.RenderAirshipV4DiamondYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.emerald.RenderAirshipV4EmeraldYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.gold.RenderAirshipV4GoldYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.iron.RenderAirshipV4IronYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.lapislazuli.RenderAirshipV4LapisLazuliYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.obsidian.RenderAirshipV4ObsidianYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstonePink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstonePurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.redstone.RenderAirshipV4RedstoneYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Admin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Black;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Blue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Brown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Cyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Gray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Green;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0LightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0LightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Lime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Magenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Normal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Orange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Pink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Purple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Red;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0White;
import com.viesis.viescraft.client.entity.render.airshipcolors.v4.wood0.RenderAirshipV4Wood0Yellow;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondBlack;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondBrown;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondCyan;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondGreen;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondLime;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondNormal;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondOrange;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondPink;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondPurple;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondRed;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondWhite;
import com.viesis.viescraft.client.entity.render.projectile.v4.diamond.RenderItemAirshipV4DiamondYellow;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldBlack;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldBrown;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldCyan;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldGreen;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldLime;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldNormal;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldOrange;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldPink;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldPurple;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldRed;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldWhite;
import com.viesis.viescraft.client.entity.render.projectile.v4.emerald.RenderItemAirshipV4EmeraldYellow;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldBlack;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldBrown;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldCyan;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldGreen;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldLime;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldNormal;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldOrange;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldPink;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldPurple;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldRed;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldWhite;
import com.viesis.viescraft.client.entity.render.projectile.v4.gold.RenderItemAirshipV4GoldYellow;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronBlack;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronBrown;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronCyan;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronGreen;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronLime;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronNormal;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronOrange;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronPink;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronPurple;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronRed;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronWhite;
import com.viesis.viescraft.client.entity.render.projectile.v4.iron.RenderItemAirshipV4IronYellow;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliBlack;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliBrown;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliCyan;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliGreen;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliLime;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliNormal;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliOrange;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliPink;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliPurple;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliRed;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliWhite;
import com.viesis.viescraft.client.entity.render.projectile.v4.lapislazuli.RenderItemAirshipV4LapisLazuliYellow;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianBlack;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianBrown;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianCyan;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianGreen;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianLime;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianNormal;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianOrange;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianPink;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianPurple;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianRed;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianWhite;
import com.viesis.viescraft.client.entity.render.projectile.v4.obsidian.RenderItemAirshipV4ObsidianYellow;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneBlack;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneBrown;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneCyan;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneGreen;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneLime;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneNormal;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneOrange;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstonePink;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstonePurple;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneRed;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneWhite;
import com.viesis.viescraft.client.entity.render.projectile.v4.redstone.RenderItemAirshipV4RedstoneYellow;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Admin;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Black;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Blue;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Brown;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Cyan;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Gray;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Green;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0LightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0LightGray;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Lime;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Magenta;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Normal;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Orange;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Pink;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Purple;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Red;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0White;
import com.viesis.viescraft.client.entity.render.projectile.v4.wood0.RenderItemAirshipV4Wood0Yellow;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondLime;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondPink;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondRed;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v4.diamond.EntityAirshipV4DiamondYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldLime;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldPink;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldRed;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v4.emerald.EntityAirshipV4EmeraldYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldLime;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldPink;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldRed;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v4.gold.EntityAirshipV4GoldYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronLime;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronPink;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronRed;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v4.iron.EntityAirshipV4IronYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliLime;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliPink;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliRed;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v4.lapislazuli.EntityAirshipV4LapisLazuliYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianLime;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianPink;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianRed;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v4.obsidian.EntityAirshipV4ObsidianYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneLime;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstonePink;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstonePurple;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneRed;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v4.redstone.EntityAirshipV4RedstoneYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Admin;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Black;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Blue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Brown;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Cyan;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Gray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Green;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0LightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0LightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Lime;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Magenta;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Normal;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Orange;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Pink;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Purple;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Red;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0White;
import com.viesis.viescraft.common.entity.airshipcolors.v4.wood0.EntityAirshipV4Wood0Yellow;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondBlack;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondBrown;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondCyan;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondGreen;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondLime;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondNormal;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondOrange;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondPink;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondPurple;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondRed;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondWhite;
import com.viesis.viescraft.common.entity.airshipitems.v4.diamond.EntityItemAirshipV4DiamondYellow;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldBlack;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldBrown;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldCyan;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldGreen;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldLime;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldNormal;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldOrange;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldPink;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldPurple;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldRed;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldWhite;
import com.viesis.viescraft.common.entity.airshipitems.v4.emerald.EntityItemAirshipV4EmeraldYellow;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldBlack;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldBrown;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldCyan;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldGreen;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldLime;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldNormal;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldOrange;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldPink;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldPurple;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldRed;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldWhite;
import com.viesis.viescraft.common.entity.airshipitems.v4.gold.EntityItemAirshipV4GoldYellow;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronBlack;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronBrown;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronCyan;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronGreen;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronLime;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronNormal;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronOrange;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronPink;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronPurple;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronRed;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronWhite;
import com.viesis.viescraft.common.entity.airshipitems.v4.iron.EntityItemAirshipV4IronYellow;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliBlack;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliBrown;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliCyan;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliGreen;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliLime;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliNormal;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliOrange;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliPink;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliPurple;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliRed;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliWhite;
import com.viesis.viescraft.common.entity.airshipitems.v4.lapislazuli.EntityItemAirshipV4LapisLazuliYellow;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianBlack;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianBrown;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianCyan;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianGreen;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianLime;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianNormal;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianOrange;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianPink;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianPurple;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianRed;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianWhite;
import com.viesis.viescraft.common.entity.airshipitems.v4.obsidian.EntityItemAirshipV4ObsidianYellow;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneBlack;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneBrown;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneCyan;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneGreen;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneLime;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneNormal;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneOrange;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstonePink;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstonePurple;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneRed;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneWhite;
import com.viesis.viescraft.common.entity.airshipitems.v4.redstone.EntityItemAirshipV4RedstoneYellow;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Admin;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Black;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Blue;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Brown;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Cyan;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Gray;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Green;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0LightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0LightGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Lime;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Magenta;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Normal;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Orange;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Pink;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Purple;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Red;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0White;
import com.viesis.viescraft.common.entity.airshipitems.v4.wood0.EntityItemAirshipV4Wood0Yellow;

public final class InitEntityV4VCRender extends ItemsVC {
	
	public static RenderManager VCRender = Minecraft.getMinecraft().getRenderManager(); 
	
	public static void registerRenders()
	{
		
		registerRender(EntityItemAirshipV4Wood0Normal.class, new RenderItemAirshipV4Wood0Normal(VCRender));
		registerRender(EntityItemAirshipV4Wood0Black.class, new RenderItemAirshipV4Wood0Black(VCRender));
		registerRender(EntityItemAirshipV4Wood0Blue.class, new RenderItemAirshipV4Wood0Blue(VCRender));
		registerRender(EntityItemAirshipV4Wood0Brown.class, new RenderItemAirshipV4Wood0Brown(VCRender));
		registerRender(EntityItemAirshipV4Wood0Cyan.class, new RenderItemAirshipV4Wood0Cyan(VCRender));
		registerRender(EntityItemAirshipV4Wood0Gray.class, new RenderItemAirshipV4Wood0Gray(VCRender));
		registerRender(EntityItemAirshipV4Wood0Green.class, new RenderItemAirshipV4Wood0Green(VCRender));
		registerRender(EntityItemAirshipV4Wood0LightBlue.class, new RenderItemAirshipV4Wood0LightBlue(VCRender));
		registerRender(EntityItemAirshipV4Wood0LightGray.class, new RenderItemAirshipV4Wood0LightGray(VCRender));
		registerRender(EntityItemAirshipV4Wood0Lime.class, new RenderItemAirshipV4Wood0Lime(VCRender));
		registerRender(EntityItemAirshipV4Wood0Magenta.class, new RenderItemAirshipV4Wood0Magenta(VCRender));
		registerRender(EntityItemAirshipV4Wood0Orange.class, new RenderItemAirshipV4Wood0Orange(VCRender));
		registerRender(EntityItemAirshipV4Wood0Pink.class, new RenderItemAirshipV4Wood0Pink(VCRender));
		registerRender(EntityItemAirshipV4Wood0Purple.class, new RenderItemAirshipV4Wood0Purple(VCRender));
		registerRender(EntityItemAirshipV4Wood0Red.class, new RenderItemAirshipV4Wood0Red(VCRender));
		registerRender(EntityItemAirshipV4Wood0White.class, new RenderItemAirshipV4Wood0White(VCRender));
		registerRender(EntityItemAirshipV4Wood0Yellow.class, new RenderItemAirshipV4Wood0Yellow(VCRender));
		registerRender(EntityItemAirshipV4Wood0Admin.class, new RenderItemAirshipV4Wood0Admin(VCRender));
		
		registerRender(EntityItemAirshipV4IronNormal.class, new RenderItemAirshipV4IronNormal(VCRender));
		registerRender(EntityItemAirshipV4IronBlack.class, new RenderItemAirshipV4IronBlack(VCRender));
		registerRender(EntityItemAirshipV4IronBlue.class, new RenderItemAirshipV4IronBlue(VCRender));
		registerRender(EntityItemAirshipV4IronBrown.class, new RenderItemAirshipV4IronBrown(VCRender));
		registerRender(EntityItemAirshipV4IronCyan.class, new RenderItemAirshipV4IronCyan(VCRender));
		registerRender(EntityItemAirshipV4IronGray.class, new RenderItemAirshipV4IronGray(VCRender));
		registerRender(EntityItemAirshipV4IronGreen.class, new RenderItemAirshipV4IronGreen(VCRender));
		registerRender(EntityItemAirshipV4IronLightBlue.class, new RenderItemAirshipV4IronLightBlue(VCRender));
		registerRender(EntityItemAirshipV4IronLightGray.class, new RenderItemAirshipV4IronLightGray(VCRender));
		registerRender(EntityItemAirshipV4IronLime.class, new RenderItemAirshipV4IronLime(VCRender));
		registerRender(EntityItemAirshipV4IronMagenta.class, new RenderItemAirshipV4IronMagenta(VCRender));
		registerRender(EntityItemAirshipV4IronOrange.class, new RenderItemAirshipV4IronOrange(VCRender));
		registerRender(EntityItemAirshipV4IronPink.class, new RenderItemAirshipV4IronPink(VCRender));
		registerRender(EntityItemAirshipV4IronPurple.class, new RenderItemAirshipV4IronPurple(VCRender));
		registerRender(EntityItemAirshipV4IronRed.class, new RenderItemAirshipV4IronRed(VCRender));
		registerRender(EntityItemAirshipV4IronWhite.class, new RenderItemAirshipV4IronWhite(VCRender));
		registerRender(EntityItemAirshipV4IronYellow.class, new RenderItemAirshipV4IronYellow(VCRender));
		registerRender(EntityItemAirshipV4IronAdmin.class, new RenderItemAirshipV4IronAdmin(VCRender));
		
		registerRender(EntityItemAirshipV4RedstoneNormal.class, new RenderItemAirshipV4RedstoneNormal(VCRender));
		registerRender(EntityItemAirshipV4RedstoneBlack.class, new RenderItemAirshipV4RedstoneBlack(VCRender));
		registerRender(EntityItemAirshipV4RedstoneBlue.class, new RenderItemAirshipV4RedstoneBlue(VCRender));
		registerRender(EntityItemAirshipV4RedstoneBrown.class, new RenderItemAirshipV4RedstoneBrown(VCRender));
		registerRender(EntityItemAirshipV4RedstoneCyan.class, new RenderItemAirshipV4RedstoneCyan(VCRender));
		registerRender(EntityItemAirshipV4RedstoneGray.class, new RenderItemAirshipV4RedstoneGray(VCRender));
		registerRender(EntityItemAirshipV4RedstoneGreen.class, new RenderItemAirshipV4RedstoneGreen(VCRender));
		registerRender(EntityItemAirshipV4RedstoneLightBlue.class, new RenderItemAirshipV4RedstoneLightBlue(VCRender));
		registerRender(EntityItemAirshipV4RedstoneLightGray.class, new RenderItemAirshipV4RedstoneLightGray(VCRender));
		registerRender(EntityItemAirshipV4RedstoneLime.class, new RenderItemAirshipV4RedstoneLime(VCRender));
		registerRender(EntityItemAirshipV4RedstoneMagenta.class, new RenderItemAirshipV4RedstoneMagenta(VCRender));
		registerRender(EntityItemAirshipV4RedstoneOrange.class, new RenderItemAirshipV4RedstoneOrange(VCRender));
		registerRender(EntityItemAirshipV4RedstonePink.class, new RenderItemAirshipV4RedstonePink(VCRender));
		registerRender(EntityItemAirshipV4RedstonePurple.class, new RenderItemAirshipV4RedstonePurple(VCRender));
		registerRender(EntityItemAirshipV4RedstoneRed.class, new RenderItemAirshipV4RedstoneRed(VCRender));
		registerRender(EntityItemAirshipV4RedstoneWhite.class, new RenderItemAirshipV4RedstoneWhite(VCRender));
		registerRender(EntityItemAirshipV4RedstoneYellow.class, new RenderItemAirshipV4RedstoneYellow(VCRender));
		registerRender(EntityItemAirshipV4RedstoneAdmin.class, new RenderItemAirshipV4RedstoneAdmin(VCRender));
		
		registerRender(EntityItemAirshipV4GoldNormal.class, new RenderItemAirshipV4GoldNormal(VCRender));
		registerRender(EntityItemAirshipV4GoldBlack.class, new RenderItemAirshipV4GoldBlack(VCRender));
		registerRender(EntityItemAirshipV4GoldBlue.class, new RenderItemAirshipV4GoldBlue(VCRender));
		registerRender(EntityItemAirshipV4GoldBrown.class, new RenderItemAirshipV4GoldBrown(VCRender));
		registerRender(EntityItemAirshipV4GoldCyan.class, new RenderItemAirshipV4GoldCyan(VCRender));
		registerRender(EntityItemAirshipV4GoldGray.class, new RenderItemAirshipV4GoldGray(VCRender));
		registerRender(EntityItemAirshipV4GoldGreen.class, new RenderItemAirshipV4GoldGreen(VCRender));
		registerRender(EntityItemAirshipV4GoldLightBlue.class, new RenderItemAirshipV4GoldLightBlue(VCRender));
		registerRender(EntityItemAirshipV4GoldLightGray.class, new RenderItemAirshipV4GoldLightGray(VCRender));
		registerRender(EntityItemAirshipV4GoldLime.class, new RenderItemAirshipV4GoldLime(VCRender));
		registerRender(EntityItemAirshipV4GoldMagenta.class, new RenderItemAirshipV4GoldMagenta(VCRender));
		registerRender(EntityItemAirshipV4GoldOrange.class, new RenderItemAirshipV4GoldOrange(VCRender));
		registerRender(EntityItemAirshipV4GoldPink.class, new RenderItemAirshipV4GoldPink(VCRender));
		registerRender(EntityItemAirshipV4GoldPurple.class, new RenderItemAirshipV4GoldPurple(VCRender));
		registerRender(EntityItemAirshipV4GoldRed.class, new RenderItemAirshipV4GoldRed(VCRender));
		registerRender(EntityItemAirshipV4GoldWhite.class, new RenderItemAirshipV4GoldWhite(VCRender));
		registerRender(EntityItemAirshipV4GoldYellow.class, new RenderItemAirshipV4GoldYellow(VCRender));
		registerRender(EntityItemAirshipV4GoldAdmin.class, new RenderItemAirshipV4GoldAdmin(VCRender));
		
		registerRender(EntityItemAirshipV4LapisLazuliNormal.class, new RenderItemAirshipV4LapisLazuliNormal(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliBlack.class, new RenderItemAirshipV4LapisLazuliBlack(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliBlue.class, new RenderItemAirshipV4LapisLazuliBlue(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliBrown.class, new RenderItemAirshipV4LapisLazuliBrown(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliCyan.class, new RenderItemAirshipV4LapisLazuliCyan(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliGray.class, new RenderItemAirshipV4LapisLazuliGray(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliGreen.class, new RenderItemAirshipV4LapisLazuliGreen(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliLightBlue.class, new RenderItemAirshipV4LapisLazuliLightBlue(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliLightGray.class, new RenderItemAirshipV4LapisLazuliLightGray(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliLime.class, new RenderItemAirshipV4LapisLazuliLime(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliMagenta.class, new RenderItemAirshipV4LapisLazuliMagenta(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliOrange.class, new RenderItemAirshipV4LapisLazuliOrange(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliPink.class, new RenderItemAirshipV4LapisLazuliPink(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliPurple.class, new RenderItemAirshipV4LapisLazuliPurple(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliRed.class, new RenderItemAirshipV4LapisLazuliRed(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliWhite.class, new RenderItemAirshipV4LapisLazuliWhite(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliYellow.class, new RenderItemAirshipV4LapisLazuliYellow(VCRender));
		registerRender(EntityItemAirshipV4LapisLazuliAdmin.class, new RenderItemAirshipV4LapisLazuliAdmin(VCRender));
		
		registerRender(EntityItemAirshipV4ObsidianNormal.class, new RenderItemAirshipV4ObsidianNormal(VCRender));
		registerRender(EntityItemAirshipV4ObsidianBlack.class, new RenderItemAirshipV4ObsidianBlack(VCRender));
		registerRender(EntityItemAirshipV4ObsidianBlue.class, new RenderItemAirshipV4ObsidianBlue(VCRender));
		registerRender(EntityItemAirshipV4ObsidianBrown.class, new RenderItemAirshipV4ObsidianBrown(VCRender));
		registerRender(EntityItemAirshipV4ObsidianCyan.class, new RenderItemAirshipV4ObsidianCyan(VCRender));
		registerRender(EntityItemAirshipV4ObsidianGray.class, new RenderItemAirshipV4ObsidianGray(VCRender));
		registerRender(EntityItemAirshipV4ObsidianGreen.class, new RenderItemAirshipV4ObsidianGreen(VCRender));
		registerRender(EntityItemAirshipV4ObsidianLightBlue.class, new RenderItemAirshipV4ObsidianLightBlue(VCRender));
		registerRender(EntityItemAirshipV4ObsidianLightGray.class, new RenderItemAirshipV4ObsidianLightGray(VCRender));
		registerRender(EntityItemAirshipV4ObsidianLime.class, new RenderItemAirshipV4ObsidianLime(VCRender));
		registerRender(EntityItemAirshipV4ObsidianMagenta.class, new RenderItemAirshipV4ObsidianMagenta(VCRender));
		registerRender(EntityItemAirshipV4ObsidianOrange.class, new RenderItemAirshipV4ObsidianOrange(VCRender));
		registerRender(EntityItemAirshipV4ObsidianPink.class, new RenderItemAirshipV4ObsidianPink(VCRender));
		registerRender(EntityItemAirshipV4ObsidianPurple.class, new RenderItemAirshipV4ObsidianPurple(VCRender));
		registerRender(EntityItemAirshipV4ObsidianRed.class, new RenderItemAirshipV4ObsidianRed(VCRender));
		registerRender(EntityItemAirshipV4ObsidianWhite.class, new RenderItemAirshipV4ObsidianWhite(VCRender));
		registerRender(EntityItemAirshipV4ObsidianYellow.class, new RenderItemAirshipV4ObsidianYellow(VCRender));
		registerRender(EntityItemAirshipV4ObsidianAdmin.class, new RenderItemAirshipV4ObsidianAdmin(VCRender));
		
		registerRender(EntityItemAirshipV4DiamondNormal.class, new RenderItemAirshipV4DiamondNormal(VCRender));
		registerRender(EntityItemAirshipV4DiamondBlack.class, new RenderItemAirshipV4DiamondBlack(VCRender));
		registerRender(EntityItemAirshipV4DiamondBlue.class, new RenderItemAirshipV4DiamondBlue(VCRender));
		registerRender(EntityItemAirshipV4DiamondBrown.class, new RenderItemAirshipV4DiamondBrown(VCRender));
		registerRender(EntityItemAirshipV4DiamondCyan.class, new RenderItemAirshipV4DiamondCyan(VCRender));
		registerRender(EntityItemAirshipV4DiamondGray.class, new RenderItemAirshipV4DiamondGray(VCRender));
		registerRender(EntityItemAirshipV4DiamondGreen.class, new RenderItemAirshipV4DiamondGreen(VCRender));
		registerRender(EntityItemAirshipV4DiamondLightBlue.class, new RenderItemAirshipV4DiamondLightBlue(VCRender));
		registerRender(EntityItemAirshipV4DiamondLightGray.class, new RenderItemAirshipV4DiamondLightGray(VCRender));
		registerRender(EntityItemAirshipV4DiamondLime.class, new RenderItemAirshipV4DiamondLime(VCRender));
		registerRender(EntityItemAirshipV4DiamondMagenta.class, new RenderItemAirshipV4DiamondMagenta(VCRender));
		registerRender(EntityItemAirshipV4DiamondOrange.class, new RenderItemAirshipV4DiamondOrange(VCRender));
		registerRender(EntityItemAirshipV4DiamondPink.class, new RenderItemAirshipV4DiamondPink(VCRender));
		registerRender(EntityItemAirshipV4DiamondPurple.class, new RenderItemAirshipV4DiamondPurple(VCRender));
		registerRender(EntityItemAirshipV4DiamondRed.class, new RenderItemAirshipV4DiamondRed(VCRender));
		registerRender(EntityItemAirshipV4DiamondWhite.class, new RenderItemAirshipV4DiamondWhite(VCRender));
		registerRender(EntityItemAirshipV4DiamondYellow.class, new RenderItemAirshipV4DiamondYellow(VCRender));
		registerRender(EntityItemAirshipV4DiamondAdmin.class, new RenderItemAirshipV4DiamondAdmin(VCRender));
		
		registerRender(EntityItemAirshipV4EmeraldNormal.class, new RenderItemAirshipV4EmeraldNormal(VCRender));
		registerRender(EntityItemAirshipV4EmeraldBlack.class, new RenderItemAirshipV4EmeraldBlack(VCRender));
		registerRender(EntityItemAirshipV4EmeraldBlue.class, new RenderItemAirshipV4EmeraldBlue(VCRender));
		registerRender(EntityItemAirshipV4EmeraldBrown.class, new RenderItemAirshipV4EmeraldBrown(VCRender));
		registerRender(EntityItemAirshipV4EmeraldCyan.class, new RenderItemAirshipV4EmeraldCyan(VCRender));
		registerRender(EntityItemAirshipV4EmeraldGray.class, new RenderItemAirshipV4EmeraldGray(VCRender));
		registerRender(EntityItemAirshipV4EmeraldGreen.class, new RenderItemAirshipV4EmeraldGreen(VCRender));
		registerRender(EntityItemAirshipV4EmeraldLightBlue.class, new RenderItemAirshipV4EmeraldLightBlue(VCRender));
		registerRender(EntityItemAirshipV4EmeraldLightGray.class, new RenderItemAirshipV4EmeraldLightGray(VCRender));
		registerRender(EntityItemAirshipV4EmeraldLime.class, new RenderItemAirshipV4EmeraldLime(VCRender));
		registerRender(EntityItemAirshipV4EmeraldMagenta.class, new RenderItemAirshipV4EmeraldMagenta(VCRender));
		registerRender(EntityItemAirshipV4EmeraldOrange.class, new RenderItemAirshipV4EmeraldOrange(VCRender));
		registerRender(EntityItemAirshipV4EmeraldPink.class, new RenderItemAirshipV4EmeraldPink(VCRender));
		registerRender(EntityItemAirshipV4EmeraldPurple.class, new RenderItemAirshipV4EmeraldPurple(VCRender));
		registerRender(EntityItemAirshipV4EmeraldRed.class, new RenderItemAirshipV4EmeraldRed(VCRender));
		registerRender(EntityItemAirshipV4EmeraldWhite.class, new RenderItemAirshipV4EmeraldWhite(VCRender));
		registerRender(EntityItemAirshipV4EmeraldYellow.class, new RenderItemAirshipV4EmeraldYellow(VCRender));
		registerRender(EntityItemAirshipV4EmeraldAdmin.class, new RenderItemAirshipV4EmeraldAdmin(VCRender));
		
		//===========================================================================
		
		registerRender(EntityAirshipV4Wood0Normal.class, new RenderAirshipV4Wood0Normal(VCRender));
		registerRender(EntityAirshipV4Wood0Black.class, new RenderAirshipV4Wood0Black(VCRender));
		registerRender(EntityAirshipV4Wood0Blue.class, new RenderAirshipV4Wood0Blue(VCRender));
		registerRender(EntityAirshipV4Wood0Brown.class, new RenderAirshipV4Wood0Brown(VCRender));
		registerRender(EntityAirshipV4Wood0Cyan.class, new RenderAirshipV4Wood0Cyan(VCRender));
		registerRender(EntityAirshipV4Wood0Gray.class, new RenderAirshipV4Wood0Gray(VCRender));
		registerRender(EntityAirshipV4Wood0Green.class, new RenderAirshipV4Wood0Green(VCRender));
		registerRender(EntityAirshipV4Wood0LightBlue.class, new RenderAirshipV4Wood0LightBlue(VCRender));
		registerRender(EntityAirshipV4Wood0LightGray.class, new RenderAirshipV4Wood0LightGray(VCRender));
		registerRender(EntityAirshipV4Wood0Lime.class, new RenderAirshipV4Wood0Lime(VCRender));
		registerRender(EntityAirshipV4Wood0Magenta.class, new RenderAirshipV4Wood0Magenta(VCRender));
		registerRender(EntityAirshipV4Wood0Orange.class, new RenderAirshipV4Wood0Orange(VCRender));
		registerRender(EntityAirshipV4Wood0Pink.class, new RenderAirshipV4Wood0Pink(VCRender));
		registerRender(EntityAirshipV4Wood0Purple.class, new RenderAirshipV4Wood0Purple(VCRender));
		registerRender(EntityAirshipV4Wood0Red.class, new RenderAirshipV4Wood0Red(VCRender));
		registerRender(EntityAirshipV4Wood0White.class, new RenderAirshipV4Wood0White(VCRender));
		registerRender(EntityAirshipV4Wood0Yellow.class, new RenderAirshipV4Wood0Yellow(VCRender));
		registerRender(EntityAirshipV4Wood0Admin.class, new RenderAirshipV4Wood0Admin(VCRender));
		
		registerRender(EntityAirshipV4IronNormal.class, new RenderAirshipV4IronNormal(VCRender));
		registerRender(EntityAirshipV4IronBlack.class, new RenderAirshipV4IronBlack(VCRender));
		registerRender(EntityAirshipV4IronBlue.class, new RenderAirshipV4IronBlue(VCRender));
		registerRender(EntityAirshipV4IronBrown.class, new RenderAirshipV4IronBrown(VCRender));
		registerRender(EntityAirshipV4IronCyan.class, new RenderAirshipV4IronCyan(VCRender));
		registerRender(EntityAirshipV4IronGray.class, new RenderAirshipV4IronGray(VCRender));
		registerRender(EntityAirshipV4IronGreen.class, new RenderAirshipV4IronGreen(VCRender));
		registerRender(EntityAirshipV4IronLightBlue.class, new RenderAirshipV4IronLightBlue(VCRender));
		registerRender(EntityAirshipV4IronLightGray.class, new RenderAirshipV4IronLightGray(VCRender));
		registerRender(EntityAirshipV4IronLime.class, new RenderAirshipV4IronLime(VCRender));
		registerRender(EntityAirshipV4IronMagenta.class, new RenderAirshipV4IronMagenta(VCRender));
		registerRender(EntityAirshipV4IronOrange.class, new RenderAirshipV4IronOrange(VCRender));
		registerRender(EntityAirshipV4IronPink.class, new RenderAirshipV4IronPink(VCRender));
		registerRender(EntityAirshipV4IronPurple.class, new RenderAirshipV4IronPurple(VCRender));
		registerRender(EntityAirshipV4IronRed.class, new RenderAirshipV4IronRed(VCRender));
		registerRender(EntityAirshipV4IronWhite.class, new RenderAirshipV4IronWhite(VCRender));
		registerRender(EntityAirshipV4IronYellow.class, new RenderAirshipV4IronYellow(VCRender));
		registerRender(EntityAirshipV4IronAdmin.class, new RenderAirshipV4IronAdmin(VCRender));
		
		registerRender(EntityAirshipV4RedstoneNormal.class, new RenderAirshipV4RedstoneNormal(VCRender));
		registerRender(EntityAirshipV4RedstoneBlack.class, new RenderAirshipV4RedstoneBlack(VCRender));
		registerRender(EntityAirshipV4RedstoneBlue.class, new RenderAirshipV4RedstoneBlue(VCRender));
		registerRender(EntityAirshipV4RedstoneBrown.class, new RenderAirshipV4RedstoneBrown(VCRender));
		registerRender(EntityAirshipV4RedstoneCyan.class, new RenderAirshipV4RedstoneCyan(VCRender));
		registerRender(EntityAirshipV4RedstoneGray.class, new RenderAirshipV4RedstoneGray(VCRender));
		registerRender(EntityAirshipV4RedstoneGreen.class, new RenderAirshipV4RedstoneGreen(VCRender));
		registerRender(EntityAirshipV4RedstoneLightBlue.class, new RenderAirshipV4RedstoneLightBlue(VCRender));
		registerRender(EntityAirshipV4RedstoneLightGray.class, new RenderAirshipV4RedstoneLightGray(VCRender));
		registerRender(EntityAirshipV4RedstoneLime.class, new RenderAirshipV4RedstoneLime(VCRender));
		registerRender(EntityAirshipV4RedstoneMagenta.class, new RenderAirshipV4RedstoneMagenta(VCRender));
		registerRender(EntityAirshipV4RedstoneOrange.class, new RenderAirshipV4RedstoneOrange(VCRender));
		registerRender(EntityAirshipV4RedstonePink.class, new RenderAirshipV4RedstonePink(VCRender));
		registerRender(EntityAirshipV4RedstonePurple.class, new RenderAirshipV4RedstonePurple(VCRender));
		registerRender(EntityAirshipV4RedstoneRed.class, new RenderAirshipV4RedstoneRed(VCRender));
		registerRender(EntityAirshipV4RedstoneWhite.class, new RenderAirshipV4RedstoneWhite(VCRender));
		registerRender(EntityAirshipV4RedstoneYellow.class, new RenderAirshipV4RedstoneYellow(VCRender));
		registerRender(EntityAirshipV4RedstoneAdmin.class, new RenderAirshipV4RedstoneAdmin(VCRender));
		
		registerRender(EntityAirshipV4GoldNormal.class, new RenderAirshipV4GoldNormal(VCRender));
		registerRender(EntityAirshipV4GoldBlack.class, new RenderAirshipV4GoldBlack(VCRender));
		registerRender(EntityAirshipV4GoldBlue.class, new RenderAirshipV4GoldBlue(VCRender));
		registerRender(EntityAirshipV4GoldBrown.class, new RenderAirshipV4GoldBrown(VCRender));
		registerRender(EntityAirshipV4GoldCyan.class, new RenderAirshipV4GoldCyan(VCRender));
		registerRender(EntityAirshipV4GoldGray.class, new RenderAirshipV4GoldGray(VCRender));
		registerRender(EntityAirshipV4GoldGreen.class, new RenderAirshipV4GoldGreen(VCRender));
		registerRender(EntityAirshipV4GoldLightBlue.class, new RenderAirshipV4GoldLightBlue(VCRender));
		registerRender(EntityAirshipV4GoldLightGray.class, new RenderAirshipV4GoldLightGray(VCRender));
		registerRender(EntityAirshipV4GoldLime.class, new RenderAirshipV4GoldLime(VCRender));
		registerRender(EntityAirshipV4GoldMagenta.class, new RenderAirshipV4GoldMagenta(VCRender));
		registerRender(EntityAirshipV4GoldOrange.class, new RenderAirshipV4GoldOrange(VCRender));
		registerRender(EntityAirshipV4GoldPink.class, new RenderAirshipV4GoldPink(VCRender));
		registerRender(EntityAirshipV4GoldPurple.class, new RenderAirshipV4GoldPurple(VCRender));
		registerRender(EntityAirshipV4GoldRed.class, new RenderAirshipV4GoldRed(VCRender));
		registerRender(EntityAirshipV4GoldWhite.class, new RenderAirshipV4GoldWhite(VCRender));
		registerRender(EntityAirshipV4GoldYellow.class, new RenderAirshipV4GoldYellow(VCRender));
		registerRender(EntityAirshipV4GoldAdmin.class, new RenderAirshipV4GoldAdmin(VCRender));
		
		registerRender(EntityAirshipV4LapisLazuliNormal.class, new RenderAirshipV4LapisLazuliNormal(VCRender));
		registerRender(EntityAirshipV4LapisLazuliBlack.class, new RenderAirshipV4LapisLazuliBlack(VCRender));
		registerRender(EntityAirshipV4LapisLazuliBlue.class, new RenderAirshipV4LapisLazuliBlue(VCRender));
		registerRender(EntityAirshipV4LapisLazuliBrown.class, new RenderAirshipV4LapisLazuliBrown(VCRender));
		registerRender(EntityAirshipV4LapisLazuliCyan.class, new RenderAirshipV4LapisLazuliCyan(VCRender));
		registerRender(EntityAirshipV4LapisLazuliGray.class, new RenderAirshipV4LapisLazuliGray(VCRender));
		registerRender(EntityAirshipV4LapisLazuliGreen.class, new RenderAirshipV4LapisLazuliGreen(VCRender));
		registerRender(EntityAirshipV4LapisLazuliLightBlue.class, new RenderAirshipV4LapisLazuliLightBlue(VCRender));
		registerRender(EntityAirshipV4LapisLazuliLightGray.class, new RenderAirshipV4LapisLazuliLightGray(VCRender));
		registerRender(EntityAirshipV4LapisLazuliLime.class, new RenderAirshipV4LapisLazuliLime(VCRender));
		registerRender(EntityAirshipV4LapisLazuliMagenta.class, new RenderAirshipV4LapisLazuliMagenta(VCRender));
		registerRender(EntityAirshipV4LapisLazuliOrange.class, new RenderAirshipV4LapisLazuliOrange(VCRender));
		registerRender(EntityAirshipV4LapisLazuliPink.class, new RenderAirshipV4LapisLazuliPink(VCRender));
		registerRender(EntityAirshipV4LapisLazuliPurple.class, new RenderAirshipV4LapisLazuliPurple(VCRender));
		registerRender(EntityAirshipV4LapisLazuliRed.class, new RenderAirshipV4LapisLazuliRed(VCRender));
		registerRender(EntityAirshipV4LapisLazuliWhite.class, new RenderAirshipV4LapisLazuliWhite(VCRender));
		registerRender(EntityAirshipV4LapisLazuliYellow.class, new RenderAirshipV4LapisLazuliYellow(VCRender));
		registerRender(EntityAirshipV4LapisLazuliAdmin.class, new RenderAirshipV4LapisLazuliAdmin(VCRender));
		
		registerRender(EntityAirshipV4ObsidianNormal.class, new RenderAirshipV4ObsidianNormal(VCRender));
		registerRender(EntityAirshipV4ObsidianBlack.class, new RenderAirshipV4ObsidianBlack(VCRender));
		registerRender(EntityAirshipV4ObsidianBlue.class, new RenderAirshipV4ObsidianBlue(VCRender));
		registerRender(EntityAirshipV4ObsidianBrown.class, new RenderAirshipV4ObsidianBrown(VCRender));
		registerRender(EntityAirshipV4ObsidianCyan.class, new RenderAirshipV4ObsidianCyan(VCRender));
		registerRender(EntityAirshipV4ObsidianGray.class, new RenderAirshipV4ObsidianGray(VCRender));
		registerRender(EntityAirshipV4ObsidianGreen.class, new RenderAirshipV4ObsidianGreen(VCRender));
		registerRender(EntityAirshipV4ObsidianLightBlue.class, new RenderAirshipV4ObsidianLightBlue(VCRender));
		registerRender(EntityAirshipV4ObsidianLightGray.class, new RenderAirshipV4ObsidianLightGray(VCRender));
		registerRender(EntityAirshipV4ObsidianLime.class, new RenderAirshipV4ObsidianLime(VCRender));
		registerRender(EntityAirshipV4ObsidianMagenta.class, new RenderAirshipV4ObsidianMagenta(VCRender));
		registerRender(EntityAirshipV4ObsidianOrange.class, new RenderAirshipV4ObsidianOrange(VCRender));
		registerRender(EntityAirshipV4ObsidianPink.class, new RenderAirshipV4ObsidianPink(VCRender));
		registerRender(EntityAirshipV4ObsidianPurple.class, new RenderAirshipV4ObsidianPurple(VCRender));
		registerRender(EntityAirshipV4ObsidianRed.class, new RenderAirshipV4ObsidianRed(VCRender));
		registerRender(EntityAirshipV4ObsidianWhite.class, new RenderAirshipV4ObsidianWhite(VCRender));
		registerRender(EntityAirshipV4ObsidianYellow.class, new RenderAirshipV4ObsidianYellow(VCRender));
		registerRender(EntityAirshipV4ObsidianAdmin.class, new RenderAirshipV4ObsidianAdmin(VCRender));
		
		registerRender(EntityAirshipV4DiamondNormal.class, new RenderAirshipV4DiamondNormal(VCRender));
		registerRender(EntityAirshipV4DiamondBlack.class, new RenderAirshipV4DiamondBlack(VCRender));
		registerRender(EntityAirshipV4DiamondBlue.class, new RenderAirshipV4DiamondBlue(VCRender));
		registerRender(EntityAirshipV4DiamondBrown.class, new RenderAirshipV4DiamondBrown(VCRender));
		registerRender(EntityAirshipV4DiamondCyan.class, new RenderAirshipV4DiamondCyan(VCRender));
		registerRender(EntityAirshipV4DiamondGray.class, new RenderAirshipV4DiamondGray(VCRender));
		registerRender(EntityAirshipV4DiamondGreen.class, new RenderAirshipV4DiamondGreen(VCRender));
		registerRender(EntityAirshipV4DiamondLightBlue.class, new RenderAirshipV4DiamondLightBlue(VCRender));
		registerRender(EntityAirshipV4DiamondLightGray.class, new RenderAirshipV4DiamondLightGray(VCRender));
		registerRender(EntityAirshipV4DiamondLime.class, new RenderAirshipV4DiamondLime(VCRender));
		registerRender(EntityAirshipV4DiamondMagenta.class, new RenderAirshipV4DiamondMagenta(VCRender));
		registerRender(EntityAirshipV4DiamondOrange.class, new RenderAirshipV4DiamondOrange(VCRender));
		registerRender(EntityAirshipV4DiamondPink.class, new RenderAirshipV4DiamondPink(VCRender));
		registerRender(EntityAirshipV4DiamondPurple.class, new RenderAirshipV4DiamondPurple(VCRender));
		registerRender(EntityAirshipV4DiamondRed.class, new RenderAirshipV4DiamondRed(VCRender));
		registerRender(EntityAirshipV4DiamondWhite.class, new RenderAirshipV4DiamondWhite(VCRender));
		registerRender(EntityAirshipV4DiamondYellow.class, new RenderAirshipV4DiamondYellow(VCRender));
		registerRender(EntityAirshipV4DiamondAdmin.class, new RenderAirshipV4DiamondAdmin(VCRender));
		
		registerRender(EntityAirshipV4EmeraldNormal.class, new RenderAirshipV4EmeraldNormal(VCRender));
		registerRender(EntityAirshipV4EmeraldBlack.class, new RenderAirshipV4EmeraldBlack(VCRender));
		registerRender(EntityAirshipV4EmeraldBlue.class, new RenderAirshipV4EmeraldBlue(VCRender));
		registerRender(EntityAirshipV4EmeraldBrown.class, new RenderAirshipV4EmeraldBrown(VCRender));
		registerRender(EntityAirshipV4EmeraldCyan.class, new RenderAirshipV4EmeraldCyan(VCRender));
		registerRender(EntityAirshipV4EmeraldGray.class, new RenderAirshipV4EmeraldGray(VCRender));
		registerRender(EntityAirshipV4EmeraldGreen.class, new RenderAirshipV4EmeraldGreen(VCRender));
		registerRender(EntityAirshipV4EmeraldLightBlue.class, new RenderAirshipV4EmeraldLightBlue(VCRender));
		registerRender(EntityAirshipV4EmeraldLightGray.class, new RenderAirshipV4EmeraldLightGray(VCRender));
		registerRender(EntityAirshipV4EmeraldLime.class, new RenderAirshipV4EmeraldLime(VCRender));
		registerRender(EntityAirshipV4EmeraldMagenta.class, new RenderAirshipV4EmeraldMagenta(VCRender));
		registerRender(EntityAirshipV4EmeraldOrange.class, new RenderAirshipV4EmeraldOrange(VCRender));
		registerRender(EntityAirshipV4EmeraldPink.class, new RenderAirshipV4EmeraldPink(VCRender));
		registerRender(EntityAirshipV4EmeraldPurple.class, new RenderAirshipV4EmeraldPurple(VCRender));
		registerRender(EntityAirshipV4EmeraldRed.class, new RenderAirshipV4EmeraldRed(VCRender));
		registerRender(EntityAirshipV4EmeraldWhite.class, new RenderAirshipV4EmeraldWhite(VCRender));
		registerRender(EntityAirshipV4EmeraldYellow.class, new RenderAirshipV4EmeraldYellow(VCRender));
		registerRender(EntityAirshipV4EmeraldAdmin.class, new RenderAirshipV4EmeraldAdmin(VCRender));
		
	}
	
	public static void registerRender(Class<? extends Entity> classIn, Render<? extends Entity> renderItem)
	{
		RenderingRegistry.registerEntityRenderingHandler(classIn, renderItem);
	}
}
