package com.viesis.viescraft.client;

import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.client.registry.RenderingRegistry;

import com.viesis.viescraft.api.ItemsVC;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.diamond.RenderAirshipV3DiamondYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.emerald.RenderAirshipV3EmeraldYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.gold.RenderAirshipV3GoldYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.iron.RenderAirshipV3IronYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.lapislazuli.RenderAirshipV3LapisLazuliYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.obsidian.RenderAirshipV3ObsidianYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstonePink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstonePurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.redstone.RenderAirshipV3RedstoneYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Admin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Black;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Blue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Brown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Cyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Gray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Green;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0LightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0LightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Lime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Magenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Normal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Orange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Pink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Purple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Red;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0White;
import com.viesis.viescraft.client.entity.render.airshipcolors.v3.wood0.RenderAirshipV3Wood0Yellow;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondBlack;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondBrown;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondCyan;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondGreen;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondLime;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondNormal;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondOrange;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondPink;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondPurple;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondRed;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondWhite;
import com.viesis.viescraft.client.entity.render.projectile.v3.diamond.RenderItemAirshipV3DiamondYellow;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldBlack;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldBrown;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldCyan;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldGreen;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldLime;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldNormal;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldOrange;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldPink;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldPurple;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldRed;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldWhite;
import com.viesis.viescraft.client.entity.render.projectile.v3.emerald.RenderItemAirshipV3EmeraldYellow;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldBlack;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldBrown;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldCyan;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldGreen;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldLime;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldNormal;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldOrange;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldPink;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldPurple;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldRed;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldWhite;
import com.viesis.viescraft.client.entity.render.projectile.v3.gold.RenderItemAirshipV3GoldYellow;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronBlack;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronBrown;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronCyan;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronGreen;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronLime;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronNormal;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronOrange;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronPink;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronPurple;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronRed;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronWhite;
import com.viesis.viescraft.client.entity.render.projectile.v3.iron.RenderItemAirshipV3IronYellow;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliBlack;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliBrown;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliCyan;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliGreen;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliLime;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliNormal;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliOrange;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliPink;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliPurple;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliRed;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliWhite;
import com.viesis.viescraft.client.entity.render.projectile.v3.lapislazuli.RenderItemAirshipV3LapisLazuliYellow;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianBlack;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianBrown;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianCyan;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianGreen;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianLime;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianNormal;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianOrange;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianPink;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianPurple;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianRed;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianWhite;
import com.viesis.viescraft.client.entity.render.projectile.v3.obsidian.RenderItemAirshipV3ObsidianYellow;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneBlack;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneBrown;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneCyan;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneGreen;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneLime;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneNormal;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneOrange;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstonePink;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstonePurple;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneRed;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneWhite;
import com.viesis.viescraft.client.entity.render.projectile.v3.redstone.RenderItemAirshipV3RedstoneYellow;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Admin;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Black;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Blue;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Brown;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Cyan;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Gray;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Green;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0LightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0LightGray;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Lime;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Magenta;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Normal;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Orange;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Pink;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Purple;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Red;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0White;
import com.viesis.viescraft.client.entity.render.projectile.v3.wood0.RenderItemAirshipV3Wood0Yellow;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondLime;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondPink;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondRed;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v3.diamond.EntityAirshipV3DiamondYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldLime;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldPink;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldRed;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v3.emerald.EntityAirshipV3EmeraldYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldLime;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldPink;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldRed;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v3.gold.EntityAirshipV3GoldYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronLime;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronPink;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronRed;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v3.iron.EntityAirshipV3IronYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliLime;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliPink;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliRed;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v3.lapislazuli.EntityAirshipV3LapisLazuliYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianLime;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianPink;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianRed;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v3.obsidian.EntityAirshipV3ObsidianYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneLime;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstonePink;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstonePurple;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneRed;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v3.redstone.EntityAirshipV3RedstoneYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Admin;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Black;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Blue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Brown;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Cyan;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Gray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Green;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0LightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0LightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Lime;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Magenta;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Normal;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Orange;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Pink;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Purple;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Red;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0White;
import com.viesis.viescraft.common.entity.airshipcolors.v3.wood0.EntityAirshipV3Wood0Yellow;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondBlack;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondBrown;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondCyan;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondGreen;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondLime;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondNormal;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondOrange;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondPink;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondPurple;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondRed;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondWhite;
import com.viesis.viescraft.common.entity.airshipitems.v3.diamond.EntityItemAirshipV3DiamondYellow;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldBlack;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldBrown;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldCyan;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldGreen;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldLime;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldNormal;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldOrange;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldPink;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldPurple;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldRed;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldWhite;
import com.viesis.viescraft.common.entity.airshipitems.v3.emerald.EntityItemAirshipV3EmeraldYellow;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldBlack;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldBrown;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldCyan;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldGreen;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldLime;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldNormal;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldOrange;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldPink;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldPurple;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldRed;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldWhite;
import com.viesis.viescraft.common.entity.airshipitems.v3.gold.EntityItemAirshipV3GoldYellow;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronBlack;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronBrown;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronCyan;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronGreen;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronLime;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronNormal;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronOrange;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronPink;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronPurple;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronRed;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronWhite;
import com.viesis.viescraft.common.entity.airshipitems.v3.iron.EntityItemAirshipV3IronYellow;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliBlack;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliBrown;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliCyan;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliGreen;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliLime;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliNormal;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliOrange;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliPink;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliPurple;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliRed;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliWhite;
import com.viesis.viescraft.common.entity.airshipitems.v3.lapislazuli.EntityItemAirshipV3LapisLazuliYellow;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianBlack;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianBrown;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianCyan;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianGreen;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianLime;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianNormal;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianOrange;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianPink;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianPurple;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianRed;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianWhite;
import com.viesis.viescraft.common.entity.airshipitems.v3.obsidian.EntityItemAirshipV3ObsidianYellow;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneBlack;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneBrown;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneCyan;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneGreen;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneLime;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneNormal;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneOrange;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstonePink;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstonePurple;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneRed;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneWhite;
import com.viesis.viescraft.common.entity.airshipitems.v3.redstone.EntityItemAirshipV3RedstoneYellow;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Admin;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Black;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Blue;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Brown;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Cyan;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Gray;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Green;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0LightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0LightGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Lime;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Magenta;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Normal;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Orange;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Pink;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Purple;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Red;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0White;
import com.viesis.viescraft.common.entity.airshipitems.v3.wood0.EntityItemAirshipV3Wood0Yellow;

public final class InitEntityV3VCRender extends ItemsVC {
	
	public static RenderManager VCRender = Minecraft.getMinecraft().getRenderManager(); 
	
	public static void registerRenders()
	{
		
		registerRender(EntityItemAirshipV3Wood0Normal.class, new RenderItemAirshipV3Wood0Normal(VCRender));
		registerRender(EntityItemAirshipV3Wood0Black.class, new RenderItemAirshipV3Wood0Black(VCRender));
		registerRender(EntityItemAirshipV3Wood0Blue.class, new RenderItemAirshipV3Wood0Blue(VCRender));
		registerRender(EntityItemAirshipV3Wood0Brown.class, new RenderItemAirshipV3Wood0Brown(VCRender));
		registerRender(EntityItemAirshipV3Wood0Cyan.class, new RenderItemAirshipV3Wood0Cyan(VCRender));
		registerRender(EntityItemAirshipV3Wood0Gray.class, new RenderItemAirshipV3Wood0Gray(VCRender));
		registerRender(EntityItemAirshipV3Wood0Green.class, new RenderItemAirshipV3Wood0Green(VCRender));
		registerRender(EntityItemAirshipV3Wood0LightBlue.class, new RenderItemAirshipV3Wood0LightBlue(VCRender));
		registerRender(EntityItemAirshipV3Wood0LightGray.class, new RenderItemAirshipV3Wood0LightGray(VCRender));
		registerRender(EntityItemAirshipV3Wood0Lime.class, new RenderItemAirshipV3Wood0Lime(VCRender));
		registerRender(EntityItemAirshipV3Wood0Magenta.class, new RenderItemAirshipV3Wood0Magenta(VCRender));
		registerRender(EntityItemAirshipV3Wood0Orange.class, new RenderItemAirshipV3Wood0Orange(VCRender));
		registerRender(EntityItemAirshipV3Wood0Pink.class, new RenderItemAirshipV3Wood0Pink(VCRender));
		registerRender(EntityItemAirshipV3Wood0Purple.class, new RenderItemAirshipV3Wood0Purple(VCRender));
		registerRender(EntityItemAirshipV3Wood0Red.class, new RenderItemAirshipV3Wood0Red(VCRender));
		registerRender(EntityItemAirshipV3Wood0White.class, new RenderItemAirshipV3Wood0White(VCRender));
		registerRender(EntityItemAirshipV3Wood0Yellow.class, new RenderItemAirshipV3Wood0Yellow(VCRender));
		registerRender(EntityItemAirshipV3Wood0Admin.class, new RenderItemAirshipV3Wood0Admin(VCRender));
		
		registerRender(EntityItemAirshipV3IronNormal.class, new RenderItemAirshipV3IronNormal(VCRender));
		registerRender(EntityItemAirshipV3IronBlack.class, new RenderItemAirshipV3IronBlack(VCRender));
		registerRender(EntityItemAirshipV3IronBlue.class, new RenderItemAirshipV3IronBlue(VCRender));
		registerRender(EntityItemAirshipV3IronBrown.class, new RenderItemAirshipV3IronBrown(VCRender));
		registerRender(EntityItemAirshipV3IronCyan.class, new RenderItemAirshipV3IronCyan(VCRender));
		registerRender(EntityItemAirshipV3IronGray.class, new RenderItemAirshipV3IronGray(VCRender));
		registerRender(EntityItemAirshipV3IronGreen.class, new RenderItemAirshipV3IronGreen(VCRender));
		registerRender(EntityItemAirshipV3IronLightBlue.class, new RenderItemAirshipV3IronLightBlue(VCRender));
		registerRender(EntityItemAirshipV3IronLightGray.class, new RenderItemAirshipV3IronLightGray(VCRender));
		registerRender(EntityItemAirshipV3IronLime.class, new RenderItemAirshipV3IronLime(VCRender));
		registerRender(EntityItemAirshipV3IronMagenta.class, new RenderItemAirshipV3IronMagenta(VCRender));
		registerRender(EntityItemAirshipV3IronOrange.class, new RenderItemAirshipV3IronOrange(VCRender));
		registerRender(EntityItemAirshipV3IronPink.class, new RenderItemAirshipV3IronPink(VCRender));
		registerRender(EntityItemAirshipV3IronPurple.class, new RenderItemAirshipV3IronPurple(VCRender));
		registerRender(EntityItemAirshipV3IronRed.class, new RenderItemAirshipV3IronRed(VCRender));
		registerRender(EntityItemAirshipV3IronWhite.class, new RenderItemAirshipV3IronWhite(VCRender));
		registerRender(EntityItemAirshipV3IronYellow.class, new RenderItemAirshipV3IronYellow(VCRender));
		registerRender(EntityItemAirshipV3IronAdmin.class, new RenderItemAirshipV3IronAdmin(VCRender));
		
		registerRender(EntityItemAirshipV3RedstoneNormal.class, new RenderItemAirshipV3RedstoneNormal(VCRender));
		registerRender(EntityItemAirshipV3RedstoneBlack.class, new RenderItemAirshipV3RedstoneBlack(VCRender));
		registerRender(EntityItemAirshipV3RedstoneBlue.class, new RenderItemAirshipV3RedstoneBlue(VCRender));
		registerRender(EntityItemAirshipV3RedstoneBrown.class, new RenderItemAirshipV3RedstoneBrown(VCRender));
		registerRender(EntityItemAirshipV3RedstoneCyan.class, new RenderItemAirshipV3RedstoneCyan(VCRender));
		registerRender(EntityItemAirshipV3RedstoneGray.class, new RenderItemAirshipV3RedstoneGray(VCRender));
		registerRender(EntityItemAirshipV3RedstoneGreen.class, new RenderItemAirshipV3RedstoneGreen(VCRender));
		registerRender(EntityItemAirshipV3RedstoneLightBlue.class, new RenderItemAirshipV3RedstoneLightBlue(VCRender));
		registerRender(EntityItemAirshipV3RedstoneLightGray.class, new RenderItemAirshipV3RedstoneLightGray(VCRender));
		registerRender(EntityItemAirshipV3RedstoneLime.class, new RenderItemAirshipV3RedstoneLime(VCRender));
		registerRender(EntityItemAirshipV3RedstoneMagenta.class, new RenderItemAirshipV3RedstoneMagenta(VCRender));
		registerRender(EntityItemAirshipV3RedstoneOrange.class, new RenderItemAirshipV3RedstoneOrange(VCRender));
		registerRender(EntityItemAirshipV3RedstonePink.class, new RenderItemAirshipV3RedstonePink(VCRender));
		registerRender(EntityItemAirshipV3RedstonePurple.class, new RenderItemAirshipV3RedstonePurple(VCRender));
		registerRender(EntityItemAirshipV3RedstoneRed.class, new RenderItemAirshipV3RedstoneRed(VCRender));
		registerRender(EntityItemAirshipV3RedstoneWhite.class, new RenderItemAirshipV3RedstoneWhite(VCRender));
		registerRender(EntityItemAirshipV3RedstoneYellow.class, new RenderItemAirshipV3RedstoneYellow(VCRender));
		registerRender(EntityItemAirshipV3RedstoneAdmin.class, new RenderItemAirshipV3RedstoneAdmin(VCRender));
		
		registerRender(EntityItemAirshipV3GoldNormal.class, new RenderItemAirshipV3GoldNormal(VCRender));
		registerRender(EntityItemAirshipV3GoldBlack.class, new RenderItemAirshipV3GoldBlack(VCRender));
		registerRender(EntityItemAirshipV3GoldBlue.class, new RenderItemAirshipV3GoldBlue(VCRender));
		registerRender(EntityItemAirshipV3GoldBrown.class, new RenderItemAirshipV3GoldBrown(VCRender));
		registerRender(EntityItemAirshipV3GoldCyan.class, new RenderItemAirshipV3GoldCyan(VCRender));
		registerRender(EntityItemAirshipV3GoldGray.class, new RenderItemAirshipV3GoldGray(VCRender));
		registerRender(EntityItemAirshipV3GoldGreen.class, new RenderItemAirshipV3GoldGreen(VCRender));
		registerRender(EntityItemAirshipV3GoldLightBlue.class, new RenderItemAirshipV3GoldLightBlue(VCRender));
		registerRender(EntityItemAirshipV3GoldLightGray.class, new RenderItemAirshipV3GoldLightGray(VCRender));
		registerRender(EntityItemAirshipV3GoldLime.class, new RenderItemAirshipV3GoldLime(VCRender));
		registerRender(EntityItemAirshipV3GoldMagenta.class, new RenderItemAirshipV3GoldMagenta(VCRender));
		registerRender(EntityItemAirshipV3GoldOrange.class, new RenderItemAirshipV3GoldOrange(VCRender));
		registerRender(EntityItemAirshipV3GoldPink.class, new RenderItemAirshipV3GoldPink(VCRender));
		registerRender(EntityItemAirshipV3GoldPurple.class, new RenderItemAirshipV3GoldPurple(VCRender));
		registerRender(EntityItemAirshipV3GoldRed.class, new RenderItemAirshipV3GoldRed(VCRender));
		registerRender(EntityItemAirshipV3GoldWhite.class, new RenderItemAirshipV3GoldWhite(VCRender));
		registerRender(EntityItemAirshipV3GoldYellow.class, new RenderItemAirshipV3GoldYellow(VCRender));
		registerRender(EntityItemAirshipV3GoldAdmin.class, new RenderItemAirshipV3GoldAdmin(VCRender));
		
		registerRender(EntityItemAirshipV3LapisLazuliNormal.class, new RenderItemAirshipV3LapisLazuliNormal(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliBlack.class, new RenderItemAirshipV3LapisLazuliBlack(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliBlue.class, new RenderItemAirshipV3LapisLazuliBlue(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliBrown.class, new RenderItemAirshipV3LapisLazuliBrown(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliCyan.class, new RenderItemAirshipV3LapisLazuliCyan(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliGray.class, new RenderItemAirshipV3LapisLazuliGray(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliGreen.class, new RenderItemAirshipV3LapisLazuliGreen(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliLightBlue.class, new RenderItemAirshipV3LapisLazuliLightBlue(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliLightGray.class, new RenderItemAirshipV3LapisLazuliLightGray(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliLime.class, new RenderItemAirshipV3LapisLazuliLime(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliMagenta.class, new RenderItemAirshipV3LapisLazuliMagenta(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliOrange.class, new RenderItemAirshipV3LapisLazuliOrange(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliPink.class, new RenderItemAirshipV3LapisLazuliPink(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliPurple.class, new RenderItemAirshipV3LapisLazuliPurple(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliRed.class, new RenderItemAirshipV3LapisLazuliRed(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliWhite.class, new RenderItemAirshipV3LapisLazuliWhite(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliYellow.class, new RenderItemAirshipV3LapisLazuliYellow(VCRender));
		registerRender(EntityItemAirshipV3LapisLazuliAdmin.class, new RenderItemAirshipV3LapisLazuliAdmin(VCRender));
		
		registerRender(EntityItemAirshipV3ObsidianNormal.class, new RenderItemAirshipV3ObsidianNormal(VCRender));
		registerRender(EntityItemAirshipV3ObsidianBlack.class, new RenderItemAirshipV3ObsidianBlack(VCRender));
		registerRender(EntityItemAirshipV3ObsidianBlue.class, new RenderItemAirshipV3ObsidianBlue(VCRender));
		registerRender(EntityItemAirshipV3ObsidianBrown.class, new RenderItemAirshipV3ObsidianBrown(VCRender));
		registerRender(EntityItemAirshipV3ObsidianCyan.class, new RenderItemAirshipV3ObsidianCyan(VCRender));
		registerRender(EntityItemAirshipV3ObsidianGray.class, new RenderItemAirshipV3ObsidianGray(VCRender));
		registerRender(EntityItemAirshipV3ObsidianGreen.class, new RenderItemAirshipV3ObsidianGreen(VCRender));
		registerRender(EntityItemAirshipV3ObsidianLightBlue.class, new RenderItemAirshipV3ObsidianLightBlue(VCRender));
		registerRender(EntityItemAirshipV3ObsidianLightGray.class, new RenderItemAirshipV3ObsidianLightGray(VCRender));
		registerRender(EntityItemAirshipV3ObsidianLime.class, new RenderItemAirshipV3ObsidianLime(VCRender));
		registerRender(EntityItemAirshipV3ObsidianMagenta.class, new RenderItemAirshipV3ObsidianMagenta(VCRender));
		registerRender(EntityItemAirshipV3ObsidianOrange.class, new RenderItemAirshipV3ObsidianOrange(VCRender));
		registerRender(EntityItemAirshipV3ObsidianPink.class, new RenderItemAirshipV3ObsidianPink(VCRender));
		registerRender(EntityItemAirshipV3ObsidianPurple.class, new RenderItemAirshipV3ObsidianPurple(VCRender));
		registerRender(EntityItemAirshipV3ObsidianRed.class, new RenderItemAirshipV3ObsidianRed(VCRender));
		registerRender(EntityItemAirshipV3ObsidianWhite.class, new RenderItemAirshipV3ObsidianWhite(VCRender));
		registerRender(EntityItemAirshipV3ObsidianYellow.class, new RenderItemAirshipV3ObsidianYellow(VCRender));
		registerRender(EntityItemAirshipV3ObsidianAdmin.class, new RenderItemAirshipV3ObsidianAdmin(VCRender));
		
		registerRender(EntityItemAirshipV3DiamondNormal.class, new RenderItemAirshipV3DiamondNormal(VCRender));
		registerRender(EntityItemAirshipV3DiamondBlack.class, new RenderItemAirshipV3DiamondBlack(VCRender));
		registerRender(EntityItemAirshipV3DiamondBlue.class, new RenderItemAirshipV3DiamondBlue(VCRender));
		registerRender(EntityItemAirshipV3DiamondBrown.class, new RenderItemAirshipV3DiamondBrown(VCRender));
		registerRender(EntityItemAirshipV3DiamondCyan.class, new RenderItemAirshipV3DiamondCyan(VCRender));
		registerRender(EntityItemAirshipV3DiamondGray.class, new RenderItemAirshipV3DiamondGray(VCRender));
		registerRender(EntityItemAirshipV3DiamondGreen.class, new RenderItemAirshipV3DiamondGreen(VCRender));
		registerRender(EntityItemAirshipV3DiamondLightBlue.class, new RenderItemAirshipV3DiamondLightBlue(VCRender));
		registerRender(EntityItemAirshipV3DiamondLightGray.class, new RenderItemAirshipV3DiamondLightGray(VCRender));
		registerRender(EntityItemAirshipV3DiamondLime.class, new RenderItemAirshipV3DiamondLime(VCRender));
		registerRender(EntityItemAirshipV3DiamondMagenta.class, new RenderItemAirshipV3DiamondMagenta(VCRender));
		registerRender(EntityItemAirshipV3DiamondOrange.class, new RenderItemAirshipV3DiamondOrange(VCRender));
		registerRender(EntityItemAirshipV3DiamondPink.class, new RenderItemAirshipV3DiamondPink(VCRender));
		registerRender(EntityItemAirshipV3DiamondPurple.class, new RenderItemAirshipV3DiamondPurple(VCRender));
		registerRender(EntityItemAirshipV3DiamondRed.class, new RenderItemAirshipV3DiamondRed(VCRender));
		registerRender(EntityItemAirshipV3DiamondWhite.class, new RenderItemAirshipV3DiamondWhite(VCRender));
		registerRender(EntityItemAirshipV3DiamondYellow.class, new RenderItemAirshipV3DiamondYellow(VCRender));
		registerRender(EntityItemAirshipV3DiamondAdmin.class, new RenderItemAirshipV3DiamondAdmin(VCRender));
		
		registerRender(EntityItemAirshipV3EmeraldNormal.class, new RenderItemAirshipV3EmeraldNormal(VCRender));
		registerRender(EntityItemAirshipV3EmeraldBlack.class, new RenderItemAirshipV3EmeraldBlack(VCRender));
		registerRender(EntityItemAirshipV3EmeraldBlue.class, new RenderItemAirshipV3EmeraldBlue(VCRender));
		registerRender(EntityItemAirshipV3EmeraldBrown.class, new RenderItemAirshipV3EmeraldBrown(VCRender));
		registerRender(EntityItemAirshipV3EmeraldCyan.class, new RenderItemAirshipV3EmeraldCyan(VCRender));
		registerRender(EntityItemAirshipV3EmeraldGray.class, new RenderItemAirshipV3EmeraldGray(VCRender));
		registerRender(EntityItemAirshipV3EmeraldGreen.class, new RenderItemAirshipV3EmeraldGreen(VCRender));
		registerRender(EntityItemAirshipV3EmeraldLightBlue.class, new RenderItemAirshipV3EmeraldLightBlue(VCRender));
		registerRender(EntityItemAirshipV3EmeraldLightGray.class, new RenderItemAirshipV3EmeraldLightGray(VCRender));
		registerRender(EntityItemAirshipV3EmeraldLime.class, new RenderItemAirshipV3EmeraldLime(VCRender));
		registerRender(EntityItemAirshipV3EmeraldMagenta.class, new RenderItemAirshipV3EmeraldMagenta(VCRender));
		registerRender(EntityItemAirshipV3EmeraldOrange.class, new RenderItemAirshipV3EmeraldOrange(VCRender));
		registerRender(EntityItemAirshipV3EmeraldPink.class, new RenderItemAirshipV3EmeraldPink(VCRender));
		registerRender(EntityItemAirshipV3EmeraldPurple.class, new RenderItemAirshipV3EmeraldPurple(VCRender));
		registerRender(EntityItemAirshipV3EmeraldRed.class, new RenderItemAirshipV3EmeraldRed(VCRender));
		registerRender(EntityItemAirshipV3EmeraldWhite.class, new RenderItemAirshipV3EmeraldWhite(VCRender));
		registerRender(EntityItemAirshipV3EmeraldYellow.class, new RenderItemAirshipV3EmeraldYellow(VCRender));
		registerRender(EntityItemAirshipV3EmeraldAdmin.class, new RenderItemAirshipV3EmeraldAdmin(VCRender));
		
		//===========================================================================
		
		registerRender(EntityAirshipV3Wood0Normal.class, new RenderAirshipV3Wood0Normal(VCRender));
		registerRender(EntityAirshipV3Wood0Black.class, new RenderAirshipV3Wood0Black(VCRender));
		registerRender(EntityAirshipV3Wood0Blue.class, new RenderAirshipV3Wood0Blue(VCRender));
		registerRender(EntityAirshipV3Wood0Brown.class, new RenderAirshipV3Wood0Brown(VCRender));
		registerRender(EntityAirshipV3Wood0Cyan.class, new RenderAirshipV3Wood0Cyan(VCRender));
		registerRender(EntityAirshipV3Wood0Gray.class, new RenderAirshipV3Wood0Gray(VCRender));
		registerRender(EntityAirshipV3Wood0Green.class, new RenderAirshipV3Wood0Green(VCRender));
		registerRender(EntityAirshipV3Wood0LightBlue.class, new RenderAirshipV3Wood0LightBlue(VCRender));
		registerRender(EntityAirshipV3Wood0LightGray.class, new RenderAirshipV3Wood0LightGray(VCRender));
		registerRender(EntityAirshipV3Wood0Lime.class, new RenderAirshipV3Wood0Lime(VCRender));
		registerRender(EntityAirshipV3Wood0Magenta.class, new RenderAirshipV3Wood0Magenta(VCRender));
		registerRender(EntityAirshipV3Wood0Orange.class, new RenderAirshipV3Wood0Orange(VCRender));
		registerRender(EntityAirshipV3Wood0Pink.class, new RenderAirshipV3Wood0Pink(VCRender));
		registerRender(EntityAirshipV3Wood0Purple.class, new RenderAirshipV3Wood0Purple(VCRender));
		registerRender(EntityAirshipV3Wood0Red.class, new RenderAirshipV3Wood0Red(VCRender));
		registerRender(EntityAirshipV3Wood0White.class, new RenderAirshipV3Wood0White(VCRender));
		registerRender(EntityAirshipV3Wood0Yellow.class, new RenderAirshipV3Wood0Yellow(VCRender));
		registerRender(EntityAirshipV3Wood0Admin.class, new RenderAirshipV3Wood0Admin(VCRender));
		
		registerRender(EntityAirshipV3IronNormal.class, new RenderAirshipV3IronNormal(VCRender));
		registerRender(EntityAirshipV3IronBlack.class, new RenderAirshipV3IronBlack(VCRender));
		registerRender(EntityAirshipV3IronBlue.class, new RenderAirshipV3IronBlue(VCRender));
		registerRender(EntityAirshipV3IronBrown.class, new RenderAirshipV3IronBrown(VCRender));
		registerRender(EntityAirshipV3IronCyan.class, new RenderAirshipV3IronCyan(VCRender));
		registerRender(EntityAirshipV3IronGray.class, new RenderAirshipV3IronGray(VCRender));
		registerRender(EntityAirshipV3IronGreen.class, new RenderAirshipV3IronGreen(VCRender));
		registerRender(EntityAirshipV3IronLightBlue.class, new RenderAirshipV3IronLightBlue(VCRender));
		registerRender(EntityAirshipV3IronLightGray.class, new RenderAirshipV3IronLightGray(VCRender));
		registerRender(EntityAirshipV3IronLime.class, new RenderAirshipV3IronLime(VCRender));
		registerRender(EntityAirshipV3IronMagenta.class, new RenderAirshipV3IronMagenta(VCRender));
		registerRender(EntityAirshipV3IronOrange.class, new RenderAirshipV3IronOrange(VCRender));
		registerRender(EntityAirshipV3IronPink.class, new RenderAirshipV3IronPink(VCRender));
		registerRender(EntityAirshipV3IronPurple.class, new RenderAirshipV3IronPurple(VCRender));
		registerRender(EntityAirshipV3IronRed.class, new RenderAirshipV3IronRed(VCRender));
		registerRender(EntityAirshipV3IronWhite.class, new RenderAirshipV3IronWhite(VCRender));
		registerRender(EntityAirshipV3IronYellow.class, new RenderAirshipV3IronYellow(VCRender));
		registerRender(EntityAirshipV3IronAdmin.class, new RenderAirshipV3IronAdmin(VCRender));
		
		registerRender(EntityAirshipV3RedstoneNormal.class, new RenderAirshipV3RedstoneNormal(VCRender));
		registerRender(EntityAirshipV3RedstoneBlack.class, new RenderAirshipV3RedstoneBlack(VCRender));
		registerRender(EntityAirshipV3RedstoneBlue.class, new RenderAirshipV3RedstoneBlue(VCRender));
		registerRender(EntityAirshipV3RedstoneBrown.class, new RenderAirshipV3RedstoneBrown(VCRender));
		registerRender(EntityAirshipV3RedstoneCyan.class, new RenderAirshipV3RedstoneCyan(VCRender));
		registerRender(EntityAirshipV3RedstoneGray.class, new RenderAirshipV3RedstoneGray(VCRender));
		registerRender(EntityAirshipV3RedstoneGreen.class, new RenderAirshipV3RedstoneGreen(VCRender));
		registerRender(EntityAirshipV3RedstoneLightBlue.class, new RenderAirshipV3RedstoneLightBlue(VCRender));
		registerRender(EntityAirshipV3RedstoneLightGray.class, new RenderAirshipV3RedstoneLightGray(VCRender));
		registerRender(EntityAirshipV3RedstoneLime.class, new RenderAirshipV3RedstoneLime(VCRender));
		registerRender(EntityAirshipV3RedstoneMagenta.class, new RenderAirshipV3RedstoneMagenta(VCRender));
		registerRender(EntityAirshipV3RedstoneOrange.class, new RenderAirshipV3RedstoneOrange(VCRender));
		registerRender(EntityAirshipV3RedstonePink.class, new RenderAirshipV3RedstonePink(VCRender));
		registerRender(EntityAirshipV3RedstonePurple.class, new RenderAirshipV3RedstonePurple(VCRender));
		registerRender(EntityAirshipV3RedstoneRed.class, new RenderAirshipV3RedstoneRed(VCRender));
		registerRender(EntityAirshipV3RedstoneWhite.class, new RenderAirshipV3RedstoneWhite(VCRender));
		registerRender(EntityAirshipV3RedstoneYellow.class, new RenderAirshipV3RedstoneYellow(VCRender));
		registerRender(EntityAirshipV3RedstoneAdmin.class, new RenderAirshipV3RedstoneAdmin(VCRender));
		
		registerRender(EntityAirshipV3GoldNormal.class, new RenderAirshipV3GoldNormal(VCRender));
		registerRender(EntityAirshipV3GoldBlack.class, new RenderAirshipV3GoldBlack(VCRender));
		registerRender(EntityAirshipV3GoldBlue.class, new RenderAirshipV3GoldBlue(VCRender));
		registerRender(EntityAirshipV3GoldBrown.class, new RenderAirshipV3GoldBrown(VCRender));
		registerRender(EntityAirshipV3GoldCyan.class, new RenderAirshipV3GoldCyan(VCRender));
		registerRender(EntityAirshipV3GoldGray.class, new RenderAirshipV3GoldGray(VCRender));
		registerRender(EntityAirshipV3GoldGreen.class, new RenderAirshipV3GoldGreen(VCRender));
		registerRender(EntityAirshipV3GoldLightBlue.class, new RenderAirshipV3GoldLightBlue(VCRender));
		registerRender(EntityAirshipV3GoldLightGray.class, new RenderAirshipV3GoldLightGray(VCRender));
		registerRender(EntityAirshipV3GoldLime.class, new RenderAirshipV3GoldLime(VCRender));
		registerRender(EntityAirshipV3GoldMagenta.class, new RenderAirshipV3GoldMagenta(VCRender));
		registerRender(EntityAirshipV3GoldOrange.class, new RenderAirshipV3GoldOrange(VCRender));
		registerRender(EntityAirshipV3GoldPink.class, new RenderAirshipV3GoldPink(VCRender));
		registerRender(EntityAirshipV3GoldPurple.class, new RenderAirshipV3GoldPurple(VCRender));
		registerRender(EntityAirshipV3GoldRed.class, new RenderAirshipV3GoldRed(VCRender));
		registerRender(EntityAirshipV3GoldWhite.class, new RenderAirshipV3GoldWhite(VCRender));
		registerRender(EntityAirshipV3GoldYellow.class, new RenderAirshipV3GoldYellow(VCRender));
		registerRender(EntityAirshipV3GoldAdmin.class, new RenderAirshipV3GoldAdmin(VCRender));
		
		registerRender(EntityAirshipV3LapisLazuliNormal.class, new RenderAirshipV3LapisLazuliNormal(VCRender));
		registerRender(EntityAirshipV3LapisLazuliBlack.class, new RenderAirshipV3LapisLazuliBlack(VCRender));
		registerRender(EntityAirshipV3LapisLazuliBlue.class, new RenderAirshipV3LapisLazuliBlue(VCRender));
		registerRender(EntityAirshipV3LapisLazuliBrown.class, new RenderAirshipV3LapisLazuliBrown(VCRender));
		registerRender(EntityAirshipV3LapisLazuliCyan.class, new RenderAirshipV3LapisLazuliCyan(VCRender));
		registerRender(EntityAirshipV3LapisLazuliGray.class, new RenderAirshipV3LapisLazuliGray(VCRender));
		registerRender(EntityAirshipV3LapisLazuliGreen.class, new RenderAirshipV3LapisLazuliGreen(VCRender));
		registerRender(EntityAirshipV3LapisLazuliLightBlue.class, new RenderAirshipV3LapisLazuliLightBlue(VCRender));
		registerRender(EntityAirshipV3LapisLazuliLightGray.class, new RenderAirshipV3LapisLazuliLightGray(VCRender));
		registerRender(EntityAirshipV3LapisLazuliLime.class, new RenderAirshipV3LapisLazuliLime(VCRender));
		registerRender(EntityAirshipV3LapisLazuliMagenta.class, new RenderAirshipV3LapisLazuliMagenta(VCRender));
		registerRender(EntityAirshipV3LapisLazuliOrange.class, new RenderAirshipV3LapisLazuliOrange(VCRender));
		registerRender(EntityAirshipV3LapisLazuliPink.class, new RenderAirshipV3LapisLazuliPink(VCRender));
		registerRender(EntityAirshipV3LapisLazuliPurple.class, new RenderAirshipV3LapisLazuliPurple(VCRender));
		registerRender(EntityAirshipV3LapisLazuliRed.class, new RenderAirshipV3LapisLazuliRed(VCRender));
		registerRender(EntityAirshipV3LapisLazuliWhite.class, new RenderAirshipV3LapisLazuliWhite(VCRender));
		registerRender(EntityAirshipV3LapisLazuliYellow.class, new RenderAirshipV3LapisLazuliYellow(VCRender));
		registerRender(EntityAirshipV3LapisLazuliAdmin.class, new RenderAirshipV3LapisLazuliAdmin(VCRender));
		
		registerRender(EntityAirshipV3ObsidianNormal.class, new RenderAirshipV3ObsidianNormal(VCRender));
		registerRender(EntityAirshipV3ObsidianBlack.class, new RenderAirshipV3ObsidianBlack(VCRender));
		registerRender(EntityAirshipV3ObsidianBlue.class, new RenderAirshipV3ObsidianBlue(VCRender));
		registerRender(EntityAirshipV3ObsidianBrown.class, new RenderAirshipV3ObsidianBrown(VCRender));
		registerRender(EntityAirshipV3ObsidianCyan.class, new RenderAirshipV3ObsidianCyan(VCRender));
		registerRender(EntityAirshipV3ObsidianGray.class, new RenderAirshipV3ObsidianGray(VCRender));
		registerRender(EntityAirshipV3ObsidianGreen.class, new RenderAirshipV3ObsidianGreen(VCRender));
		registerRender(EntityAirshipV3ObsidianLightBlue.class, new RenderAirshipV3ObsidianLightBlue(VCRender));
		registerRender(EntityAirshipV3ObsidianLightGray.class, new RenderAirshipV3ObsidianLightGray(VCRender));
		registerRender(EntityAirshipV3ObsidianLime.class, new RenderAirshipV3ObsidianLime(VCRender));
		registerRender(EntityAirshipV3ObsidianMagenta.class, new RenderAirshipV3ObsidianMagenta(VCRender));
		registerRender(EntityAirshipV3ObsidianOrange.class, new RenderAirshipV3ObsidianOrange(VCRender));
		registerRender(EntityAirshipV3ObsidianPink.class, new RenderAirshipV3ObsidianPink(VCRender));
		registerRender(EntityAirshipV3ObsidianPurple.class, new RenderAirshipV3ObsidianPurple(VCRender));
		registerRender(EntityAirshipV3ObsidianRed.class, new RenderAirshipV3ObsidianRed(VCRender));
		registerRender(EntityAirshipV3ObsidianWhite.class, new RenderAirshipV3ObsidianWhite(VCRender));
		registerRender(EntityAirshipV3ObsidianYellow.class, new RenderAirshipV3ObsidianYellow(VCRender));
		registerRender(EntityAirshipV3ObsidianAdmin.class, new RenderAirshipV3ObsidianAdmin(VCRender));
		
		registerRender(EntityAirshipV3DiamondNormal.class, new RenderAirshipV3DiamondNormal(VCRender));
		registerRender(EntityAirshipV3DiamondBlack.class, new RenderAirshipV3DiamondBlack(VCRender));
		registerRender(EntityAirshipV3DiamondBlue.class, new RenderAirshipV3DiamondBlue(VCRender));
		registerRender(EntityAirshipV3DiamondBrown.class, new RenderAirshipV3DiamondBrown(VCRender));
		registerRender(EntityAirshipV3DiamondCyan.class, new RenderAirshipV3DiamondCyan(VCRender));
		registerRender(EntityAirshipV3DiamondGray.class, new RenderAirshipV3DiamondGray(VCRender));
		registerRender(EntityAirshipV3DiamondGreen.class, new RenderAirshipV3DiamondGreen(VCRender));
		registerRender(EntityAirshipV3DiamondLightBlue.class, new RenderAirshipV3DiamondLightBlue(VCRender));
		registerRender(EntityAirshipV3DiamondLightGray.class, new RenderAirshipV3DiamondLightGray(VCRender));
		registerRender(EntityAirshipV3DiamondLime.class, new RenderAirshipV3DiamondLime(VCRender));
		registerRender(EntityAirshipV3DiamondMagenta.class, new RenderAirshipV3DiamondMagenta(VCRender));
		registerRender(EntityAirshipV3DiamondOrange.class, new RenderAirshipV3DiamondOrange(VCRender));
		registerRender(EntityAirshipV3DiamondPink.class, new RenderAirshipV3DiamondPink(VCRender));
		registerRender(EntityAirshipV3DiamondPurple.class, new RenderAirshipV3DiamondPurple(VCRender));
		registerRender(EntityAirshipV3DiamondRed.class, new RenderAirshipV3DiamondRed(VCRender));
		registerRender(EntityAirshipV3DiamondWhite.class, new RenderAirshipV3DiamondWhite(VCRender));
		registerRender(EntityAirshipV3DiamondYellow.class, new RenderAirshipV3DiamondYellow(VCRender));
		registerRender(EntityAirshipV3DiamondAdmin.class, new RenderAirshipV3DiamondAdmin(VCRender));
		
		registerRender(EntityAirshipV3EmeraldNormal.class, new RenderAirshipV3EmeraldNormal(VCRender));
		registerRender(EntityAirshipV3EmeraldBlack.class, new RenderAirshipV3EmeraldBlack(VCRender));
		registerRender(EntityAirshipV3EmeraldBlue.class, new RenderAirshipV3EmeraldBlue(VCRender));
		registerRender(EntityAirshipV3EmeraldBrown.class, new RenderAirshipV3EmeraldBrown(VCRender));
		registerRender(EntityAirshipV3EmeraldCyan.class, new RenderAirshipV3EmeraldCyan(VCRender));
		registerRender(EntityAirshipV3EmeraldGray.class, new RenderAirshipV3EmeraldGray(VCRender));
		registerRender(EntityAirshipV3EmeraldGreen.class, new RenderAirshipV3EmeraldGreen(VCRender));
		registerRender(EntityAirshipV3EmeraldLightBlue.class, new RenderAirshipV3EmeraldLightBlue(VCRender));
		registerRender(EntityAirshipV3EmeraldLightGray.class, new RenderAirshipV3EmeraldLightGray(VCRender));
		registerRender(EntityAirshipV3EmeraldLime.class, new RenderAirshipV3EmeraldLime(VCRender));
		registerRender(EntityAirshipV3EmeraldMagenta.class, new RenderAirshipV3EmeraldMagenta(VCRender));
		registerRender(EntityAirshipV3EmeraldOrange.class, new RenderAirshipV3EmeraldOrange(VCRender));
		registerRender(EntityAirshipV3EmeraldPink.class, new RenderAirshipV3EmeraldPink(VCRender));
		registerRender(EntityAirshipV3EmeraldPurple.class, new RenderAirshipV3EmeraldPurple(VCRender));
		registerRender(EntityAirshipV3EmeraldRed.class, new RenderAirshipV3EmeraldRed(VCRender));
		registerRender(EntityAirshipV3EmeraldWhite.class, new RenderAirshipV3EmeraldWhite(VCRender));
		registerRender(EntityAirshipV3EmeraldYellow.class, new RenderAirshipV3EmeraldYellow(VCRender));
		registerRender(EntityAirshipV3EmeraldAdmin.class, new RenderAirshipV3EmeraldAdmin(VCRender));
		
	}
	
	public static void registerRender(Class<? extends Entity> classIn, Render<? extends Entity> renderItem)
	{
		RenderingRegistry.registerEntityRenderingHandler(classIn, renderItem);
	}
}
