package com.viesis.viescraft.client;

import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.client.registry.RenderingRegistry;

import com.viesis.viescraft.api.ItemsVC;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.diamond.RenderAirshipV2DiamondYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.emerald.RenderAirshipV2EmeraldYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.gold.RenderAirshipV2GoldYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.iron.RenderAirshipV2IronYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.lapislazuli.RenderAirshipV2LapisLazuliYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianPink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianPurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.obsidian.RenderAirshipV2ObsidianYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneAdmin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneBlack;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneBrown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneCyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneGreen;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneLightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneLightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneLime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneMagenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneNormal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneOrange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstonePink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstonePurple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneRed;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneWhite;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.redstone.RenderAirshipV2RedstoneYellow;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Admin;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Black;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Blue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Brown;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Cyan;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Gray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Green;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0LightBlue;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0LightGray;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Lime;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Magenta;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Normal;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Orange;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Pink;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Purple;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Red;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0White;
import com.viesis.viescraft.client.entity.render.airshipcolors.v2.wood0.RenderAirshipV2Wood0Yellow;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondBlack;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondBrown;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondCyan;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondGreen;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondLime;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondNormal;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondOrange;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondPink;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondPurple;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondRed;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondWhite;
import com.viesis.viescraft.client.entity.render.projectile.v2.diamond.RenderItemAirshipV2DiamondYellow;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldBlack;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldBrown;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldCyan;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldGreen;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldLime;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldNormal;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldOrange;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldPink;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldPurple;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldRed;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldWhite;
import com.viesis.viescraft.client.entity.render.projectile.v2.emerald.RenderItemAirshipV2EmeraldYellow;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldBlack;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldBrown;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldCyan;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldGreen;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldLime;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldNormal;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldOrange;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldPink;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldPurple;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldRed;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldWhite;
import com.viesis.viescraft.client.entity.render.projectile.v2.gold.RenderItemAirshipV2GoldYellow;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronBlack;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronBrown;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronCyan;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronGreen;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronLime;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronNormal;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronOrange;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronPink;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronPurple;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronRed;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronWhite;
import com.viesis.viescraft.client.entity.render.projectile.v2.iron.RenderItemAirshipV2IronYellow;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliBlack;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliBrown;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliCyan;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliGreen;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliLime;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliNormal;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliOrange;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliPink;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliPurple;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliRed;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliWhite;
import com.viesis.viescraft.client.entity.render.projectile.v2.lapislazuli.RenderItemAirshipV2LapisLazuliYellow;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianBlack;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianBrown;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianCyan;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianGreen;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianLime;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianNormal;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianOrange;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianPink;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianPurple;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianRed;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianWhite;
import com.viesis.viescraft.client.entity.render.projectile.v2.obsidian.RenderItemAirshipV2ObsidianYellow;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneAdmin;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneBlack;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneBrown;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneCyan;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneGreen;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneLightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneLightGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneLime;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneMagenta;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneNormal;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneOrange;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstonePink;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstonePurple;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneRed;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneWhite;
import com.viesis.viescraft.client.entity.render.projectile.v2.redstone.RenderItemAirshipV2RedstoneYellow;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Admin;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Black;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Blue;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Brown;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Cyan;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Gray;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Green;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0LightBlue;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0LightGray;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Lime;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Magenta;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Normal;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Orange;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Pink;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Purple;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Red;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0White;
import com.viesis.viescraft.client.entity.render.projectile.v2.wood0.RenderItemAirshipV2Wood0Yellow;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondLime;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondPink;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondRed;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v2.diamond.EntityAirshipV2DiamondYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldLime;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldPink;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldRed;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v2.emerald.EntityAirshipV2EmeraldYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldLime;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldPink;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldRed;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v2.gold.EntityAirshipV2GoldYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronLime;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronPink;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronRed;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v2.iron.EntityAirshipV2IronYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliLime;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliPink;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliRed;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v2.lapislazuli.EntityAirshipV2LapisLazuliYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianLime;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianPink;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianPurple;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianRed;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v2.obsidian.EntityAirshipV2ObsidianYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneAdmin;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneBlack;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneBrown;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneCyan;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneGreen;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneLightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneLightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneLime;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneMagenta;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneNormal;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneOrange;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstonePink;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstonePurple;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneRed;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneWhite;
import com.viesis.viescraft.common.entity.airshipcolors.v2.redstone.EntityAirshipV2RedstoneYellow;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Admin;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Black;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Blue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Brown;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Cyan;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Gray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Green;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0LightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0LightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Lime;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Magenta;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Normal;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Orange;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Pink;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Purple;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Red;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0White;
import com.viesis.viescraft.common.entity.airshipcolors.v2.wood0.EntityAirshipV2Wood0Yellow;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondBlack;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondBrown;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondCyan;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondGreen;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondLime;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondNormal;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondOrange;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondPink;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondPurple;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondRed;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondWhite;
import com.viesis.viescraft.common.entity.airshipitems.v2.diamond.EntityItemAirshipV2DiamondYellow;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldBlack;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldBrown;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldCyan;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldGreen;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldLime;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldNormal;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldOrange;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldPink;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldPurple;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldRed;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldWhite;
import com.viesis.viescraft.common.entity.airshipitems.v2.emerald.EntityItemAirshipV2EmeraldYellow;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldBlack;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldBrown;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldCyan;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldGreen;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldLime;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldNormal;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldOrange;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldPink;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldPurple;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldRed;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldWhite;
import com.viesis.viescraft.common.entity.airshipitems.v2.gold.EntityItemAirshipV2GoldYellow;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronBlack;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronBrown;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronCyan;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronGreen;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronLime;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronNormal;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronOrange;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronPink;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronPurple;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronRed;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronWhite;
import com.viesis.viescraft.common.entity.airshipitems.v2.iron.EntityItemAirshipV2IronYellow;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliBlack;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliBrown;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliCyan;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliGreen;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliLime;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliNormal;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliOrange;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliPink;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliPurple;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliRed;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliWhite;
import com.viesis.viescraft.common.entity.airshipitems.v2.lapislazuli.EntityItemAirshipV2LapisLazuliYellow;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianBlack;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianBrown;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianCyan;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianGreen;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianLime;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianNormal;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianOrange;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianPink;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianPurple;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianRed;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianWhite;
import com.viesis.viescraft.common.entity.airshipitems.v2.obsidian.EntityItemAirshipV2ObsidianYellow;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneAdmin;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneBlack;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneBrown;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneCyan;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneGreen;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneLightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneLightGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneLime;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneMagenta;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneNormal;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneOrange;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstonePink;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstonePurple;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneRed;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneWhite;
import com.viesis.viescraft.common.entity.airshipitems.v2.redstone.EntityItemAirshipV2RedstoneYellow;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Admin;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Black;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Blue;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Brown;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Cyan;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Gray;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Green;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0LightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0LightGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Lime;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Magenta;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Normal;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Orange;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Pink;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Purple;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Red;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0White;
import com.viesis.viescraft.common.entity.airshipitems.v2.wood0.EntityItemAirshipV2Wood0Yellow;

public final class InitEntityV2VCRender extends ItemsVC {
	
	public static RenderManager VCRender = Minecraft.getMinecraft().getRenderManager(); 
	
	public static void registerRenders()
	{
		
		registerRender(EntityItemAirshipV2Wood0Normal.class, new RenderItemAirshipV2Wood0Normal(VCRender));
		registerRender(EntityItemAirshipV2Wood0Black.class, new RenderItemAirshipV2Wood0Black(VCRender));
		registerRender(EntityItemAirshipV2Wood0Blue.class, new RenderItemAirshipV2Wood0Blue(VCRender));
		registerRender(EntityItemAirshipV2Wood0Brown.class, new RenderItemAirshipV2Wood0Brown(VCRender));
		registerRender(EntityItemAirshipV2Wood0Cyan.class, new RenderItemAirshipV2Wood0Cyan(VCRender));
		registerRender(EntityItemAirshipV2Wood0Gray.class, new RenderItemAirshipV2Wood0Gray(VCRender));
		registerRender(EntityItemAirshipV2Wood0Green.class, new RenderItemAirshipV2Wood0Green(VCRender));
		registerRender(EntityItemAirshipV2Wood0LightBlue.class, new RenderItemAirshipV2Wood0LightBlue(VCRender));
		registerRender(EntityItemAirshipV2Wood0LightGray.class, new RenderItemAirshipV2Wood0LightGray(VCRender));
		registerRender(EntityItemAirshipV2Wood0Lime.class, new RenderItemAirshipV2Wood0Lime(VCRender));
		registerRender(EntityItemAirshipV2Wood0Magenta.class, new RenderItemAirshipV2Wood0Magenta(VCRender));
		registerRender(EntityItemAirshipV2Wood0Orange.class, new RenderItemAirshipV2Wood0Orange(VCRender));
		registerRender(EntityItemAirshipV2Wood0Pink.class, new RenderItemAirshipV2Wood0Pink(VCRender));
		registerRender(EntityItemAirshipV2Wood0Purple.class, new RenderItemAirshipV2Wood0Purple(VCRender));
		registerRender(EntityItemAirshipV2Wood0Red.class, new RenderItemAirshipV2Wood0Red(VCRender));
		registerRender(EntityItemAirshipV2Wood0White.class, new RenderItemAirshipV2Wood0White(VCRender));
		registerRender(EntityItemAirshipV2Wood0Yellow.class, new RenderItemAirshipV2Wood0Yellow(VCRender));
		registerRender(EntityItemAirshipV2Wood0Admin.class, new RenderItemAirshipV2Wood0Admin(VCRender));
		
		registerRender(EntityItemAirshipV2IronNormal.class, new RenderItemAirshipV2IronNormal(VCRender));
		registerRender(EntityItemAirshipV2IronBlack.class, new RenderItemAirshipV2IronBlack(VCRender));
		registerRender(EntityItemAirshipV2IronBlue.class, new RenderItemAirshipV2IronBlue(VCRender));
		registerRender(EntityItemAirshipV2IronBrown.class, new RenderItemAirshipV2IronBrown(VCRender));
		registerRender(EntityItemAirshipV2IronCyan.class, new RenderItemAirshipV2IronCyan(VCRender));
		registerRender(EntityItemAirshipV2IronGray.class, new RenderItemAirshipV2IronGray(VCRender));
		registerRender(EntityItemAirshipV2IronGreen.class, new RenderItemAirshipV2IronGreen(VCRender));
		registerRender(EntityItemAirshipV2IronLightBlue.class, new RenderItemAirshipV2IronLightBlue(VCRender));
		registerRender(EntityItemAirshipV2IronLightGray.class, new RenderItemAirshipV2IronLightGray(VCRender));
		registerRender(EntityItemAirshipV2IronLime.class, new RenderItemAirshipV2IronLime(VCRender));
		registerRender(EntityItemAirshipV2IronMagenta.class, new RenderItemAirshipV2IronMagenta(VCRender));
		registerRender(EntityItemAirshipV2IronOrange.class, new RenderItemAirshipV2IronOrange(VCRender));
		registerRender(EntityItemAirshipV2IronPink.class, new RenderItemAirshipV2IronPink(VCRender));
		registerRender(EntityItemAirshipV2IronPurple.class, new RenderItemAirshipV2IronPurple(VCRender));
		registerRender(EntityItemAirshipV2IronRed.class, new RenderItemAirshipV2IronRed(VCRender));
		registerRender(EntityItemAirshipV2IronWhite.class, new RenderItemAirshipV2IronWhite(VCRender));
		registerRender(EntityItemAirshipV2IronYellow.class, new RenderItemAirshipV2IronYellow(VCRender));
		registerRender(EntityItemAirshipV2IronAdmin.class, new RenderItemAirshipV2IronAdmin(VCRender));
		
		registerRender(EntityItemAirshipV2RedstoneNormal.class, new RenderItemAirshipV2RedstoneNormal(VCRender));
		registerRender(EntityItemAirshipV2RedstoneBlack.class, new RenderItemAirshipV2RedstoneBlack(VCRender));
		registerRender(EntityItemAirshipV2RedstoneBlue.class, new RenderItemAirshipV2RedstoneBlue(VCRender));
		registerRender(EntityItemAirshipV2RedstoneBrown.class, new RenderItemAirshipV2RedstoneBrown(VCRender));
		registerRender(EntityItemAirshipV2RedstoneCyan.class, new RenderItemAirshipV2RedstoneCyan(VCRender));
		registerRender(EntityItemAirshipV2RedstoneGray.class, new RenderItemAirshipV2RedstoneGray(VCRender));
		registerRender(EntityItemAirshipV2RedstoneGreen.class, new RenderItemAirshipV2RedstoneGreen(VCRender));
		registerRender(EntityItemAirshipV2RedstoneLightBlue.class, new RenderItemAirshipV2RedstoneLightBlue(VCRender));
		registerRender(EntityItemAirshipV2RedstoneLightGray.class, new RenderItemAirshipV2RedstoneLightGray(VCRender));
		registerRender(EntityItemAirshipV2RedstoneLime.class, new RenderItemAirshipV2RedstoneLime(VCRender));
		registerRender(EntityItemAirshipV2RedstoneMagenta.class, new RenderItemAirshipV2RedstoneMagenta(VCRender));
		registerRender(EntityItemAirshipV2RedstoneOrange.class, new RenderItemAirshipV2RedstoneOrange(VCRender));
		registerRender(EntityItemAirshipV2RedstonePink.class, new RenderItemAirshipV2RedstonePink(VCRender));
		registerRender(EntityItemAirshipV2RedstonePurple.class, new RenderItemAirshipV2RedstonePurple(VCRender));
		registerRender(EntityItemAirshipV2RedstoneRed.class, new RenderItemAirshipV2RedstoneRed(VCRender));
		registerRender(EntityItemAirshipV2RedstoneWhite.class, new RenderItemAirshipV2RedstoneWhite(VCRender));
		registerRender(EntityItemAirshipV2RedstoneYellow.class, new RenderItemAirshipV2RedstoneYellow(VCRender));
		registerRender(EntityItemAirshipV2RedstoneAdmin.class, new RenderItemAirshipV2RedstoneAdmin(VCRender));
		
		registerRender(EntityItemAirshipV2GoldNormal.class, new RenderItemAirshipV2GoldNormal(VCRender));
		registerRender(EntityItemAirshipV2GoldBlack.class, new RenderItemAirshipV2GoldBlack(VCRender));
		registerRender(EntityItemAirshipV2GoldBlue.class, new RenderItemAirshipV2GoldBlue(VCRender));
		registerRender(EntityItemAirshipV2GoldBrown.class, new RenderItemAirshipV2GoldBrown(VCRender));
		registerRender(EntityItemAirshipV2GoldCyan.class, new RenderItemAirshipV2GoldCyan(VCRender));
		registerRender(EntityItemAirshipV2GoldGray.class, new RenderItemAirshipV2GoldGray(VCRender));
		registerRender(EntityItemAirshipV2GoldGreen.class, new RenderItemAirshipV2GoldGreen(VCRender));
		registerRender(EntityItemAirshipV2GoldLightBlue.class, new RenderItemAirshipV2GoldLightBlue(VCRender));
		registerRender(EntityItemAirshipV2GoldLightGray.class, new RenderItemAirshipV2GoldLightGray(VCRender));
		registerRender(EntityItemAirshipV2GoldLime.class, new RenderItemAirshipV2GoldLime(VCRender));
		registerRender(EntityItemAirshipV2GoldMagenta.class, new RenderItemAirshipV2GoldMagenta(VCRender));
		registerRender(EntityItemAirshipV2GoldOrange.class, new RenderItemAirshipV2GoldOrange(VCRender));
		registerRender(EntityItemAirshipV2GoldPink.class, new RenderItemAirshipV2GoldPink(VCRender));
		registerRender(EntityItemAirshipV2GoldPurple.class, new RenderItemAirshipV2GoldPurple(VCRender));
		registerRender(EntityItemAirshipV2GoldRed.class, new RenderItemAirshipV2GoldRed(VCRender));
		registerRender(EntityItemAirshipV2GoldWhite.class, new RenderItemAirshipV2GoldWhite(VCRender));
		registerRender(EntityItemAirshipV2GoldYellow.class, new RenderItemAirshipV2GoldYellow(VCRender));
		registerRender(EntityItemAirshipV2GoldAdmin.class, new RenderItemAirshipV2GoldAdmin(VCRender));
		
		registerRender(EntityItemAirshipV2LapisLazuliNormal.class, new RenderItemAirshipV2LapisLazuliNormal(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliBlack.class, new RenderItemAirshipV2LapisLazuliBlack(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliBlue.class, new RenderItemAirshipV2LapisLazuliBlue(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliBrown.class, new RenderItemAirshipV2LapisLazuliBrown(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliCyan.class, new RenderItemAirshipV2LapisLazuliCyan(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliGray.class, new RenderItemAirshipV2LapisLazuliGray(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliGreen.class, new RenderItemAirshipV2LapisLazuliGreen(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliLightBlue.class, new RenderItemAirshipV2LapisLazuliLightBlue(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliLightGray.class, new RenderItemAirshipV2LapisLazuliLightGray(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliLime.class, new RenderItemAirshipV2LapisLazuliLime(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliMagenta.class, new RenderItemAirshipV2LapisLazuliMagenta(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliOrange.class, new RenderItemAirshipV2LapisLazuliOrange(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliPink.class, new RenderItemAirshipV2LapisLazuliPink(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliPurple.class, new RenderItemAirshipV2LapisLazuliPurple(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliRed.class, new RenderItemAirshipV2LapisLazuliRed(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliWhite.class, new RenderItemAirshipV2LapisLazuliWhite(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliYellow.class, new RenderItemAirshipV2LapisLazuliYellow(VCRender));
		registerRender(EntityItemAirshipV2LapisLazuliAdmin.class, new RenderItemAirshipV2LapisLazuliAdmin(VCRender));
		
		registerRender(EntityItemAirshipV2ObsidianNormal.class, new RenderItemAirshipV2ObsidianNormal(VCRender));
		registerRender(EntityItemAirshipV2ObsidianBlack.class, new RenderItemAirshipV2ObsidianBlack(VCRender));
		registerRender(EntityItemAirshipV2ObsidianBlue.class, new RenderItemAirshipV2ObsidianBlue(VCRender));
		registerRender(EntityItemAirshipV2ObsidianBrown.class, new RenderItemAirshipV2ObsidianBrown(VCRender));
		registerRender(EntityItemAirshipV2ObsidianCyan.class, new RenderItemAirshipV2ObsidianCyan(VCRender));
		registerRender(EntityItemAirshipV2ObsidianGray.class, new RenderItemAirshipV2ObsidianGray(VCRender));
		registerRender(EntityItemAirshipV2ObsidianGreen.class, new RenderItemAirshipV2ObsidianGreen(VCRender));
		registerRender(EntityItemAirshipV2ObsidianLightBlue.class, new RenderItemAirshipV2ObsidianLightBlue(VCRender));
		registerRender(EntityItemAirshipV2ObsidianLightGray.class, new RenderItemAirshipV2ObsidianLightGray(VCRender));
		registerRender(EntityItemAirshipV2ObsidianLime.class, new RenderItemAirshipV2ObsidianLime(VCRender));
		registerRender(EntityItemAirshipV2ObsidianMagenta.class, new RenderItemAirshipV2ObsidianMagenta(VCRender));
		registerRender(EntityItemAirshipV2ObsidianOrange.class, new RenderItemAirshipV2ObsidianOrange(VCRender));
		registerRender(EntityItemAirshipV2ObsidianPink.class, new RenderItemAirshipV2ObsidianPink(VCRender));
		registerRender(EntityItemAirshipV2ObsidianPurple.class, new RenderItemAirshipV2ObsidianPurple(VCRender));
		registerRender(EntityItemAirshipV2ObsidianRed.class, new RenderItemAirshipV2ObsidianRed(VCRender));
		registerRender(EntityItemAirshipV2ObsidianWhite.class, new RenderItemAirshipV2ObsidianWhite(VCRender));
		registerRender(EntityItemAirshipV2ObsidianYellow.class, new RenderItemAirshipV2ObsidianYellow(VCRender));
		registerRender(EntityItemAirshipV2ObsidianAdmin.class, new RenderItemAirshipV2ObsidianAdmin(VCRender));
		
		registerRender(EntityItemAirshipV2DiamondNormal.class, new RenderItemAirshipV2DiamondNormal(VCRender));
		registerRender(EntityItemAirshipV2DiamondBlack.class, new RenderItemAirshipV2DiamondBlack(VCRender));
		registerRender(EntityItemAirshipV2DiamondBlue.class, new RenderItemAirshipV2DiamondBlue(VCRender));
		registerRender(EntityItemAirshipV2DiamondBrown.class, new RenderItemAirshipV2DiamondBrown(VCRender));
		registerRender(EntityItemAirshipV2DiamondCyan.class, new RenderItemAirshipV2DiamondCyan(VCRender));
		registerRender(EntityItemAirshipV2DiamondGray.class, new RenderItemAirshipV2DiamondGray(VCRender));
		registerRender(EntityItemAirshipV2DiamondGreen.class, new RenderItemAirshipV2DiamondGreen(VCRender));
		registerRender(EntityItemAirshipV2DiamondLightBlue.class, new RenderItemAirshipV2DiamondLightBlue(VCRender));
		registerRender(EntityItemAirshipV2DiamondLightGray.class, new RenderItemAirshipV2DiamondLightGray(VCRender));
		registerRender(EntityItemAirshipV2DiamondLime.class, new RenderItemAirshipV2DiamondLime(VCRender));
		registerRender(EntityItemAirshipV2DiamondMagenta.class, new RenderItemAirshipV2DiamondMagenta(VCRender));
		registerRender(EntityItemAirshipV2DiamondOrange.class, new RenderItemAirshipV2DiamondOrange(VCRender));
		registerRender(EntityItemAirshipV2DiamondPink.class, new RenderItemAirshipV2DiamondPink(VCRender));
		registerRender(EntityItemAirshipV2DiamondPurple.class, new RenderItemAirshipV2DiamondPurple(VCRender));
		registerRender(EntityItemAirshipV2DiamondRed.class, new RenderItemAirshipV2DiamondRed(VCRender));
		registerRender(EntityItemAirshipV2DiamondWhite.class, new RenderItemAirshipV2DiamondWhite(VCRender));
		registerRender(EntityItemAirshipV2DiamondYellow.class, new RenderItemAirshipV2DiamondYellow(VCRender));
		registerRender(EntityItemAirshipV2DiamondAdmin.class, new RenderItemAirshipV2DiamondAdmin(VCRender));
		
		registerRender(EntityItemAirshipV2EmeraldNormal.class, new RenderItemAirshipV2EmeraldNormal(VCRender));
		registerRender(EntityItemAirshipV2EmeraldBlack.class, new RenderItemAirshipV2EmeraldBlack(VCRender));
		registerRender(EntityItemAirshipV2EmeraldBlue.class, new RenderItemAirshipV2EmeraldBlue(VCRender));
		registerRender(EntityItemAirshipV2EmeraldBrown.class, new RenderItemAirshipV2EmeraldBrown(VCRender));
		registerRender(EntityItemAirshipV2EmeraldCyan.class, new RenderItemAirshipV2EmeraldCyan(VCRender));
		registerRender(EntityItemAirshipV2EmeraldGray.class, new RenderItemAirshipV2EmeraldGray(VCRender));
		registerRender(EntityItemAirshipV2EmeraldGreen.class, new RenderItemAirshipV2EmeraldGreen(VCRender));
		registerRender(EntityItemAirshipV2EmeraldLightBlue.class, new RenderItemAirshipV2EmeraldLightBlue(VCRender));
		registerRender(EntityItemAirshipV2EmeraldLightGray.class, new RenderItemAirshipV2EmeraldLightGray(VCRender));
		registerRender(EntityItemAirshipV2EmeraldLime.class, new RenderItemAirshipV2EmeraldLime(VCRender));
		registerRender(EntityItemAirshipV2EmeraldMagenta.class, new RenderItemAirshipV2EmeraldMagenta(VCRender));
		registerRender(EntityItemAirshipV2EmeraldOrange.class, new RenderItemAirshipV2EmeraldOrange(VCRender));
		registerRender(EntityItemAirshipV2EmeraldPink.class, new RenderItemAirshipV2EmeraldPink(VCRender));
		registerRender(EntityItemAirshipV2EmeraldPurple.class, new RenderItemAirshipV2EmeraldPurple(VCRender));
		registerRender(EntityItemAirshipV2EmeraldRed.class, new RenderItemAirshipV2EmeraldRed(VCRender));
		registerRender(EntityItemAirshipV2EmeraldWhite.class, new RenderItemAirshipV2EmeraldWhite(VCRender));
		registerRender(EntityItemAirshipV2EmeraldYellow.class, new RenderItemAirshipV2EmeraldYellow(VCRender));
		registerRender(EntityItemAirshipV2EmeraldAdmin.class, new RenderItemAirshipV2EmeraldAdmin(VCRender));
		
		//===========================================================================
		
		registerRender(EntityAirshipV2Wood0Normal.class, new RenderAirshipV2Wood0Normal(VCRender));
		registerRender(EntityAirshipV2Wood0Black.class, new RenderAirshipV2Wood0Black(VCRender));
		registerRender(EntityAirshipV2Wood0Blue.class, new RenderAirshipV2Wood0Blue(VCRender));
		registerRender(EntityAirshipV2Wood0Brown.class, new RenderAirshipV2Wood0Brown(VCRender));
		registerRender(EntityAirshipV2Wood0Cyan.class, new RenderAirshipV2Wood0Cyan(VCRender));
		registerRender(EntityAirshipV2Wood0Gray.class, new RenderAirshipV2Wood0Gray(VCRender));
		registerRender(EntityAirshipV2Wood0Green.class, new RenderAirshipV2Wood0Green(VCRender));
		registerRender(EntityAirshipV2Wood0LightBlue.class, new RenderAirshipV2Wood0LightBlue(VCRender));
		registerRender(EntityAirshipV2Wood0LightGray.class, new RenderAirshipV2Wood0LightGray(VCRender));
		registerRender(EntityAirshipV2Wood0Lime.class, new RenderAirshipV2Wood0Lime(VCRender));
		registerRender(EntityAirshipV2Wood0Magenta.class, new RenderAirshipV2Wood0Magenta(VCRender));
		registerRender(EntityAirshipV2Wood0Orange.class, new RenderAirshipV2Wood0Orange(VCRender));
		registerRender(EntityAirshipV2Wood0Pink.class, new RenderAirshipV2Wood0Pink(VCRender));
		registerRender(EntityAirshipV2Wood0Purple.class, new RenderAirshipV2Wood0Purple(VCRender));
		registerRender(EntityAirshipV2Wood0Red.class, new RenderAirshipV2Wood0Red(VCRender));
		registerRender(EntityAirshipV2Wood0White.class, new RenderAirshipV2Wood0White(VCRender));
		registerRender(EntityAirshipV2Wood0Yellow.class, new RenderAirshipV2Wood0Yellow(VCRender));
		registerRender(EntityAirshipV2Wood0Admin.class, new RenderAirshipV2Wood0Admin(VCRender));
		
		registerRender(EntityAirshipV2IronNormal.class, new RenderAirshipV2IronNormal(VCRender));
		registerRender(EntityAirshipV2IronBlack.class, new RenderAirshipV2IronBlack(VCRender));
		registerRender(EntityAirshipV2IronBlue.class, new RenderAirshipV2IronBlue(VCRender));
		registerRender(EntityAirshipV2IronBrown.class, new RenderAirshipV2IronBrown(VCRender));
		registerRender(EntityAirshipV2IronCyan.class, new RenderAirshipV2IronCyan(VCRender));
		registerRender(EntityAirshipV2IronGray.class, new RenderAirshipV2IronGray(VCRender));
		registerRender(EntityAirshipV2IronGreen.class, new RenderAirshipV2IronGreen(VCRender));
		registerRender(EntityAirshipV2IronLightBlue.class, new RenderAirshipV2IronLightBlue(VCRender));
		registerRender(EntityAirshipV2IronLightGray.class, new RenderAirshipV2IronLightGray(VCRender));
		registerRender(EntityAirshipV2IronLime.class, new RenderAirshipV2IronLime(VCRender));
		registerRender(EntityAirshipV2IronMagenta.class, new RenderAirshipV2IronMagenta(VCRender));
		registerRender(EntityAirshipV2IronOrange.class, new RenderAirshipV2IronOrange(VCRender));
		registerRender(EntityAirshipV2IronPink.class, new RenderAirshipV2IronPink(VCRender));
		registerRender(EntityAirshipV2IronPurple.class, new RenderAirshipV2IronPurple(VCRender));
		registerRender(EntityAirshipV2IronRed.class, new RenderAirshipV2IronRed(VCRender));
		registerRender(EntityAirshipV2IronWhite.class, new RenderAirshipV2IronWhite(VCRender));
		registerRender(EntityAirshipV2IronYellow.class, new RenderAirshipV2IronYellow(VCRender));
		registerRender(EntityAirshipV2IronAdmin.class, new RenderAirshipV2IronAdmin(VCRender));
		
		registerRender(EntityAirshipV2RedstoneNormal.class, new RenderAirshipV2RedstoneNormal(VCRender));
		registerRender(EntityAirshipV2RedstoneBlack.class, new RenderAirshipV2RedstoneBlack(VCRender));
		registerRender(EntityAirshipV2RedstoneBlue.class, new RenderAirshipV2RedstoneBlue(VCRender));
		registerRender(EntityAirshipV2RedstoneBrown.class, new RenderAirshipV2RedstoneBrown(VCRender));
		registerRender(EntityAirshipV2RedstoneCyan.class, new RenderAirshipV2RedstoneCyan(VCRender));
		registerRender(EntityAirshipV2RedstoneGray.class, new RenderAirshipV2RedstoneGray(VCRender));
		registerRender(EntityAirshipV2RedstoneGreen.class, new RenderAirshipV2RedstoneGreen(VCRender));
		registerRender(EntityAirshipV2RedstoneLightBlue.class, new RenderAirshipV2RedstoneLightBlue(VCRender));
		registerRender(EntityAirshipV2RedstoneLightGray.class, new RenderAirshipV2RedstoneLightGray(VCRender));
		registerRender(EntityAirshipV2RedstoneLime.class, new RenderAirshipV2RedstoneLime(VCRender));
		registerRender(EntityAirshipV2RedstoneMagenta.class, new RenderAirshipV2RedstoneMagenta(VCRender));
		registerRender(EntityAirshipV2RedstoneOrange.class, new RenderAirshipV2RedstoneOrange(VCRender));
		registerRender(EntityAirshipV2RedstonePink.class, new RenderAirshipV2RedstonePink(VCRender));
		registerRender(EntityAirshipV2RedstonePurple.class, new RenderAirshipV2RedstonePurple(VCRender));
		registerRender(EntityAirshipV2RedstoneRed.class, new RenderAirshipV2RedstoneRed(VCRender));
		registerRender(EntityAirshipV2RedstoneWhite.class, new RenderAirshipV2RedstoneWhite(VCRender));
		registerRender(EntityAirshipV2RedstoneYellow.class, new RenderAirshipV2RedstoneYellow(VCRender));
		registerRender(EntityAirshipV2RedstoneAdmin.class, new RenderAirshipV2RedstoneAdmin(VCRender));
		
		registerRender(EntityAirshipV2GoldNormal.class, new RenderAirshipV2GoldNormal(VCRender));
		registerRender(EntityAirshipV2GoldBlack.class, new RenderAirshipV2GoldBlack(VCRender));
		registerRender(EntityAirshipV2GoldBlue.class, new RenderAirshipV2GoldBlue(VCRender));
		registerRender(EntityAirshipV2GoldBrown.class, new RenderAirshipV2GoldBrown(VCRender));
		registerRender(EntityAirshipV2GoldCyan.class, new RenderAirshipV2GoldCyan(VCRender));
		registerRender(EntityAirshipV2GoldGray.class, new RenderAirshipV2GoldGray(VCRender));
		registerRender(EntityAirshipV2GoldGreen.class, new RenderAirshipV2GoldGreen(VCRender));
		registerRender(EntityAirshipV2GoldLightBlue.class, new RenderAirshipV2GoldLightBlue(VCRender));
		registerRender(EntityAirshipV2GoldLightGray.class, new RenderAirshipV2GoldLightGray(VCRender));
		registerRender(EntityAirshipV2GoldLime.class, new RenderAirshipV2GoldLime(VCRender));
		registerRender(EntityAirshipV2GoldMagenta.class, new RenderAirshipV2GoldMagenta(VCRender));
		registerRender(EntityAirshipV2GoldOrange.class, new RenderAirshipV2GoldOrange(VCRender));
		registerRender(EntityAirshipV2GoldPink.class, new RenderAirshipV2GoldPink(VCRender));
		registerRender(EntityAirshipV2GoldPurple.class, new RenderAirshipV2GoldPurple(VCRender));
		registerRender(EntityAirshipV2GoldRed.class, new RenderAirshipV2GoldRed(VCRender));
		registerRender(EntityAirshipV2GoldWhite.class, new RenderAirshipV2GoldWhite(VCRender));
		registerRender(EntityAirshipV2GoldYellow.class, new RenderAirshipV2GoldYellow(VCRender));
		registerRender(EntityAirshipV2GoldAdmin.class, new RenderAirshipV2GoldAdmin(VCRender));
		
		registerRender(EntityAirshipV2LapisLazuliNormal.class, new RenderAirshipV2LapisLazuliNormal(VCRender));
		registerRender(EntityAirshipV2LapisLazuliBlack.class, new RenderAirshipV2LapisLazuliBlack(VCRender));
		registerRender(EntityAirshipV2LapisLazuliBlue.class, new RenderAirshipV2LapisLazuliBlue(VCRender));
		registerRender(EntityAirshipV2LapisLazuliBrown.class, new RenderAirshipV2LapisLazuliBrown(VCRender));
		registerRender(EntityAirshipV2LapisLazuliCyan.class, new RenderAirshipV2LapisLazuliCyan(VCRender));
		registerRender(EntityAirshipV2LapisLazuliGray.class, new RenderAirshipV2LapisLazuliGray(VCRender));
		registerRender(EntityAirshipV2LapisLazuliGreen.class, new RenderAirshipV2LapisLazuliGreen(VCRender));
		registerRender(EntityAirshipV2LapisLazuliLightBlue.class, new RenderAirshipV2LapisLazuliLightBlue(VCRender));
		registerRender(EntityAirshipV2LapisLazuliLightGray.class, new RenderAirshipV2LapisLazuliLightGray(VCRender));
		registerRender(EntityAirshipV2LapisLazuliLime.class, new RenderAirshipV2LapisLazuliLime(VCRender));
		registerRender(EntityAirshipV2LapisLazuliMagenta.class, new RenderAirshipV2LapisLazuliMagenta(VCRender));
		registerRender(EntityAirshipV2LapisLazuliOrange.class, new RenderAirshipV2LapisLazuliOrange(VCRender));
		registerRender(EntityAirshipV2LapisLazuliPink.class, new RenderAirshipV2LapisLazuliPink(VCRender));
		registerRender(EntityAirshipV2LapisLazuliPurple.class, new RenderAirshipV2LapisLazuliPurple(VCRender));
		registerRender(EntityAirshipV2LapisLazuliRed.class, new RenderAirshipV2LapisLazuliRed(VCRender));
		registerRender(EntityAirshipV2LapisLazuliWhite.class, new RenderAirshipV2LapisLazuliWhite(VCRender));
		registerRender(EntityAirshipV2LapisLazuliYellow.class, new RenderAirshipV2LapisLazuliYellow(VCRender));
		registerRender(EntityAirshipV2LapisLazuliAdmin.class, new RenderAirshipV2LapisLazuliAdmin(VCRender));
		
		registerRender(EntityAirshipV2ObsidianNormal.class, new RenderAirshipV2ObsidianNormal(VCRender));
		registerRender(EntityAirshipV2ObsidianBlack.class, new RenderAirshipV2ObsidianBlack(VCRender));
		registerRender(EntityAirshipV2ObsidianBlue.class, new RenderAirshipV2ObsidianBlue(VCRender));
		registerRender(EntityAirshipV2ObsidianBrown.class, new RenderAirshipV2ObsidianBrown(VCRender));
		registerRender(EntityAirshipV2ObsidianCyan.class, new RenderAirshipV2ObsidianCyan(VCRender));
		registerRender(EntityAirshipV2ObsidianGray.class, new RenderAirshipV2ObsidianGray(VCRender));
		registerRender(EntityAirshipV2ObsidianGreen.class, new RenderAirshipV2ObsidianGreen(VCRender));
		registerRender(EntityAirshipV2ObsidianLightBlue.class, new RenderAirshipV2ObsidianLightBlue(VCRender));
		registerRender(EntityAirshipV2ObsidianLightGray.class, new RenderAirshipV2ObsidianLightGray(VCRender));
		registerRender(EntityAirshipV2ObsidianLime.class, new RenderAirshipV2ObsidianLime(VCRender));
		registerRender(EntityAirshipV2ObsidianMagenta.class, new RenderAirshipV2ObsidianMagenta(VCRender));
		registerRender(EntityAirshipV2ObsidianOrange.class, new RenderAirshipV2ObsidianOrange(VCRender));
		registerRender(EntityAirshipV2ObsidianPink.class, new RenderAirshipV2ObsidianPink(VCRender));
		registerRender(EntityAirshipV2ObsidianPurple.class, new RenderAirshipV2ObsidianPurple(VCRender));
		registerRender(EntityAirshipV2ObsidianRed.class, new RenderAirshipV2ObsidianRed(VCRender));
		registerRender(EntityAirshipV2ObsidianWhite.class, new RenderAirshipV2ObsidianWhite(VCRender));
		registerRender(EntityAirshipV2ObsidianYellow.class, new RenderAirshipV2ObsidianYellow(VCRender));
		registerRender(EntityAirshipV2ObsidianAdmin.class, new RenderAirshipV2ObsidianAdmin(VCRender));
		
		registerRender(EntityAirshipV2DiamondNormal.class, new RenderAirshipV2DiamondNormal(VCRender));
		registerRender(EntityAirshipV2DiamondBlack.class, new RenderAirshipV2DiamondBlack(VCRender));
		registerRender(EntityAirshipV2DiamondBlue.class, new RenderAirshipV2DiamondBlue(VCRender));
		registerRender(EntityAirshipV2DiamondBrown.class, new RenderAirshipV2DiamondBrown(VCRender));
		registerRender(EntityAirshipV2DiamondCyan.class, new RenderAirshipV2DiamondCyan(VCRender));
		registerRender(EntityAirshipV2DiamondGray.class, new RenderAirshipV2DiamondGray(VCRender));
		registerRender(EntityAirshipV2DiamondGreen.class, new RenderAirshipV2DiamondGreen(VCRender));
		registerRender(EntityAirshipV2DiamondLightBlue.class, new RenderAirshipV2DiamondLightBlue(VCRender));
		registerRender(EntityAirshipV2DiamondLightGray.class, new RenderAirshipV2DiamondLightGray(VCRender));
		registerRender(EntityAirshipV2DiamondLime.class, new RenderAirshipV2DiamondLime(VCRender));
		registerRender(EntityAirshipV2DiamondMagenta.class, new RenderAirshipV2DiamondMagenta(VCRender));
		registerRender(EntityAirshipV2DiamondOrange.class, new RenderAirshipV2DiamondOrange(VCRender));
		registerRender(EntityAirshipV2DiamondPink.class, new RenderAirshipV2DiamondPink(VCRender));
		registerRender(EntityAirshipV2DiamondPurple.class, new RenderAirshipV2DiamondPurple(VCRender));
		registerRender(EntityAirshipV2DiamondRed.class, new RenderAirshipV2DiamondRed(VCRender));
		registerRender(EntityAirshipV2DiamondWhite.class, new RenderAirshipV2DiamondWhite(VCRender));
		registerRender(EntityAirshipV2DiamondYellow.class, new RenderAirshipV2DiamondYellow(VCRender));
		registerRender(EntityAirshipV2DiamondAdmin.class, new RenderAirshipV2DiamondAdmin(VCRender));
		
		registerRender(EntityAirshipV2EmeraldNormal.class, new RenderAirshipV2EmeraldNormal(VCRender));
		registerRender(EntityAirshipV2EmeraldBlack.class, new RenderAirshipV2EmeraldBlack(VCRender));
		registerRender(EntityAirshipV2EmeraldBlue.class, new RenderAirshipV2EmeraldBlue(VCRender));
		registerRender(EntityAirshipV2EmeraldBrown.class, new RenderAirshipV2EmeraldBrown(VCRender));
		registerRender(EntityAirshipV2EmeraldCyan.class, new RenderAirshipV2EmeraldCyan(VCRender));
		registerRender(EntityAirshipV2EmeraldGray.class, new RenderAirshipV2EmeraldGray(VCRender));
		registerRender(EntityAirshipV2EmeraldGreen.class, new RenderAirshipV2EmeraldGreen(VCRender));
		registerRender(EntityAirshipV2EmeraldLightBlue.class, new RenderAirshipV2EmeraldLightBlue(VCRender));
		registerRender(EntityAirshipV2EmeraldLightGray.class, new RenderAirshipV2EmeraldLightGray(VCRender));
		registerRender(EntityAirshipV2EmeraldLime.class, new RenderAirshipV2EmeraldLime(VCRender));
		registerRender(EntityAirshipV2EmeraldMagenta.class, new RenderAirshipV2EmeraldMagenta(VCRender));
		registerRender(EntityAirshipV2EmeraldOrange.class, new RenderAirshipV2EmeraldOrange(VCRender));
		registerRender(EntityAirshipV2EmeraldPink.class, new RenderAirshipV2EmeraldPink(VCRender));
		registerRender(EntityAirshipV2EmeraldPurple.class, new RenderAirshipV2EmeraldPurple(VCRender));
		registerRender(EntityAirshipV2EmeraldRed.class, new RenderAirshipV2EmeraldRed(VCRender));
		registerRender(EntityAirshipV2EmeraldWhite.class, new RenderAirshipV2EmeraldWhite(VCRender));
		registerRender(EntityAirshipV2EmeraldYellow.class, new RenderAirshipV2EmeraldYellow(VCRender));
		registerRender(EntityAirshipV2EmeraldAdmin.class, new RenderAirshipV2EmeraldAdmin(VCRender));
		
	}
	
	public static void registerRender(Class<? extends Entity> classIn, Render<? extends Entity> renderItem)
	{
		RenderingRegistry.registerEntityRenderingHandler(classIn, renderItem);
	}
}
