package com.viesis.viescraft.init;

import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.registry.EntityRegistry;

import com.viesis.viescraft.ViesCraft;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Admin;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Black;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Blue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Brown;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Cyan;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Gray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Green;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1LightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1LightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Lime;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Magenta;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Normal;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Orange;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Pink;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Purple;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Red;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1White;
import com.viesis.viescraft.common.entity.airshipcolors.v1.EntityAirshipV1Yellow;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Admin;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Black;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Blue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Brown;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Cyan;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Gray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Green;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2LightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2LightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Lime;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Magenta;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Normal;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Orange;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Pink;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Purple;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Red;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2White;
import com.viesis.viescraft.common.entity.airshipcolors.v2.EntityAirshipV2Yellow;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Admin;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Black;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Blue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Brown;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Cyan;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Gray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Green;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3LightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3LightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Lime;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Magenta;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Normal;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Orange;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Pink;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Purple;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Red;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3White;
import com.viesis.viescraft.common.entity.airshipcolors.v3.EntityAirshipV3Yellow;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Admin;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Black;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Blue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Brown;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Cyan;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Gray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Green;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4LightBlue;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4LightGray;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Lime;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Magenta;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Normal;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Orange;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Pink;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Purple;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Red;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4White;
import com.viesis.viescraft.common.entity.airshipcolors.v4.EntityAirshipV4Yellow;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Admin;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Black;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Blue;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Brown;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Cyan;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Gray;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Green;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1LightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1LightGray;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Lime;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Magenta;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Normal;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Orange;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Pink;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Purple;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Red;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1White;
import com.viesis.viescraft.common.entity.airshipitems.v1.EntityItemAirshipV1Yellow;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Admin;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Black;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Blue;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Brown;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Cyan;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Gray;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Green;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2LightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2LightGray;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Lime;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Magenta;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Normal;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Orange;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Pink;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Purple;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Red;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2White;
import com.viesis.viescraft.common.entity.airshipitems.v2.EntityItemAirshipV2Yellow;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Admin;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Black;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Blue;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Brown;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Cyan;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Gray;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Green;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3LightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3LightGray;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Lime;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Magenta;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Normal;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Orange;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Pink;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Purple;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Red;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3White;
import com.viesis.viescraft.common.entity.airshipitems.v3.EntityItemAirshipV3Yellow;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Admin;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Black;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Blue;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Brown;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Cyan;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Gray;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Green;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4LightBlue;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4LightGray;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Lime;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Magenta;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Normal;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Orange;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Pink;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Purple;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Red;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4White;
import com.viesis.viescraft.common.entity.airshipitems.v4.EntityItemAirshipV4Yellow;

public class InitEntityVC {
	
	private static int entityID = 1;
	
	public static void preInit()
	{
		register("item_airship_v1_normal", EntityItemAirshipV1Normal.class, "item.airship.v1.normal", 64, 20, true);
		register("item_airship_v1_black", EntityItemAirshipV1Black.class, "item.airship.v1.black", 64, 20, true);
		register("item_airship_v1_blue", EntityItemAirshipV1Blue.class, "item.airship.v1.blue", 64, 20, true);
		register("item_airship_v1_brown", EntityItemAirshipV1Brown.class, "item.airship.v1.brown", 64, 20, true);
		register("item_airship_v1_cyan", EntityItemAirshipV1Cyan.class, "item.airship.v1.cyan", 64, 20, true);
		register("item_airship_v1_gray", EntityItemAirshipV1Gray.class, "item.airship.v1.gray", 64, 20, true);
		register("item_airship_v1_green", EntityItemAirshipV1Green.class, "item.airship.v1.green", 64, 20, true);
		register("item_airship_v1_lightblue", EntityItemAirshipV1LightBlue.class, "item.airship.v1.lightblue", 64, 20, true);
		register("item_airship_v1_lightgray", EntityItemAirshipV1LightGray.class, "item.airship.v1.lightgray", 64, 20, true);
		register("item_airship_v1_lime", EntityItemAirshipV1Lime.class, "item.airship.v1.lime", 64, 20, true);
		register("item_airship_v1_magenta", EntityItemAirshipV1Magenta.class, "item.airship.v1.magenta", 64, 20, true);
		register("item_airship_v1_orange", EntityItemAirshipV1Orange.class, "item.airship.v1.orange", 64, 20, true);
		register("item_airship_v1_pink", EntityItemAirshipV1Pink.class, "item.airship.v1.pink", 64, 20, true);
		register("item_airship_v1_purple", EntityItemAirshipV1Purple.class, "item.airship.v1.purple", 64, 20, true);
		register("item_airship_v1_red", EntityItemAirshipV1Red.class, "item.airship.v1.red", 64, 20, true);
		register("item_airship_v1_white", EntityItemAirshipV1White.class, "item.airship.v1.white", 64, 20, true);
		register("item_airship_v1_yellow", EntityItemAirshipV1Yellow.class, "item.airship.v1.yellow", 64, 20, true);
		register("item_airship_v1_admin", EntityItemAirshipV1Admin.class, "item.airship.v1.admin", 64, 20, true);
		
		register("item_airship_v2_normal", EntityItemAirshipV2Normal.class, "item.airship.v2.normal", 64, 20, true);
		register("item_airship_v2_black", EntityItemAirshipV2Black.class, "item.airship.v2.black", 64, 20, true);
		register("item_airship_v2_blue", EntityItemAirshipV2Blue.class, "item.airship.v2.blue", 64, 20, true);
		register("item_airship_v2_brown", EntityItemAirshipV2Brown.class, "item.airship.v2.brown", 64, 20, true);
		register("item_airship_v2_cyan", EntityItemAirshipV2Cyan.class, "item.airship.v2.cyan", 64, 20, true);
		register("item_airship_v2_gray", EntityItemAirshipV2Gray.class, "item.airship.v2.gray", 64, 20, true);
		register("item_airship_v2_green", EntityItemAirshipV2Green.class, "item.airship.v2.green", 64, 20, true);
		register("item_airship_v2_lightblue", EntityItemAirshipV2LightBlue.class, "item.airship.v2.lightblue", 64, 20, true);
		register("item_airship_v2_lightgray", EntityItemAirshipV2LightGray.class, "item.airship.v2.lightgray", 64, 20, true);
		register("item_airship_v2_lime", EntityItemAirshipV2Lime.class, "item.airship.v2.lime", 64, 20, true);
		register("item_airship_v2_magenta", EntityItemAirshipV2Magenta.class, "item.airship.v2.magenta", 64, 20, true);
		register("item_airship_v2_orange", EntityItemAirshipV2Orange.class, "item.airship.v2.orange", 64, 20, true);
		register("item_airship_v2_pink", EntityItemAirshipV2Pink.class, "item.airship.v2.pink", 64, 20, true);
		register("item_airship_v2_purple", EntityItemAirshipV2Purple.class, "item.airship.v2.purple", 64, 20, true);
		register("item_airship_v2_red", EntityItemAirshipV2Red.class, "item.airship.v2.red", 64, 20, true);
		register("item_airship_v2_white", EntityItemAirshipV2White.class, "item.airship.v2.white", 64, 20, true);
		register("item_airship_v2_yellow", EntityItemAirshipV2Yellow.class, "item.airship.v2.yellow", 64, 20, true);
		register("item_airship_v2_admin", EntityItemAirshipV2Admin.class, "item.airship.v2.admin", 64, 20, true);
		
		register("item_airship_v3_normal", EntityItemAirshipV3Normal.class, "item.airship.v3.normal", 64, 20, true);
		register("item_airship_v3_black", EntityItemAirshipV3Black.class, "item.airship.v3.black", 64, 20, true);
		register("item_airship_v3_blue", EntityItemAirshipV3Blue.class, "item.airship.v3.blue", 64, 20, true);
		register("item_airship_v3_brown", EntityItemAirshipV3Brown.class, "item.airship.v3.brown", 64, 20, true);
		register("item_airship_v3_cyan", EntityItemAirshipV3Cyan.class, "item.airship.v3.cyan", 64, 20, true);
		register("item_airship_v3_gray", EntityItemAirshipV3Gray.class, "item.airship.v3.gray", 64, 20, true);
		register("item_airship_v3_green", EntityItemAirshipV3Green.class, "item.airship.v3.green", 64, 20, true);
		register("item_airship_v3_lightblue", EntityItemAirshipV3LightBlue.class, "item.airship.v3.lightblue", 64, 20, true);
		register("item_airship_v3_lightgray", EntityItemAirshipV3LightGray.class, "item.airship.v3.lightgray", 64, 20, true);
		register("item_airship_v3_lime", EntityItemAirshipV3Lime.class, "item.airship.v3.lime", 64, 20, true);
		register("item_airship_v3_magenta", EntityItemAirshipV3Magenta.class, "item.airship.v3.magenta", 64, 20, true);
		register("item_airship_v3_orange", EntityItemAirshipV3Orange.class, "item.airship.v3.orange", 64, 20, true);
		register("item_airship_v3_pink", EntityItemAirshipV3Pink.class, "item.airship.v3.pink", 64, 20, true);
		register("item_airship_v3_purple", EntityItemAirshipV3Purple.class, "item.airship.v3.purple", 64, 20, true);
		register("item_airship_v3_red", EntityItemAirshipV3Red.class, "item.airship.v3.red", 64, 20, true);
		register("item_airship_v3_white", EntityItemAirshipV3White.class, "item.airship.v3.white", 64, 20, true);
		register("item_airship_v3_yellow", EntityItemAirshipV3Yellow.class, "item.airship.v3.yellow", 64, 20, true);
		register("item_airship_v3_admin", EntityItemAirshipV3Admin.class, "item.airship.v3.admin", 64, 20, true);
		
		register("item_airship_v4_normal", EntityItemAirshipV4Normal.class, "item.airship.v4.normal", 64, 20, true);
		register("item_airship_v4_black", EntityItemAirshipV4Black.class, "item.airship.v4.black", 64, 20, true);
		register("item_airship_v4_blue", EntityItemAirshipV4Blue.class, "item.airship.v4.blue", 64, 20, true);
		register("item_airship_v4_brown", EntityItemAirshipV4Brown.class, "item.airship.v4.brown", 64, 20, true);
		register("item_airship_v4_cyan", EntityItemAirshipV4Cyan.class, "item.airship.v4.cyan", 64, 20, true);
		register("item_airship_v4_gray", EntityItemAirshipV4Gray.class, "item.airship.v4.gray", 64, 20, true);
		register("item_airship_v4_green", EntityItemAirshipV4Green.class, "item.airship.v4.green", 64, 20, true);
		register("item_airship_v4_lightblue", EntityItemAirshipV4LightBlue.class, "item.airship.v4.lightblue", 64, 20, true);
		register("item_airship_v4_lightgray", EntityItemAirshipV4LightGray.class, "item.airship.v4.lightgray", 64, 20, true);
		register("item_airship_v4_lime", EntityItemAirshipV4Lime.class, "item.airship.v4.lime", 64, 20, true);
		register("item_airship_v4_magenta", EntityItemAirshipV4Magenta.class, "item.airship.v4.magenta", 64, 20, true);
		register("item_airship_v4_orange", EntityItemAirshipV4Orange.class, "item.airship.v4.orange", 64, 20, true);
		register("item_airship_v4_pink", EntityItemAirshipV4Pink.class, "item.airship.v4.pink", 64, 20, true);
		register("item_airship_v4_purple", EntityItemAirshipV4Purple.class, "item.airship.v4.purple", 64, 20, true);
		register("item_airship_v4_red", EntityItemAirshipV4Red.class, "item.airship.v4.red", 64, 20, true);
		register("item_airship_v4_white", EntityItemAirshipV4White.class, "item.airship.v4.white", 64, 20, true);
		register("item_airship_v4_yellow", EntityItemAirshipV4Yellow.class, "item.airship.v4.yellow", 64, 20, true);
		register("item_airship_v4_admin", EntityItemAirshipV4Admin.class, "item.airship.v4.admin", 64, 20, true);
		
		//===========================================
		
		register("airship_v1_normal", EntityAirshipV1Normal.class, "airship.v1.normal", 64, 1, true);
		register("airship_v1_black", EntityAirshipV1Black.class, "airship.v1.black", 64, 1, true);
		register("airship_v1_blue", EntityAirshipV1Blue.class, "airship.v1.blue", 64, 1, true);
		register("airship_v1_brown", EntityAirshipV1Brown.class, "airship.v1.brown", 64, 1, true);
		register("airship_v1_cyan", EntityAirshipV1Cyan.class, "airship.v1.cyan", 64, 1, true);
		register("airship_v1_gray", EntityAirshipV1Gray.class, "airship.v1.gray", 64, 1, true);
		register("airship_v1_green", EntityAirshipV1Green.class, "airship.v1.green", 64, 1, true);
		register("airship_v1_lightblue", EntityAirshipV1LightBlue.class, "airship.v1.lightblue", 64, 1, true);
		register("airship_v1_lightgray", EntityAirshipV1LightGray.class, "airship.v1.lightgray", 64, 1, true);
		register("airship_v1_lime", EntityAirshipV1Lime.class, "airship.v1.lime", 64, 1, true);
		register("airship_v1_magenta", EntityAirshipV1Magenta.class, "airship.v1.magenta", 64, 1, true);
		register("airship_v1_orange", EntityAirshipV1Orange.class, "airship.v1.orange", 64, 1, true);
		register("airship_v1_pink", EntityAirshipV1Pink.class, "airship.v1.pink", 64, 1, true);
		register("airship_v1_purple", EntityAirshipV1Purple.class, "airship.v1.purple", 64, 1, true);
		register("airship_v1_red", EntityAirshipV1Red.class, "airship.v1.red", 64, 1, true);
		register("airship_v1_white", EntityAirshipV1White.class, "airship.v1.white", 64, 1, true);
		register("airship_v1_yellow", EntityAirshipV1Yellow.class, "airship.v1.yellow", 64, 1, true);
		register("airship_v1_admin", EntityAirshipV1Admin.class, "airship.v1.admin", 64, 1, true);
		
		register("airship_v2_normal", EntityAirshipV2Normal.class, "airship.v2.normal", 64, 1, true);
		register("airship_v2_black", EntityAirshipV2Black.class, "airship.v2.black", 64, 1, true);
		register("airship_v2_blue", EntityAirshipV2Blue.class, "airship.v2.blue", 64, 1, true);
		register("airship_v2_brown", EntityAirshipV2Brown.class, "airship.v2.brown", 64, 1, true);
		register("airship_v2_cyan", EntityAirshipV2Cyan.class, "airship.v2.cyan", 64, 1, true);
		register("airship_v2_gray", EntityAirshipV2Gray.class, "airship.v2.gray", 64, 1, true);
		register("airship_v2_green", EntityAirshipV2Green.class, "airship.v2.green", 64, 1, true);
		register("airship_v2_lightblue", EntityAirshipV2LightBlue.class, "airship.v2.lightblue", 64, 1, true);
		register("airship_v2_lightgray", EntityAirshipV2LightGray.class, "airship.v2.lightgray", 64, 1, true);
		register("airship_v2_lime", EntityAirshipV2Lime.class, "airship.v2.lime", 64, 1, true);
		register("airship_v2_magenta", EntityAirshipV2Magenta.class, "airship.v2.magenta", 64, 1, true);
		register("airship_v2_orange", EntityAirshipV2Orange.class, "airship.v2.orange", 64, 1, true);
		register("airship_v2_pink", EntityAirshipV2Pink.class, "airship.v2.pink", 64, 1, true);
		register("airship_v2_purple", EntityAirshipV2Purple.class, "airship.v2.purple", 64, 1, true);
		register("airship_v2_red", EntityAirshipV2Red.class, "airship.v2.red", 64, 1, true);
		register("airship_v2_white", EntityAirshipV2White.class, "airship.v2.white", 64, 1, true);
		register("airship_v2_yellow", EntityAirshipV2Yellow.class, "airship.v2.yellow", 64, 1, true);
		register("airship_v2_admin", EntityAirshipV2Admin.class, "airship.v2.admin", 64, 1, true);
		
		register("airship_v3_normal", EntityAirshipV3Normal.class, "airship.v3.normal", 64, 1, true);
		register("airship_v3_black", EntityAirshipV3Black.class, "airship.v3.black", 64, 1, true);
		register("airship_v3_blue", EntityAirshipV3Blue.class, "airship.v3.blue", 64, 1, true);
		register("airship_v3_brown", EntityAirshipV3Brown.class, "airship.v3.brown", 64, 1, true);
		register("airship_v3_cyan", EntityAirshipV3Cyan.class, "airship.v3.cyan", 64, 1, true);
		register("airship_v3_gray", EntityAirshipV3Gray.class, "airship.v3.gray", 64, 1, true);
		register("airship_v3_green", EntityAirshipV3Green.class, "airship.v3.green", 64, 1, true);
		register("airship_v3_lightblue", EntityAirshipV3LightBlue.class, "airship.v3.lightblue", 64, 1, true);
		register("airship_v3_lightgray", EntityAirshipV3LightGray.class, "airship.v3.lightgray", 64, 1, true);
		register("airship_v3_lime", EntityAirshipV3Lime.class, "airship.v3.lime", 64, 1, true);
		register("airship_v3_magenta", EntityAirshipV3Magenta.class, "airship.v3.magenta", 64, 1, true);
		register("airship_v3_orange", EntityAirshipV3Orange.class, "airship.v3.orange", 64, 1, true);
		register("airship_v3_pink", EntityAirshipV3Pink.class, "airship.v3.pink", 64, 1, true);
		register("airship_v3_purple", EntityAirshipV3Purple.class, "airship.v3.purple", 64, 1, true);
		register("airship_v3_red", EntityAirshipV3Red.class, "airship.v3.red", 64, 1, true);
		register("airship_v3_white", EntityAirshipV3White.class, "airship.v3.white", 64, 1, true);
		register("airship_v3_yellow", EntityAirshipV3Yellow.class, "airship.v3.yellow", 64, 1, true);
		register("airship_v3_admin", EntityAirshipV3Admin.class, "airship.v3.admin", 64, 1, true);
		
		register("airship_v4_normal", EntityAirshipV4Normal.class, "airship.v4.normal", 64, 1, true);
		register("airship_v4_black", EntityAirshipV4Black.class, "airship.v4.black", 64, 1, true);
		register("airship_v4_blue", EntityAirshipV4Blue.class, "airship.v4.blue", 64, 1, true);
		register("airship_v4_brown", EntityAirshipV4Brown.class, "airship.v4.brown", 64, 1, true);
		register("airship_v4_cyan", EntityAirshipV4Cyan.class, "airship.v4.cyan", 64, 1, true);
		register("airship_v4_gray", EntityAirshipV4Gray.class, "airship.v4.gray", 64, 1, true);
		register("airship_v4_green", EntityAirshipV4Green.class, "airship.v4.green", 64, 1, true);
		register("airship_v4_lightblue", EntityAirshipV4LightBlue.class, "airship.v4.lightblue", 64, 1, true);
		register("airship_v4_lightgray", EntityAirshipV4LightGray.class, "airship.v4.lightgray", 64, 1, true);
		register("airship_v4_lime", EntityAirshipV4Lime.class, "airship.v4.lime", 64, 1, true);
		register("airship_v4_magenta", EntityAirshipV4Magenta.class, "airship.v4.magenta", 64, 1, true);
		register("airship_v4_orange", EntityAirshipV4Orange.class, "airship.v4.orange", 64, 1, true);
		register("airship_v4_pink", EntityAirshipV4Pink.class, "airship.v4.pink", 64, 1, true);
		register("airship_v4_purple", EntityAirshipV4Purple.class, "airship.v4.purple", 64, 1, true);
		register("airship_v4_red", EntityAirshipV4Red.class, "airship.v4.red", 64, 1, true);
		register("airship_v4_white", EntityAirshipV4White.class, "airship.v4.white", 64, 1, true);
		register("airship_v4_yellow", EntityAirshipV4Yellow.class, "airship.v4.yellow", 64, 1, true);
		register("airship_v4_admin", EntityAirshipV4Admin.class, "airship.v4.admin", 64, 1, true);
	}
	
	public static void register(String name, Class<? extends Entity> entityClass, String entityName, int trackingRange, int updateFrequency, boolean sendsVelocityUpdates)
	{
		EntityRegistry.registerModEntity(new ResourceLocation("vc:" + name), entityClass, entityName, entityID++, ViesCraft.instance, trackingRange, updateFrequency, sendsVelocityUpdates);
	}
}
